Refactor TS code snippet to interfaces
microsoftgraph/microsoft-graph-devx-api pull request #1008
Opened 2022-05-20 09:17 UTC by rkodev

## Overview

Brief description of what this PR does, and why it is needed.

### Demo

Optional. Screenshots, `curl` examples, etc.

### Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Testing Instructions

* How to test this PR
* Prefer bulleted description
* Start after checking out this branch
* Include any setup required, such as bundling scripts, restarting services, etc.
* Include test case, and expected output

2022-05-30 17:41 UTC, baywet requested changes

2022-05-30 17:41 UTC, baywet commented on CodeSnippetsReflection.OpenAPI/ModelGraph/SnippetCodeGraph.cs
> +            return Headers.Any() == true;
```suggestion
            return Headers.Any();
```

2022-05-30 17:41 UTC, baywet commented on CodeSnippetsReflection.OpenAPI/CodeSnippetsReflection.OpenAPI.csproj
> +    <PackageReference Include="System.Linq" Version="4.3.0" />
can you provide a bit more context on why this reference is needed? this version is from 4.3.0. And system.linq should be included in net6 api surface. [example kiota which makes extended use of linq](https://github.com/microsoft/kiota/blob/main/src/Kiota.Builder/Kiota.Builder.csproj)

2022-05-30 17:41 UTC, baywet commented on CodeSnippetsReflection.OpenAPI.Test/ModelGraphBuilderTests.cs
> +                    if (result != null) return result;
```suggestion
                    if(findProperyInSnipet(param, name) is not null result) return result;
```

2022-05-30 17:41 UTC, baywet commented on CodeSnippetsReflection.OpenAPI.Test/TypeScriptGeneratorTest.cs
> +            Assert.Contains(
couldn't we define an extension method of Assert.EqualsIgnoreWithespace and avoid duplication for each test this way?

2022-05-30 17:41 UTC, baywet commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/TypeScriptGenerator.cs
> +                builder.AppendLine($"{indentManager.GetIndent()}\"{param.Name}\": \"{param.Value.Replace("\"", "\\\"")}\",");
could the replacement of quotes be defined as an extension method instead?

2022-05-30 17:41 UTC, baywet commented on CodeSnippetsReflection.OpenAPI/ModelGraph/ModelGraphBuilder.cs
> +            var parameters = new List<CodeProperty>();
could this be used instead of doing the parsing manually? https://docs.microsoft.com/en-us/dotnet/api/system.web.httputility.parsequerystring?view=net-6.0

2022-05-30 17:41 UTC, baywet commented on CodeSnippetsReflection.OpenAPI/ModelGraph/ModelGraphBuilder.cs
> +        public static SnippetCodeGraph BuildCodeGraph(SnippetModel snippetModel)
why is there a need for a static factory instead of using a constructor?

2022-05-30 18:15 UTC, rkodev commented on CodeSnippetsReflection.OpenAPI/ModelGraph/ModelGraphBuilder.cs
> +        public static SnippetCodeGraph BuildCodeGraph(SnippetModel snippetModel)
In this case, we only need a single such object in memory

2022-05-31 03:56 UTC, rkodev commented on CodeSnippetsReflection.OpenAPI/ModelGraph/ModelGraphBuilder.cs
> +        public static SnippetCodeGraph BuildCodeGraph(SnippetModel snippetModel)
sorry, yes this can be a constructor parameter for SnippetCodeGraph class

2022-05-31 12:51 UTC, baywet requested changes
Thanks for taking in the changes, a couple of additional comments.

2022-05-31 12:51 UTC, baywet commented on CodeSnippetsReflection.OpenAPI/ModelGraph/SnippetCodeGraph.cs
> +                }
```suggestion
                foreach (var groups in matches.Select(m => m.Groups)))
                {
                    var key = groups[1].Value;
                    var value = groups[2].Value;
                    replacements.Add(key, value);
                    queryParams = queryParams.Replace(value, string.Empty);
                }
```

2022-05-31 12:51 UTC, baywet commented on CodeSnippetsReflection.OpenAPI.Test/SnippetCodeGraphTests.cs
> +                    if (result != null) return result;
```suggestion
                    if(findProperyInSnipet(param, name) is CodeProperty result) return result;
```

2022-05-31 13:13 UTC, baywet commented on CodeSnippetsReflection.OpenAPI/ModelGraph/SnippetCodeGraph.cs
> +                foreach (var groups in matches.Select(m => m.Groups)))
```suggestion
                foreach (var groups in matches.Select(m => m.Groups))
```

2022-05-31 14:25 UTC, rkodev commented
@baywet Yes. That was the next step that I was thinking of. We can add all the changes to this PR for both Go and PowerShell, was afraid might be too large for 1 PR but I'm happy to add both to this

2022-05-31 14:55 UTC, baywet commented
I'd vote to go ahead with that change, which should also include CSharp and Java

2022-05-31 20:08 UTC, zengin requested changes
left a few minor comments.

2022-05-31 20:08 UTC, zengin commented on CodeSnippetsReflection.OpenAPI.Test/SnippetCodeGraphTests.cs
> +            Assert.Equal("False", property?.Value);
guaranteed to be not null in these lines.
```suggestion
            Assert.Equal(PropertyType.Boolean, property.PropertyType);
            Assert.Equal("False", property.Value);
```

2022-05-31 20:08 UTC, zengin commented on CodeSnippetsReflection.OpenAPI.Test/SnippetCodeGraphTests.cs
> +            Assert.Equal(PropertyType.Object, property?.PropertyType);
```suggestion
            Assert.Equal(PropertyType.Object, property.PropertyType);
```

2022-05-31 20:08 UTC, zengin commented on CodeSnippetsReflection.OpenAPI.Test/SnippetCodeGraphTests.cs
> +            Assert.Equal(PropertyType.Array, property?.PropertyType);
```suggestion
            Assert.Equal(PropertyType.Array, property.PropertyType);
```

2022-05-31 20:08 UTC, zengin commented on CodeSnippetsReflection.OpenAPI.Test/SnippetCodeGraphTests.cs
> +            Assert.Equal(PropertyType.Map, property?.PropertyType);
```suggestion
            Assert.Equal(PropertyType.Map, property.PropertyType);
```

2022-05-31 20:08 UTC, zengin commented on CodeSnippetsReflection.OpenAPI.Test/SnippetCodeGraphTests.cs
> +            Assert.Equal(expectedProperty2, result.Parameters.Skip(1).Take(1).First());
```suggestion
            Assert.Equal(expectedProperty2, result.Parameters.Skip(1).First());
```

2022-05-31 20:13 UTC, zengin commented
We have been waiting on this implementation for a while now to clear the TS tests. It would be nice if we can go ahead with the check-in and build other languages on top of this change gradually.

2022-06-02 12:54 UTC, baywet commented
Alright, thanks for the input @zengin. @rkodev would you mind creating an issue to follow up on that please? And feel free to assign it to yourself and start tackling it right after this PR gets merged.

2022-06-02 17:55 UTC, zengin approved these changes

2022-06-07 17:01 UTC, merged