Refactor Go Snippet generation (OpenAPI Refactor)
microsoftgraph/microsoft-graph-devx-api pull request #1021
Opened 2022-06-08 09:47 UTC by rkodev

## Overview

Brief description of what this PR does, and why it is needed.

### Demo

Optional. Screenshots, `curl` examples, etc.

### Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Testing Instructions

* How to test this PR
* Prefer bulleted description
* Start after checking out this branch
* Include any setup required, such as bundling scripts, restarting services, etc.
* Include test case, and expected output

2022-06-09 13:02 UTC, rkodev commented
- [x] Enum Generation 
Example [Docs](https://docs.microsoft.com/en-us/graph/api/outlookuser-post-mastercategories?view=graph-rest-1.0&tabs=go)

Current
```go
graphClient := msgraphsdk.NewGraphServiceClient(requestAdapter)

requestBody := msgraphsdk.NewOutlookCategory()
displayName := "Project expenses"
requestBody.SetDisplayName(&displayName)
color := "preset9"
requestBody.SetColor(&color)
result, err := graphClient.Me().Outlook().MasterCategories().Post(requestBody)
```
New Syntax
```go
graphClient := msgraphsdk.NewGraphServiceClient(requestAdapter)

requestBody := graphmodels.NewOutlookCategory()
displayName := "Project expenses"
requestBody.SetDisplayName(&displayName) 
color := graphmodels.PRESET9_CATEGORYCOLOR 
requestBody.SetColor(&color) 

result, err := graphClient.Me().Outlook().MasterCategories().Post(requestBody)
```

2022-06-09 13:02 UTC, rkodev commented
- [x] Missing Class Generation
Example [Docs](https://docs.microsoft.com/en-us/graph/api/accessreviewinstance-batchrecorddecisions?view=graph-rest-1.0&tabs=go)

Current
```go
graphClient := msgraphsdk.NewGraphServiceClient(requestAdapter)

requestBody := msgraphsdk.New()
decision := "Approve"
requestBody.SetDecision(&decision)
justification := "All principals with access need continued access to the resource (Marketing Group) as all the principals are on the marketing team"
requestBody.SetJustification(&justification)
```
New Syntax
```go
graphClient := msgraphsdk.NewGraphServiceClient(requestAdapter)

requestBody := graphmodels.NewBatchRecordDecisionsPostRequestBody()
decision := "Approve"
requestBody.SetDecision(&decision) 
justification := "All principals with access need continued access to the resource (Marketing Group) as all the principals are on the marketing team"
requestBody.SetJustification(&justification) 
resourceId := "a5c51e59-3fcd-4a37-87a1-835c0c21488a"
requestBody.SetResourceId(&resourceId) 
```

2022-06-09 13:03 UTC, rkodev commented
- [x] Nested Object Generation
Example [Docs](https://docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&tabs=go)

Current
```go
graphClient := msgraphsdk.NewGraphServiceClient(requestAdapter)

requestBody := msgraphsdk.NewChatMessage()
body := msgraphsdk.NewItemBody()
requestBody.SetBody(body)
contentType := "html"
body.SetContentType(&contentType)
content := "Hello World <at id="0">Jane Smith</at>"
body.SetContent(&content)
requestBody.SetMentions( []ChatMessageMention {
	msgraphsdk.NewChatMessageMention(),
	SetAdditionalData(map[string]interface{}{
		"id": ,
		"mentionText": "Jane Smith",
	}
}
teamId := "team-id"
channelId := "channel-id"
result, err := graphClient.TeamsById(&teamId).ChannelsById(&channelId).Messages().Post(requestBody)
```
New Syntax
```go
graphClient := msgraphsdk.NewGraphServiceClient(requestAdapter)

headers := map[string]string{
	"Prefer": "outlook.timezone=\"Pacific Standard Time\"",
}
configuration := &graphconfig.MessagesRequestBuilderPostRequestConfiguration{
	Headers: headers,
}
requestBody := graphmodels.NewChatMessage()


chatMessageMention := graphmodels.NewChatMessageMention()
id := int32(0)
chatMessageMention.SetId(&id) 
mentionText := "Jane Smith"
chatMessageMention.SetMentionText(&mentionText) 
mentioned := graphmodels.NewChatMessageMentionedIdentitySet()
user := graphmodels.NewIdentity()
displayName := "Jane Smith"
user.SetDisplayName(&displayName) 
id := "ef1c916a-3135-4417-ba27-8eb7bd084193"
user.SetId(&id) 
additionalData := map[string]interface{}{
	"userIdentityType" : "aadUser", 
}
user.SetAdditionalData(additionalData)
mentioned.SetUser(user)
chatMessageMention.SetMentioned(mentioned)

mentions := []graphmodels.ChatMessageMentionable {
	chatMessageMention,

}
requestBody.SetMentions(mentions)

result, err := graphClient.TeamsById("team-id").ChannelsById("channel-id").Messages().PostWithRequestConfigurationAndResponseHandler(requestBody, configuration, nil)

```

2022-06-09 13:36 UTC, rkodev commented
@zengin getting about 71 % pass rate after generating the snippets and running the raptor tests

2022-06-10 19:11 UTC, zengin requested changes
- Awesome PR description!
- Great proof that your refactor pays off dividends really fast!
- Great Raptor results after fixing issues!

left a few minor comments to address.

2022-06-10 19:11 UTC, zengin commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/GoGenerator.cs
> +                builder.AppendLine("\n");
unless you want this to be normalized to the Unix-way all the time:
```suggestion
                builder.AppendLine(Environment.NewLine);
```

2022-06-10 19:11 UTC, zengin commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/GoGenerator.cs
> +                builder.AppendLine("\n");
I don't think this will be normalized to the Unix-way, because you are already calling AppendLine which should already respect the environment while appending new lines.

2022-06-10 19:11 UTC, zengin commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/GoGenerator.cs
> +                builder.AppendLine(objectBuilder.ToString());
Avoid calling `ToString()` until it is absolutely needed. There might be optimizations that you can benefit from if you call the variation that takes the StringBuilder directly.
```suggestion
                builder.Append(objectBuilder);
                builder.AppendLine();
```

Same comment goes for all the other instances where the string is passed when passing StringBuilder is possible.

2022-06-13 09:44 UTC, rkodev commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/GoGenerator.cs
> +                builder.AppendLine(objectBuilder.ToString());
This is the only instance for the `objectBuilder` , which is a separate builder from `builder` calls the `ToString`.  the reason was its the `builder` object traverses the object model from the `root` of the tree, but when writing an array, all the instances of the objects to be part of the array need to be generated first then added to the array have a look at this example https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/1021#issuecomment-1151093487

For this reason, a second builder to traverse all the children was required

2022-06-13 16:50 UTC, zengin commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/GoGenerator.cs
> +                builder.AppendLine(objectBuilder.ToString());
I understand the need for the second builder, my suggestion is not to call `ToString()` on it. The `Append` call that takes `StringBuilder` may handle buffer transfer more efficiently than converting it into `string` and then passing into the outer builder as a string.

2022-06-13 17:34 UTC, zengin commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/GoGenerator.cs
> +                builder.AppendLine(objectBuilder.ToString());
Ok, I ran the benchmarks. With `ToString` it is faster even though memory allocations are bigger. I don't think we will be memory bound here, so we can keep the code as is:

```
// * Summary *

BenchmarkDotNet=v0.13.1, OS=Windows 10.0.22000
Intel Xeon W-2123 CPU 3.60GHz, 1 CPU, 8 logical and 4 physical cores
.NET SDK=6.0.300
  [Host]     : .NET 6.0.5 (6.0.522.21309), X64 RyuJIT
  DefaultJob : .NET 6.0.5 (6.0.522.21309), X64 RyuJIT


|          Method |     Mean |    Error |   StdDev | Rank |      Gen 0 |     Gen 1 |     Gen 2 | Allocated |
|---------------- |---------:|---------:|---------:|-----:|-----------:|----------:|----------:|----------:|
|    WithToString | 87.59 ms | 1.721 ms | 4.883 ms |    1 | 18857.1429 | 4714.2857 | 1714.2857 |    142 MB |
| WithoutToString | 94.19 ms | 2.830 ms | 8.256 ms |    2 | 19166.6667 | 5000.0000 | 1500.0000 |    131 MB |
```

Benchmark code using BenchmarkDotNet package:
```csharp
using System.Text;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

public static class Program
{
    public static void Main(string[] args)
    {
        var summary = BenchmarkRunner.Run<Benchmarker>();
    }

    [MemoryDiagnoser]
    [RankColumn]
    public class Benchmarker
    {
        static int items = 1000000;
        [Benchmark]
        public string WithToString()
        {
            var sb = new StringBuilder();
            for (int i = 0; i < items; i++)
            {
                sb.Append(i.ToString());
            }
            var innerSB = new StringBuilder();
            for (int i = 0; i < items; i++)
            {
                innerSB.Append(i.ToString());
            }
            sb.Append(innerSB.ToString());
            return sb.ToString();
        }

        [Benchmark]
        public string WithoutToString()
        {
            var sb = new StringBuilder();
            for (int i = 0; i < items; i++)
            {
                sb.Append(i.ToString());
            }
            var innerSB = new StringBuilder();
            for (int i = 0; i < items; i++)
            {
                innerSB.Append(i.ToString());
            }
            sb.Append(innerSB);
            return sb.ToString();
        }
    }
}
```

2022-06-13 17:38 UTC, zengin commented on CodeSnippetsReflection.OpenAPI.Test/SnippetCodeGraphTests.cs
> +            var result = new SnippetCodeGraph(new SnippetModel(requestPayload, ServiceRootUrl, await GetV1TreeNode()));
this is not really encapsulating. Model object creation stays as caller's responsibility. The alternative I am suggesting is passing in requestPayload, ServiceRootUrl and tree node directly into a `SnippetCodeGraph` constructor and that constructor creating the model inside. Model needs not to be visible to the caller at all.

2022-06-14 06:46 UTC, rkodev commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/GoGenerator.cs
> +                builder.AppendLine(objectBuilder.ToString());
Thanks for the detailed explanation

2022-06-14 19:27 UTC, merged