WIP: PHP Snippet generation
microsoftgraph/microsoft-graph-devx-api pull request #1041
Opened 2022-06-21 14:02 UTC by SilasKenneth

## Overview

Add snippet generation support for PHP Kiota based SDK.

### Demo

Optional. Screenshots, `curl` examples, etc.

### Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Testing Instructions

2022-06-21 14:05 UTC, SilasKenneth commented on pipelines/snippets.yml
> -    $buildLanguages = if ("$env:LANGUAGES") { "$env:LANGUAGES" } else { "$(snippetLanguages)" }
For testing purposes.

2022-06-24 16:45 UTC, zengin requested changes
@rkodev could PHP also use the `SnippetCodeGraph` you have created for OpenAPI based generation?

2022-06-27 10:58 UTC, rkodev commented on pipelines/snippets.yml
> +    $buildLanguages = if ("$env:LANGUAGES") { "$(snippetLanguage)" } else { "$(snippetLanguages)" }
You can use create the pipeline varaible `LANGUAGE` and pass `php` to the pipeline. Commiting PHP to the pipeline will force any test pipeline to create a new branch / commit to test

2022-06-27 17:32 UTC, baywet requested changes

2022-06-27 17:32 UTC, baywet commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/PhpGenerator.cs
> +        if (snippetModel.ResponseSchema == null || (snippetModel.ResponseSchema.Properties.Count == 1 && snippetModel.ResponseSchema.Properties.First().Key.Equals("error",StringComparison.OrdinalIgno
```suggestion
        if (snippetModel.ResponseSchema == null || (snippetModel.ResponseSchema.Properties.Any() && snippetModel.ResponseSchema.Properties.First(x => x.Key.Equals("error",StringComparison.OrdinalIgnoreCase)))
```

2022-07-08 11:14 UTC, rkodev commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/PhpGenerator.cs
> +    private const string QueryParametersVarName = "queryParameters";
nit: declare constants at the start of the file

2022-07-08 11:18 UTC, rkodev commented on CodeSnippetsReflection.OpenAPI/ModelGraph/SnippetCodeGraph.cs
> +            var NumberParameters = ImmutableHashSet.Create("skip", "top");
nice!

2022-07-08 12:47 UTC, calebkiage approved these changes

2022-07-08 13:27 UTC, baywet approved these changes

2022-07-08 13:27 UTC, baywet commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/PhpGenerator.cs
> +        var enumClass = enumParts.First();
wrap with if any condition to avoid failure?

2022-07-09 00:24 UTC, zengin approved these changes

2022-07-12 07:53 UTC, merged