Remove PHP from weekly docs generation + Fix Sonarcloud issue
microsoftgraph/microsoft-graph-devx-api pull request #1061
Opened 2022-07-12 08:53 UTC by SilasKenneth

## Overview

- Fix SonarCloud issue with unescaped regex pattern.
- Remove PHP from weekly docs generation Pipeline.
### Demo

Optional. Screenshots, `curl` examples, etc.

### Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Testing Instructions

* How to test this PR
* Prefer bulleted description
* Start after checking out this branch
* Include any setup required, such as bundling scripts, restarting services, etc.
* Include test case, and expected output

2022-07-12 12:37 UTC, rkodev submitted a review, later dismissed

2022-07-12 13:00 UTC, baywet requested changes

2022-07-12 13:00 UTC, baywet commented on pipelines/snippets.yml
> +  snippetLanguages: 'C#,JavaScript,Java,Go,PowerShell'
I'd argue we should keep PHP since we don't have snippets for the older version of the SDK AFAIK and since Go has snippets (but with a warning message) https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=go

2022-07-12 13:02 UTC, rkodev commented on pipelines/snippets.yml
> +  snippetLanguages: 'C#,JavaScript,Java,Go,PowerShell'
@baywet Should this apply to Typescript as well?

2022-07-12 13:04 UTC, baywet commented on pipelines/snippets.yml
> +  snippetLanguages: 'C#,JavaScript,Java,Go,PowerShell'
TypeScript is a different story since we already have a JavaScript tab here.
Same for C#, or Java when the preview comes out.
PMs are working on a design for languages that already have snippets.

2022-07-12 14:42 UTC, baywet submitted a review, later dismissed
I can see that you manually did the opposite change. In case you didn't know you could:
1. git revert commit-sha (to apply an automatically generated opposite commit)
2. git rebase -i (and then drop in front of the commit to drop it from history, requires a force push afterwards)

2022-07-12 17:54 UTC, baywet requested changes

2022-07-12 17:54 UTC, baywet commented on CodeSnippetsReflection.OpenAPI/ModelGraph/SnippetCodeGraph.cs
> +            if ((propSchema == null || propSchema.Enum.Count == 0) && enumSchema == null)
```suggestion
            if (enumSchema == null || propSchema?.Enum.Count == 0)
```

2022-07-13 11:17 UTC, baywet approved these changes

2022-07-13 11:17 UTC, merged