Added provision for mime contents on powershell snippets
microsoftgraph/microsoft-graph-devx-api pull request #1075
Opened 2022-07-14 10:00 UTC by timayabi2020

## Overview

This PR fixes powershell snippet generation by including -OutFile parameter whenever HTTP snippets returns a stream response.  We make use of the optional query parameter $value to get the mime content of the message.
It addresses this [raptor issue](https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/1148) and partly addresses [this devx issue](https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1058)

### Demo
<img width="627" alt="image" src="https://user-images.githubusercontent.com/10947120/178956526-744e0694-0272-4e01-abd3-02e34a2bb6cc.png">

2022-07-14 12:02 UTC, baywet requested changes

2022-07-14 12:02 UTC, baywet commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/PowerShellGenerator.cs
> +        private bool RequiresMIMEContentOutPut(SnippetModel snippetModel, string path)
```suggestion
        private static bool RequiresMIMEContentOutPut(SnippetModel snippetModel, string path)
```

2022-07-14 14:04 UTC, baywet approved these changes

2022-07-14 14:29 UTC, merged

2022-08-04 16:48 UTC, peombwa commented
@timayabi2020, it looks like this change is applying the `-OutFile` to all PS snippets - https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=powershell#request.