Fix/php go type issue
microsoftgraph/microsoft-graph-devx-api pull request #1124
Opened 2022-08-04 13:10 UTC by SilasKenneth

## Overview

Captures more type formats for string values.
 - Boolean.
 - Double.
 - Duration.
It also simplifies the `evaluateStringProperty` method in `SnippetCodeGraph.cs`

### Demo

### Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Testing Instructions

* How to test this PR
* Prefer bulleted description
* Start after checking out this branch
* Include any setup required, such as bundling scripts, restarting services, etc.
* Include test case, and expected output

2022-08-04 13:50 UTC, baywet requested changes

2022-08-04 13:50 UTC, baywet commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/GoGenerator.cs
> +                case PropertyType.Duration:
just call parse iso duration https://github.com/microsoft/kiota-abstractions-go/blob/1ecd925f435fb1aaf0174576a0ef222044c7217a/serialization/iso_duration.go#L85

2022-08-04 13:50 UTC, baywet commented on CodeSnippetsReflection.OpenAPI/ModelGraph/SnippetCodeGraph.cs
> +        private static Dictionary<string, PropertyType> _formatPropertyTypes = new ()
```suggestion
        private static Dictionary<string, PropertyType> _formatPropertyTypes = new (StringComparer.OrdinalIgnoreCase)
```

2022-08-04 14:25 UTC, SilasKenneth commented on CodeSnippetsReflection.OpenAPI/ModelGraph/SnippetCodeGraph.cs
> +        private static Dictionary<string, PropertyType> _formatPropertyTypes = new ()
I think given that the keys are in Lowercase and I'm doing case conversion on line https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/e948a26de6cc2c7ecf8d16f5ccc6c18dd3472aec/CodeSnippetsReflection.OpenAPI/ModelGraph/SnippetCodeGraph.cs#L281
we might not need to add the suggestion.

2022-08-04 14:30 UTC, baywet commented on CodeSnippetsReflection.OpenAPI/ModelGraph/SnippetCodeGraph.cs
> +        private static Dictionary<string, PropertyType> _formatPropertyTypes = new ()
it is generally better to use the right comparer than forcing a casing before comparison.
https://docs.microsoft.com/en-us/dotnet/standard/base-types/best-practices-strings

2022-08-08 05:16 UTC, SilasKenneth commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/GoGenerator.cs
> +                case PropertyType.Duration:
Done!

2022-08-08 12:16 UTC, baywet approved these changes

2022-08-08 12:49 UTC, merged