Remove unnecessary clone when applying OpenAPI style
microsoftgraph/microsoft-graph-devx-api pull request #1147
Opened 2022-08-15 17:18 UTC by millicentachieng

## Overview

Brief description of what this PR does, and why it is needed.

### Demo

Optional. Screenshots, `curl` examples, etc.

### Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Testing Instructions

* How to test this PR
* Prefer bulleted description
* Start after checking out this branch
* Include any setup required, such as bundling scripts, restarting services, etc.
* Include test case, and expected output

2022-08-15 18:29 UTC, baywet requested changes

2022-08-15 18:29 UTC, baywet commented on OpenAPIService/OpenApiService.cs
>                  if(!includeRequestBody)
collapse this condition in the one above

2022-08-19 12:06 UTC, irvinesunday approved these changes

2022-08-19 12:22 UTC, baywet approved these changes

2022-08-19 12:41 UTC, merged