Have OpenApiConvertSettings configurable for each style
microsoftgraph/microsoft-graph-devx-api pull request #1156
Opened 2022-08-24 11:25 UTC by millicentachieng

## Overview
Closes #1047
Closes #956
Brief description of what this PR does, and why it is needed.

### Demo

Optional. Screenshots, `curl` examples, etc.

### Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Testing Instructions

* How to test this PR
* Prefer bulleted description
* Start after checking out this branch
* Include any setup required, such as bundling scripts, restarting services, etc.
* Include test case, and expected output

2022-10-12 07:06 UTC, baywet requested changes

2022-10-12 07:06 UTC, baywet commented on GraphWebApi/appsettings.json
> +      "PowerShell": {
It feels like some of those profiles should have more settings defined here, can you circle back with the different owners to understand better their settings requirements please?

2022-10-12 07:06 UTC, baywet commented on OpenAPIService/OpenApiService.cs
> +                var convertSettingsForStyle = _configuration.GetSection($"OpenAPI:ConvertSettings:{style}")
use the configuration binder instead of building it manually.

https://github.com/microsoft/kiota/blob/3cc6161845aef7276de44757aead6e1820dc6599/src/kiota/Handlers/BaseKiotaCommandHandler.cs#L25

2022-10-18 11:57 UTC, irvinesunday commented on GraphWebApi/appsettings.json
> +      "PowerShell": {
I know PowerShell does not like `ShowRootPath` and doesn't care about `ShowLinks`. These are GE-specific settings. And we def. want all styles to implement `ExpandDerivedTypesNavigationProperties=false` for now.
`DeclarePathParametersOnPathItem=true` and `EnableODataAnnotationReferencesForResponses=false` can be implemented for PowerShell.

2022-10-18 12:36 UTC, millicentachieng commented on GraphWebApi/appsettings.json
> +      "PowerShell": {
Thanks for the info @irvinesunday. I'll update the settings.

2022-10-18 12:48 UTC, millicentachieng commented on OpenAPIService/OpenApiService.cs
> +                var convertSettingsForStyle = _configuration.GetSection($"OpenAPI:ConvertSettings:{style}")
@baywet I could bind the configuration to `OpenApiConvertSettings` but the class defines some default values and it would be impossible to tell which values came from the configuration.

2022-10-18 12:52 UTC, baywet commented on OpenAPIService/OpenApiService.cs
> +                var convertSettingsForStyle = _configuration.GetSection($"OpenAPI:ConvertSettings:{style}")
If the default is acceptable for the profile, it's fine and no need to change it in the configuration. If the default is not suitable for the profile, just update the configuration. I'm not sure why we need to know where it was set from?

2022-10-18 13:36 UTC, baywet commented on OpenAPIService/OpenApiService.cs
> +                var convertSettingsForStyle = _configuration.GetSection($"OpenAPI:ConvertSettings:{style}")
I'm not saying we should change that part of the logic.
You can perfectly bind the object once with the "global" entry of the configuration, and rebind it with the "styled" entry of the configuration to override some of the settings as needed and without having to implement that manually.

2022-10-18 14:34 UTC, millicentachieng commented on OpenAPIService/OpenApiService.cs
> +                var convertSettingsForStyle = _configuration.GetSection($"OpenAPI:ConvertSettings:{style}")
I see. Thanks @baywet 😀

2022-10-18 16:07 UTC, baywet requested changes

2022-10-18 16:07 UTC, baywet commented on OpenAPIService/OpenApiService.cs
> +                AddSingleQuotesForStringParameters = true,
I'd advocate to even have the baseline to the configuration file so we can change the settings without having to redeploy the code. And bind twice

2022-10-19 11:43 UTC, baywet approved these changes

2022-10-27 16:08 UTC, merged