Adds requestBodies and other missing fields to the components object.
microsoftgraph/microsoft-graph-devx-api pull request #1162
Opened 2022-08-30 21:11 UTC by peombwa

## Overview

This PR fixes #1160 by:
- Ensuring we copy references of all `Components` object fields to the sliced OpenAPI document. See https://swagger.io/specification/#components-object.
- Updates unit tests to reflect the change above.

2022-08-31 10:12 UTC, MaggieKimani1 approved these changes

2022-08-31 12:10 UTC, baywet requested changes

2022-08-31 12:10 UTC, baywet commented on OpenAPIService/OpenApiService.cs
> +        }
```suggestion
        private static bool AddComponentsRequestBodies(OpenApiComponents newComponents, OpenApiComponents target)
        {
            var bodiesToAdd = newComponents.RequestBodies.Where(x => !target.RequestBodies.ContainsKey(x.Key));
            foreach (var item in bodiesToAdd)
            {
                target.RequestBodies.Add(item);
            }
            return bodiesToAdd.Any();
        }
```

2022-08-31 12:10 UTC, baywet commented on OpenAPIService/OpenApiService.cs
> +            moreStuff = AddComponentsRequestBodies(newComponents, target, moreStuff);
```suggestion
            moreStuff |= AddComponentsRequestBodies(newComponents, target);
```

2022-08-31 12:10 UTC, baywet commented on OpenAPIService/OpenApiService.cs
> +            moreStuff = AddComponentsRequestBodies(newComponents, target, moreStuff);
```suggestion
            moreStuff |= AddComponentsSchemas(newComponents, target, moreStuff);
            moreStuff |= AddComponentsParameters(newComponents, target, moreStuff);
            moreStuff |= AddComponentsResponses(newComponents, target, moreStuff);
            moreStuff |= AddComponentsRequestBodies(newComponents, target, moreStuff);
```

(I'm not sure resetting the more stuff switch after each method was what was desired)

2022-09-01 11:46 UTC, baywet commented on OpenAPIService/OpenApiService.cs
> +        }
ah you didn't like my Linq expression? 🤣

2022-09-01 11:46 UTC, baywet approved these changes

2022-09-01 12:39 UTC, merged