Feature: change open api gen process
microsoftgraph/microsoft-graph-devx-api pull request #1393
Opened 2023-02-28 07:54 UTC by thewahome

## Overview

Closes #1392 
Uses the yaml files in the metadata API to return pre-generated open api documents that have already been converted using the conversion settings

2023-02-28 12:58 UTC, baywet submitted a review, later dismissed
My only concern is if somebody else than us has taken a dependency on the API /enum values as changing those will break them. Trusting this will at least be coordinated with GE if there are direct dependencies. Otherwise we might want to consider a compatibility mapping.

CC @estruyf if you still have a dependency on devx api for your extensions

2023-02-28 13:08 UTC, estruyf commented
@baywet indeed, it is used in the following extension: https://marketplace.visualstudio.com/items?itemName=eliostruyf.vscode-msgraph-autocomplete - one of your colleagues is working on this extension to allow snippets to work as well.

2023-02-28 13:11 UTC, thewahome commented
Aah makes sense @baywet ... I will just make a dictionary to map the enum values to the file names ..

2023-02-28 13:13 UTC, baywet commented
Thanks for reverting that fast @estruyf It seems the extension is relying on a static zip file instead of calling out to the devx API, did I get this right? https://github.com/estruyf/vscode-msgraph-autocomplete/blob/main/apis.json.gz

2023-02-28 13:17 UTC, estruyf commented
@baywet yes, that is the cached version of the API, so that it doesn't always have to call the API, but if it doesn't find it, or there is a new endpoint, it will still call the API.

https://github.com/estruyf/vscode-msgraph-autocomplete/blob/ced76a29162db1f1089f009db3cec95f98c4f8ae/src/utils/AutoComplete.ts#L4

2023-02-28 13:18 UTC, baywet commented
Ah great, you're not making use of the style parameter and anyway we're going to be reverting the changes to the API surface. Thanks again for all that input!

2023-02-28 15:28 UTC, baywet requested changes

2023-02-28 15:28 UTC, baywet commented on OpenAPIService/OpenApiService.cs
> +        Dictionary<OpenApiStyle, string> fileNames = new Dictionary<OpenApiStyle, string>();
```suggestion
        private static readonly Dictionary<OpenApiStyle, string> fileNames = new Dictionary<OpenApiStyle, string>() {
            { OpenApiStyle.GEAutocomplete, "graphexplorer"},
            { OpenApiStyle.Plain, "openapi"},
            { OpenApiStyle.PowerShell, "powershell"},
            { OpenApiStyle.PowerPlatform, "openapi"},
         };
```

2023-02-28 15:28 UTC, baywet commented on OpenAPIService/OpenApiService.cs
> +            fileNames.Add(OpenApiStyle.PowerPlatform, "openapi");
```suggestion
```

2023-02-28 16:05 UTC, baywet submitted a review, later dismissed

2023-03-01 13:11 UTC, andrueastman approved these changes

2023-03-01 13:28 UTC, merged