Support processing of permission file in new format
microsoftgraph/microsoft-graph-devx-api pull request #1402
Opened 2023-03-03 16:30 UTC by millicentachieng

## Overview

Fixes #1261, #1253, #1318, #1337, #1338, #1355, 
This PR
- Updates DevX API to use permissions file in new format
- Updates permissions endpoint to add support for returning permissions for all scope types for a given endpoint
- Updates DevX API to return scope types in the permissions response object
- Updates DevX API to return a payload indicating which permission has the least privilege
- Updates permissions endpoint to add support for filtering out hidden permissions
- Adds an endpoint that to return least privilege permissions given a set of URLs

2023-03-06 13:15 UTC, baywet requested changes

2023-03-06 13:15 UTC, baywet commented on GraphWebApi/wwwroot/OpenApi.yaml
> +        "207":
207 is a webdav status code. Why do we need both the scopes and the errors at the same time? shouldn't it be one or the other?

2023-03-06 13:15 UTC, baywet commented on PermissionsService/Interfaces/IPermissionStore.cs
> +        Task<PermissionResult> GetScopesForMultipleResourcesAsync(List<string> requestUrls = null,
instead of introducing a new method, since we own both the interface and the implementation, why don't we evolve the existing one?

2023-03-06 13:15 UTC, baywet commented on PermissionsService/Models/PathPermissions.cs
> +        public string Url
```suggestion
        public required string Url
```

(this way you can get rid of the constructor)

2023-03-06 13:15 UTC, baywet commented on PermissionsService/Models/PathSet.cs
> +    internal class PathsLeastPrivilegeSchemeKeyConverter : JsonConverter<Dictionary<string, List<ScopeType>>>
why do we need custom converters, couldn't we adapt our models to avoid needing them?

2023-03-06 13:15 UTC, baywet commented on PermissionsService/Services/PermissionsStore.cs
> +                .Where(x => x.Value.ProvisioningInfo.IsHidden).Select(x => x.Key).ToHashSet();
```suggestion
                .Where(static x => x.Value.ProvisioningInfo.IsHidden).Select(static x => x.Key).ToHashSet(StringComparer.OrdinalIgnoreCase);
```

2023-03-06 13:15 UTC, baywet commented on PermissionsService/Services/PermissionsStore.cs
> +            var scopesInformationDictionary = (!string.IsNullOrEmpty(org) && !string.IsNullOrEmpty(branchName))
```suggestion
            var scopesInformationDictionary = !(string.IsNullOrEmpty(org) || string.IsNullOrEmpty(branchName))
```

2023-03-06 13:15 UTC, baywet commented on PermissionsService/Services/PermissionsStore.cs
> +                .SelectMany(x => x)
```suggestion
                .SelectMany(static x => x.SupportedMethodPermissions.Values)
                .SelectMany(static x => x)
```

2023-03-06 13:15 UTC, baywet commented on PermissionsService/Services/PermissionsStore.cs
> +                .SelectMany(x => x.Value.AllPermissions, (x, permission) => new ScopeInformation
```suggestion
                .SelectMany(static x => x.Value.AllPermissions, static (x, permission) => new ScopeInformation
```

2023-03-07 11:37 UTC, millicentachieng commented on GraphWebApi/wwwroot/OpenApi.yaml
> +        "207":
Noted. I've updated the status code to 400. We need to let the client know that there were some URLs that did not yield  any scopes and they can proceed with the result if they choose to.

2023-03-07 11:37 UTC, millicentachieng commented on PermissionsService/Interfaces/IPermissionStore.cs
> +        Task<PermissionResult> GetScopesForMultipleResourcesAsync(List<string> requestUrls = null,
Done. I've merged the two methods.

2023-03-07 11:37 UTC, millicentachieng commented on PermissionsService/Models/PathSet.cs
> +    internal class PathsLeastPrivilegeSchemeKeyConverter : JsonConverter<Dictionary<string, List<ScopeType>>>
I've removed the custom converters.

2023-03-07 14:34 UTC, baywet requested changes

2023-03-07 14:34 UTC, baywet commented on GraphWebApi/wwwroot/OpenApi.yaml
> +          type: string
this could use an enum type instead

2023-03-07 14:34 UTC, baywet commented on GraphWebApi/wwwroot/OpenApi.yaml
> +              - Application
why not move this definition to the schema + parameters components and refer to it here instead to enable reusability?

2023-03-07 14:34 UTC, baywet commented on GraphWebApi/wwwroot/OpenApi.yaml
> +          default: true
parameters components for all of them so they can be reused between the get and post operations

2023-03-07 14:34 UTC, baywet commented on PermissionsService/Models/PathPermissions.cs
> +        } = new();
```suggestion
        } = new(StringComparer.OrdinalIgnoreCase);
```

2023-03-07 14:34 UTC, baywet commented on PermissionsService/Models/PathPermissions.cs
> +        } = new();
```suggestion
        } = new(StringComparer.OrdinalIgnoreCase);
```

2023-03-07 14:34 UTC, baywet commented on PermissionsService/Models/PathSet.cs
> +        } = new();
```suggestion
        } = new(StringComparer.OrdinalIgnoreCase);
```

2023-03-07 14:34 UTC, baywet commented on PermissionsService/Models/PathSet.cs
> +        public List<string> ExcludedProperties
any specific reason why we're using a list and not a hashset for those two?

2023-03-07 14:34 UTC, baywet commented on PermissionsService/Models/PermissionResult.cs
> +        }
```suggestion
        } = new();
```

2023-03-07 14:34 UTC, baywet commented on PermissionsService/Models/PermissionResult.cs
> +        }
```suggestion
        } = new();
```

2023-03-07 14:34 UTC, baywet commented on PermissionsService/Models/PermissionResult.cs
> +        }
```suggestion
        } = string.Empty;
```

2023-03-07 14:34 UTC, baywet commented on PermissionsService/Models/PermissionResult.cs
> +        }
```suggestion
        } = string.Empty;
```

Should we decide to enable NRT for this project, we won't have to revisit this class this way

2023-03-07 14:34 UTC, baywet commented on PermissionsService/Services/PermissionsStore.cs
> +            }
set default values?

2023-03-07 14:34 UTC, baywet commented on PermissionsService/Services/PermissionsStore.cs
> +                        permissionsData = LoadPermissionsDataAsync().Result;
instead of using a lock and blocking everyone, use [GetOrCreateAsync](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.caching.memory.cacheextensions.getorcreateasync?view=dotnet-plat-ext-7.0) and change the property type to be a Task<PermissionsDataInfo> so everyone can await, which will be deferred in most cases and avoid blocking everything, everywhere.

2023-03-07 18:13 UTC, millicentachieng commented on PermissionsService/Models/PathSet.cs
> +        public List<string> ExcludedProperties
Updating to HashSet

2023-03-07 18:37 UTC, irvinesunday commented on PermissionsService/Models/ScopeType.cs
> +﻿using System;
Remove unnecessary usings

2023-03-07 18:37 UTC, irvinesunday commented on PermissionsService/Models/ScopeType.cs
> +﻿using System;
Add license info.

2023-03-07 18:38 UTC, irvinesunday commented on PermissionsService/Models/ScopeType.cs
> +    public enum ScopeType
Include public XML summary

2023-03-07 18:40 UTC, irvinesunday commented on GraphWebApi/Controllers/PermissionsController.cs
> +                return BadRequest("The HTTP method value cannot be null or empty.");
Exception message does not indicate whether the `requestUrl` could be null or empty

2023-03-07 18:54 UTC, irvinesunday commented on GraphWebApi/Controllers/PermissionsController.cs
> +            if (!string.IsNullOrEmpty(requestUrl) && string.IsNullOrEmpty(method))
What if the `requestUrl` is empty? Do we want to throw an error?

2023-03-07 18:54 UTC, irvinesunday commented on GraphWebApi/Controllers/PermissionsController.cs
> +        public async Task<IActionResult> GetPermissionScopes([FromBody] List<string> requestUrls,
Check against nullability of `requestUrls`.

2023-03-07 18:55 UTC, irvinesunday commented on GraphWebApi/Controllers/PermissionsController.cs
> +                                                             [FromQuery] ScopeType? scopeType = null,
Same as above, check for nullability.

2023-03-07 19:03 UTC, irvinesunday commented on PermissionsService/Services/PermissionsStore.cs
> +                using var client = new HttpClient();
Or use the already declared http client private field.
```CSharp 
private readonly IHttpClientUtility _httpClientUtility;
```

2023-03-07 19:10 UTC, millicentachieng commented on GraphWebApi/Controllers/PermissionsController.cs
> +            if (!string.IsNullOrEmpty(requestUrl) && string.IsNullOrEmpty(method))
If `requestUrl` is null or empty then we return all permissions. We won't need to throw an error.

2023-03-07 19:16 UTC, millicentachieng commented on GraphWebApi/Controllers/PermissionsController.cs
> +        public async Task<IActionResult> GetPermissionScopes([FromQuery]ScopeType? scopeType = null,
We want it to be nullable so that if `scopeType` is not specified then we return all scope types.

2023-03-07 19:17 UTC, irvinesunday commented on PermissionsService/Services/PermissionsStore.cs
> +            if (!requestUrls.Any())
`requestUrls` could be be null here.

2023-03-07 19:24 UTC, irvinesunday commented on PermissionsService/Services/PermissionsStore.cs
> +            if (string.IsNullOrEmpty(requestUrl))
Consider moving this check to the calling method and check whether the `IEnumerable` of `requestUrls` is null.

2023-03-07 21:51 UTC, millicentachieng commented on PermissionsService/Services/PermissionsStore.cs
> +                foreach (var url in requestUrls)
The thrown exception is handled within the catch block and execution continues to the next URL. And what are the benefits of using a select statement instead?

2023-03-07 22:21 UTC, zengin requested changes

2023-03-07 22:21 UTC, zengin commented on PermissionsService/Services/PermissionsStore.cs
> +        private async Task<PermissionsDataInfo> LoadPermissionsDataAsync()
I think we should run this conversion once at the time of permission file deployment and generate the reverse lookup data structure on file.

DevX API should simply load that reverse lookup file as a data structure and run lookup logic per request.

Current architecture has a very long latency for the initial request which can be avoided.

2023-03-08 07:37 UTC, irvinesunday commented on GraphWebApi/Controllers/PermissionsController.cs
> +                                                             [FromQuery] ScopeType? scopeType = null,
Resolving this as it has been explained above.

2023-03-08 14:16 UTC, baywet commented on PermissionsService/Services/PermissionsStore.cs
> +                using var client = new HttpClient();
@irvinesunday is there a specific reason why we rolled out our "own version" of the http client factory?

2023-03-08 14:23 UTC, baywet commented on PermissionsService/Services/PermissionsStore.cs
> +                foreach (var url in requestUrls)
I might be missing some of the UX context here. My assumption was that as an application developer, I want to see all the permissions I might need for my application to run. If there's is a failure, instead of getting only the ones that didn't fail until the first failure, wouldn't it be better to get all the ones that didn't fail at least?

2023-03-08 14:42 UTC, millicentachieng commented on PermissionsService/Services/PermissionsStore.cs
> +            foreach (var permission in permissionsDocument.Permissions)
For performance improvement, we will implement this [idea](https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/1402#discussion_r1128667816) from @zengin.

2023-03-09 13:21 UTC, millicentachieng commented on PermissionsService/Services/PermissionsStore.cs
> +        private async Task<PermissionsDataInfo> LoadPermissionsDataAsync()
Here's the link to the reverse lookup file I'll be using 
https://raw.githubusercontent.com/microsoftgraph/microsoft-graph-devx-content/task/ma/add-reverse-lookup-permission-file/permissions/permissions-all.json

2023-03-09 13:44 UTC, millicentachieng commented on PermissionsService/Services/PermissionsStore.cs
> +                foreach (var url in requestUrls)
Here's a snippet of more of the code
```csharp
foreach (var url in requestUrls)
{
    try
    {
        if (string.IsNullOrEmpty(url))
            throw new InvalidOperationException("The request URL cannot be null or empty.");

        var scopesForUrl = GetScopesForRequestUrl(requestUrl: url,
                                                scopeType: scopeType,
                                                includeHidden: includeHidden,
                                                leastPrivilegeOnly: leastPrivilegeOnly);

        if (scopesForUrl == null)
            throw new InvalidOperationException($"Permissions information for {url} were not found.");

        scopesInfo.AddRange(scopesForUrl);
    }
    catch (Exception exception)
    {
        errors.Add(new PermissionError()
        {
            Url = url,
            Message = exception.Message
        });
    }
}
```
If there's an exception while fetching scopes for any of the Urls, it's caught, added to the errors list and we move on to process the next Url.

2023-03-10 11:11 UTC, millicentachieng commented on PermissionsService/Services/PermissionsStore.cs
> +        private async Task<PermissionsDataInfo> LoadPermissionsDataAsync()
Updated to use reverse lookup file

2023-03-10 13:55 UTC, baywet commented on PermissionsService/Services/PermissionsStore.cs
> +                foreach (var url in requestUrls)
thanks for clarifying/updating.

2023-03-10 13:59 UTC, baywet requested changes
Thanks for making the changes, two minor things on my side

2023-03-10 13:59 UTC, baywet commented on PermissionsService/Services/PermissionsStore.cs
> +            var scopesInfo = GetAdditionalScopesInformation(scopesInformationDictionary, scopes.DistinctBy(x => new { x.ScopeName, x.ScopeType }));
```suggestion
            var scopesInfo = GetAdditionalScopesInformation(scopesInformationDictionary, scopes.DistinctBy(x => $"{x.ScopeName}{x.ScopeType}", StringComparison.OrdinalIgnoreCase));
```

Otherwise you're doing reference comparisons on anonymous objects which will always be different

2023-03-10 13:59 UTC, baywet commented on GraphWebApi/Controllers/PermissionsController.cs
> +            return result == null || !result.Results.Any() ? NotFound() : Ok(result.Results);
why is there a difference in returning status based on the result and presence of errors or not between the two methods?

2023-03-10 17:30 UTC, baywet commented on PermissionsService/Services/PermissionsStore.cs
> +            var scopesInfo = GetAdditionalScopesInformation(scopesInformationDictionary, scopes.DistinctBy(x => new { x.ScopeName, x.ScopeType }));
right, this ends up calling [Object.Equals()](https://learn.microsoft.com/en-us/dotnet/api/system.object.equals?view=net-7.0) which can have a bunch of size effects and relies on reflection (bad perf) which recursively does reference comparisons on the object structure.
Whereas a string is deterministic and will provide better perf

2023-03-10 19:59 UTC, millicentachieng commented on GraphWebApi/Controllers/PermissionsController.cs
> +            return result == null || !result.Results.Any() ? NotFound() : Ok(result.Results);
Implemented the above

2023-03-13 14:01 UTC, baywet submitted a review, later dismissed
Thanks for making the changes

2023-03-13 22:49 UTC, zengin approved these changes

2023-03-13 22:49 UTC, zengin commented on PermissionsService.Test/PermissionsService.Test.csproj
> +      <Content Include="TestFiles\permissions-test-file.json">
nit: you can use wildcards to copy files, e.g. `TestFiles\*`

2023-03-13 22:49 UTC, zengin commented on PermissionsService/Interfaces/IPermissionStore.cs
> +        Task<PermissionResult> GetScopesAsync(List<string> requestUrls = null,
I think requestUrls should not be optional.

2023-03-14 07:47 UTC, millicentachieng commented on PermissionsService/Interfaces/IPermissionStore.cs
> +        Task<PermissionResult> GetScopesAsync(List<string> requestUrls = null,
We want to fetch all permissions when requestUrls is null

2023-03-14 08:02 UTC, millicentachieng commented on PermissionsService.Test/PermissionsService.Test.csproj
> +      <Content Include="TestFiles\permissions-test-file.json">
Updated

2023-03-14 13:41 UTC, baywet approved these changes

2023-03-17 13:01 UTC, baywet requested changes

2023-03-17 14:44 UTC, millicentachieng commented on PermissionsService/Services/PermissionsStore.cs
> +                .Select(x => x.ToString().Contains(Delegated, StringComparison.InvariantCultureIgnoreCase) ? Delegated : Application)
The descriptions list is grouped into two lists: "Delegated" and "Application". We are comparing an enum and a string that do not exactly match.

2023-03-17 14:49 UTC, baywet commented on PermissionsService/Services/PermissionsStore.cs
> +                .Select(x => x.ToString().Contains(Delegated, StringComparison.InvariantCultureIgnoreCase) ? Delegated : Application)
So you're mapping two values to two other values? A dictionary would be much faster at doing that.

2023-03-17 18:22 UTC, baywet commented on PermissionsService/Services/PermissionsStore.cs
> +                .Select(x => x.ToString().Contains(Delegated, StringComparison.InvariantCultureIgnoreCase) ? Delegated : Application)
or more accurately 3 enum values to 2 strings. so a Dictionary<ScopeType, string> with the 3 entries as a static readonly field shuold do the trick

2023-03-27 11:38 UTC, baywet approved these changes

2023-03-27 11:38 UTC, baywet commented on PermissionsService/Services/PermissionsStore.cs
> +        private Task<PermissionsDataInfo> PermissionsData =>
could you log an issue about multiple threads potentially populating the value concurrently and the impact on the initial request. And the suggested solution to load the cache on app startup instead + have something else re-populate it on a schedule.

2023-03-28 16:32 UTC, millicentachieng commented on PermissionsService/Services/PermissionsStore.cs
> +        private Task<PermissionsDataInfo> PermissionsData =>
https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1456

2023-03-28 16:36 UTC, baywet requested changes

2023-03-28 16:36 UTC, baywet commented on PermissionsService/Services/PermissionsStore.cs
> +                if (scopeInfo != null)
```suggestion
                if (scopesInformationDictionary[schemeKey].TryGetValue(scope.ScopeName, out var scopeInfo))
```

2023-03-28 20:14 UTC, merged