adds go import statements
microsoftgraph/microsoft-graph-devx-api pull request #1448
Opened 2023-03-22 14:14 UTC by rkodev

1. Adds import statements to go generated snippets.
2. Fixes Me path objects after shim me.

Updated snippet has all necessary imports and resolves wrong imports for shim me path

Resolves https://github.com/microsoftgraph/msgraph-sdk-go/issues/442
Resolves https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/920

```go
//THE GO SDK IS IN PREVIEW. NON-PRODUCTION USE ONLY
import (
	  "context"
	  msgraphsdk "github.com/microsoftgraph/msgraph-sdk-go"
	  graphconfig "github.com/microsoftgraph/msgraph-sdk-go/users"
	  //other-imports
)

graphClient := msgraphsdk.NewGraphServiceClientWithCredentials(cred, scopes)

requestParameters := &graphconfig.ItemMessagesRequestBuilderGetQueryParameters{
	Select: [] string {"sender","subject"},
}
configuration := &graphconfig.ItemMessagesRequestBuilderGetRequestConfiguration{
	QueryParameters: requestParameters,
}

result, err := graphClient.Me().Messages().Get(context.Background(), configuration)

```

2023-03-22 14:42 UTC, baywet requested changes
Thanks for starting this, a couple of comments.

2023-03-22 14:42 UTC, baywet commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/GoGenerator.cs
> +                var inchildren = property.Children.Select(x => x.PropertyType == propertyType).Where(x => true).FirstOrDefault();
same where comment

2023-03-22 14:42 UTC, baywet commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/GoGenerator.cs
> +                            w = w.Equals("Me") ? "Item" : w;
```suggestion
                            w = w.Equals("Me", StringComparison.Ordinal) ? "Item" : w;
```

2023-03-22 15:02 UTC, baywet submitted a review, later dismissed
Thanks for making the changes!

2023-03-23 07:38 UTC, andrueastman approved these changes

2023-03-23 07:38 UTC, merged