Update python snippet generation logic
microsoftgraph/microsoft-graph-devx-api pull request #1450
Opened 2023-03-23 13:12 UTC by shemogumbe

## Overview
Add snippet Generation for Kiota based Python SDK

Brief description of what this PR does, and why it is needed.

### Demo
Optional. Screenshots, `curl` examples, etc.

### Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Testing Instructions

* How to test this PR
* Prefer bulleted description
* Start after checking out this branch
* Include any setup required, such as bundling scripts, restarting services, etc.
* Include test case, and expected output

2023-04-13 10:47 UTC, rkodev requested changes

2023-04-13 10:47 UTC, rkodev commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/PythonGenerator.cs
> +        */
minor: this might have been left by mistake

2023-04-13 10:47 UTC, rkodev commented on CodeSnippetsReflection/StringExtensions/StringExtensions.cs
> +                        snakeCaseString += "_";
We can use stringbuilder here

2023-04-13 10:47 UTC, rkodev commented on CodeSnippetsReflection.OpenAPI.Test/PythonGeneratorTests.cs
> +        //     )", result);
Another comment probably can be removed

2023-04-13 12:56 UTC, andrueastman commented on CodeSnippetsReflection/StringExtensions/StringExtensions.cs
> +                        snakeCaseString += "_";
We can also pull this https://github.com/microsoft/kiota/blob/2bbc155bff2a9539e6f5513d0830395a58cb280d/src/Kiota.Builder/Extensions/StringExtensions.cs#L57

2023-04-13 12:56 UTC, andrueastman commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/PythonGenerator.cs
> +            if (codeGraph.HasParameters() || codeGraph.HasParameters()){
Did you mean this?
```suggestion
            if (codeGraph.HasParameters() || codeGraph.HasHeaders()){
```

2023-04-13 12:56 UTC, andrueastman commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/PythonGenerator.cs
> +            .ToList();
unused variables
```suggestion
```

2023-04-13 12:56 UTC, andrueastman commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/PythonGenerator.cs
> +        indentManager.Unindent();
Just to confirm, do we need to unindent twice? Only one Indent it called above.

2023-04-13 12:56 UTC, andrueastman commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/PythonGenerator.cs
> +    private const string RequestHeadersVarName = "headers";
unused vars
```suggestion
    private const string RequestConfigurationVarName = "request_configuration";
```

2023-04-25 08:56 UTC, shemogumbe commented on CodeSnippetsReflection/StringExtensions/StringExtensions.cs
> +                        snakeCaseString += "_";
Considering these builders are on Kiota, and we have some in devx, does this imply we need to cease using the ones on devx, can they both exist, in which case it is healthy to keep this?

2023-04-25 10:38 UTC, andrueastman commented on CodeSnippetsReflection/StringExtensions/StringExtensions.cs
> +                        snakeCaseString += "_";
Apologies for any confusion caused, I was providing a pointer to an alternative/suggested implementation. 
I'm okay to resolve this with the latest changes.

2023-04-25 10:39 UTC, andrueastman approved these changes

2023-04-26 12:13 UTC, samwelkanda requested changes
Thanks for this! A few modifications needed due to recent breaking changes.

2023-04-26 12:13 UTC, samwelkanda commented on CodeSnippetsReflection.OpenAPI.Test/PythonGeneratorTests.cs
> +        Assert.Contains(".directory.deletedItems.graphgroup.get()", result);
`.directory.deleted_items.graph_group.get()`

2023-04-26 12:13 UTC, samwelkanda commented on CodeSnippetsReflection.OpenAPI.Test/PythonGeneratorTests.cs
> +            ".me.messages_by_id('message-id').get(request_configuration = request_configuration)",
`.me.messages.by_message_id('message-id').get(request_configuration = request_configuration)`

2023-04-26 12:13 UTC, samwelkanda commented on CodeSnippetsReflection.OpenAPI.Test/PythonGeneratorTests.cs
> +        Assert.Contains(".me.messages_by_id('message-id').delete()", result);
`.me.messages.by_message_id('message-id').delete()`

2023-04-26 12:13 UTC, samwelkanda commented on CodeSnippetsReflection.OpenAPI.Test/PythonGeneratorTests.cs
> +        Assert.Contains("request_body.additionaldata(additionalData)", result);
`request_body.additional_data(additionalData)`

2023-04-26 12:13 UTC, samwelkanda commented on CodeSnippetsReflection.OpenAPI.Test/PythonGeneratorTests.cs
> +        Assert.Contains("= new DirectoryObject();", result);
`= DirectoryObject()` Remove the new and ;

2023-05-10 10:50 UTC, samwelkanda approved these changes

2023-05-17 14:19 UTC, rkodev approved these changes

2023-05-22 16:00 UTC, merged