Fix date time offset in URL path segments
microsoftgraph/microsoft-graph-devx-api pull request #1509
Opened 2023-04-18 08:52 UTC by andrueastman

This PR closes https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/612

Type information is needed to correctly infer types used in URL path parameters for functions. This PR therefore adds a collection of CodeProperty instances to the snippetCode graph with the type information so that this may be taken advantage of during snippet generation.

Tests have been added to validate this.

2023-04-20 12:04 UTC, baywet requested changes

2023-04-20 12:04 UTC, baywet commented on CodeSnippetsReflection.OpenAPI/ModelGraph/SnippetCodeGraph.cs
> +                .Value?.Parameters.Where(param => param.In == ParameterLocation.Path) ?? new List<OpenApiParameter>();
```suggestion
                .Value?.Parameters.Where(static param => param.In == ParameterLocation.Path) ?? new List<OpenApiParameter>();
```

2023-04-20 12:04 UTC, baywet commented on CodeSnippetsReflection.OpenAPI/ModelGraph/SnippetCodeGraph.cs
> +            var parameters = new List<CodeProperty>();
could we write that as a select on the path parameters to avoid multiple growth of the list/enable vectorialization?

2023-04-20 12:04 UTC, baywet commented on CodeSnippetsReflection.OpenAPI/ModelGraph/SnippetCodeGraph.cs
> +                switch (parameter.Schema.Type)
```suggestion
                switch (parameter.Schema.Type.ToLowerCaseInvariant())
```

2023-04-20 12:04 UTC, baywet commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/CSharpGenerator.cs
> +                                            foreach (var codeProperty in snippetCodeGraph.PathParameters.OrderBy(static parameter => parameter.Name))
```suggestion
                                            foreach (var codeProperty in snippetCodeGraph.PathParameters.OrderBy(static parameter => parameter.Name, StringComparer.OrdinalIgnoreCase))
```

2023-04-24 06:29 UTC, andrueastman commented on CodeSnippetsReflection.OpenAPI/ModelGraph/SnippetCodeGraph.cs
> +            var parameters = new List<CodeProperty>();
Resolved in latest update

2023-04-24 11:37 UTC, baywet approved these changes

2023-04-24 11:37 UTC, merged