Fix importing nested model files
microsoftgraph/microsoft-graph-devx-api pull request #1548
Opened 2023-05-11 10:57 UTC by rkodev

## Overview

Fixes import statements for go imports in nested builder folders

### Demo

E.g  creating worklow  https://learn.microsoft.com/en-us/graph/api/identitygovernance-lifecycleworkflowscontainer-post-workflows?view=graph-rest-beta&tabs=go

Current 

```go

```
import (
	  "context"
	  msgraphsdk "github.com/microsoftgraph/msgraph-beta-sdk-go"
	  graphmodels "github.com/microsoftgraph/msgraph-beta-sdk-go/models//identityGovernance"
	  //other-imports
)

Fix

```go

import (
	  "context"
	  abstractions "github.com/microsoft/kiota-abstractions-go"
	  msgraphsdk "github.com/microsoftgraph/msgraph-beta-sdk-go"
	  graphidentitygovernance "github.com/microsoftgraph/msgraph-beta-sdk-go/identitygovernance"
	  //other-imports
)
```

## Testing Instructions

Added unit tests

2023-05-14 20:05 UTC, baywet requested changes

2023-05-14 20:05 UTC, baywet commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/GoGenerator.cs
> +                var path = codeGraph.Body.NamespaceName.Replace("microsoft.graph", "").Replace(".", "/").Replace("//","/").ToLower().Split("/").FirstOrDefault();
To lower invariant

2023-05-14 20:05 UTC, baywet commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/GoGenerator.cs
> +            return codeGraph.GetReferencedNamespaces(true).Select(x => evaluateNameSpaceName(x));
```suggestion
            return codeGraph.GetReferencedNamespaces(true).Select(evaluateNameSpaceName);
```

2023-05-14 20:05 UTC, baywet commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/GoGenerator.cs
> +            return nameSpace.Split(".").FirstOrDefault().ToLower().Replace(".microsoft.graph", "");
To lower invariant

2023-05-14 20:05 UTC, baywet commented on CodeSnippetsReflection.OpenAPI/ModelGraph/SnippetCodeGraph.cs
> +            HashSet<String> result = new HashSet<string>();
Does casing matter here?

2023-05-14 20:05 UTC, baywet commented on CodeSnippetsReflection.OpenAPI/ModelGraph/SnippetCodeGraph.cs
> +                        var nameSpaceName = shimmedMePackage ? x.NamespaceName.Split(".").Select(x => x.Equals("Me", StringComparison.OrdinalIgnoreCase) ? "Users" : x).Aggregate((current, next) => cu
String split option remove empty

2023-05-15 13:44 UTC, baywet commented on CodeSnippetsReflection.OpenAPI/ModelGraph/SnippetCodeGraph.cs
> +                        var nameSpaceName = shimmedMePackage ? x.NamespaceName.Split(".").Where(x => !string.IsNullOrEmpty(x)).Select(x => x.Equals("Me", StringComparison.OrdinalIgnoreCase) ? "Users"
this is what I meant here https://learn.microsoft.com/en-us/dotnet/api/system.string.split?view=net-8.0#system-string-split(system-char-system-stringsplitoptions)

2023-05-16 16:13 UTC, baywet submitted a review, later dismissed
approving to avoid blocking this PR while I'm gone but I haven't had time to review the latest changes. Please have somebody else review it

2023-05-17 08:16 UTC, andrueastman commented on CodeSnippetsReflection.OpenAPI/ModelGraph/SnippetCodeGraph.cs
> +            HashSet<String> result = new HashSet<string>();
If it doesn't, you can prevent potential duplicate entries due to different casing

```cs
HashSet<String> result = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
```

2023-05-22 09:58 UTC, andrueastman approved these changes

2023-05-22 10:04 UTC, merged