Tie wiql to class instance
microsoftgraph/microsoft-graph-devx-api pull request #1609
Opened 2023-06-20 10:09 UTC by Onokaev

## Overview
Fixes #1608 

### Demo

Optional. Screenshots, `curl` examples, etc.

### Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Testing Instructions

* How to test this PR
* Prefer bulleted description
* Start after checking out this branch
* Include any setup required, such as bundling scripts, restarting services, etc.
* Include test case, and expected output

2023-06-20 13:11 UTC, baywet requested changes

2023-06-20 13:11 UTC, baywet commented on KnownIssuesService/Services/KnownIssuesService.cs
> +            if (this.IssuesEnvironment.ToLower() == EnvironmentType.Production.ToLower() || this.IssuesEnvironment.ToLower() == EnvironmentType.Preview.ToLower())
use a string comparison instead of normalizing to lower

2023-06-20 13:11 UTC, baywet commented on KnownIssuesService/Services/KnownIssuesService.cs
> +			int[] ids = result?.WorkItems.Select(item => item.Id).ToArray();
```suggestion
			int[] ids = result?.WorkItems.Select(static item => item.Id).ToArray();
```

2023-06-20 19:34 UTC, baywet requested changes

2023-06-20 19:34 UTC, baywet commented on KnownIssuesService/Services/KnownIssuesService.cs
> +            if (environment == EnvironmentType.Production || environment == EnvironmentType.Preview)
```suggestion
            if (EnvironmentType.Production.Equals(environment, StringComparison.OrdinalIgnoreCase) || EnvironmentType.Preview.Equals(environment, StringComparison.OrdinalIgnoreCase))
```

2023-06-21 06:22 UTC, andrueastman approved these changes

2023-06-21 12:34 UTC, baywet approved these changes
thanks for making the changes

2023-06-21 12:35 UTC, merged