Bump PowerShell Snippet Generator to V2 GA
microsoftgraph/microsoft-graph-devx-api pull request #1650
Opened 2023-06-29 08:48 UTC by timayabi2020

## Overview
Update the PowerShell snippet generator to V2 GA.
See [release notes](https://github.com/microsoftgraph/msgraph-sdk-powershell/releases) for full v1 to v2 change log and new [changes ](https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/features/2.0/docs/upgrade-to-v2.md) in v2.

2023-06-29 20:41 UTC, peombwa commented on CodeSnippetsReflection.OpenAPI.Test/PowerShellGeneratorTests.cs
> +        }
Can we add unit tests for beta APIs as well.

2023-06-29 23:44 UTC, peombwa commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/PowerShellGenerator.cs
> +            var hasGraphPrefix = snippetModel.EndPathNode.Path.Contains("graph", StringComparison.OrdinalIgnoreCase);
You should be able to use `cleanPath` here. It is extracted from `snippetModel.EndPathNode.Path`.
```suggestion
            var hasGraphPrefix = cleanPath.Contains("graph", StringComparison.OrdinalIgnoreCase);
```

2023-06-30 00:00 UTC, peombwa commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/PowerShellGenerator.cs
> +                }
@timayabi2020, do you have an example where this used? AFIK, deltaTokens are set as query parameters and are currently not exposed in the OpenAPI document - https://github.com/microsoftgraph/msgraph-metadata/issues/354.

2023-06-30 00:13 UTC, peombwa requested changes

2023-06-30 00:13 UTC, peombwa commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/PowerShellGenerator.cs
> +                }
never mind, I've found it - https://learn.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0&tabs=http#example-2-last-page-in-a-set. However, this block should live in `GetCommandParameters` method:
https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/082a2e80a76c6b72fb3079d3de3a1bbced136fc1/CodeSnippetsReflection.OpenAPI/LanguageGenerators/PowerShellGenerator.cs#L114-L133

2023-06-30 11:42 UTC, andrueastman commented on CodeSnippetsReflection.OpenAPI.Test/PowerShellGeneratorTests.cs
> +            using var requestPayload = new HttpRequestMessage(HttpMethod.Get, $"{ServiceRootUrl}/places/graph.room");
When the snippet generator runs, the input will come as `https://graph.microsoft.com/v1.0/places/microsoft.graph.room`
Any chance we can add a test to validate the alternative path as well?
https://learn.microsoft.com/en-us/graph/api/place-list?view=graph-rest-1.0&tabs=http#request

2023-06-30 11:42 UTC, andrueastman commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/PowerShellGenerator.cs
> +            if (deltaWithParams.IsMatch(lastPathSegment))
I suspect this may be too specific and will mean adding more if clauses as more are discovered. As other functions exist in the graph surface that may need parameters extracted. E.g.
https://learn.microsoft.com/en-us/graph/api/reports-getuserarchivedprintjobs?view=graph-rest-1.0&tabs=http

We should probably extract the function name and the parameter values and use those to generate the function name and the parameter list.

2023-06-30 11:42 UTC, andrueastman commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/PowerShellGenerator.cs
> +            if (lastPathSegment.Contains("()"))
We can simply call or return `path.RemoveFunctionBraces()`

https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/8a926e024dcc9a12fc795a1b5b819694d7c85ad3/CodeSnippetsReflection.OpenAPI/StringExtensions.cs#L33C28-L33C48

2023-06-30 18:02 UTC, timayabi2020 commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/PowerShellGenerator.cs
> +        private const string mgCommandMetadataUrl = "https://raw.githubusercontent.com/microsoftgraph/msgraph-sdk-powershell/features/2.0/src/Authentication/Authentication/custom/common/MgCommandMeta
I have rolled back to the previous link because of this PR https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/2117

2023-06-30 18:02 UTC, timayabi2020 commented on CodeSnippetsReflection.OpenAPI.Test/PowerShellGeneratorTests.cs
> +            using var requestPayload = new HttpRequestMessage(HttpMethod.Get, $"{ServiceRootUrl}/places/graph.room");
This has been added

2023-06-30 18:03 UTC, timayabi2020 commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/PowerShellGenerator.cs
> +            if (deltaWithParams.IsMatch(lastPathSegment))
I have made the regex more generic to cover all scenarios related to overloaded bounded functions.

2023-06-30 19:15 UTC, peombwa commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/PowerShellGenerator.cs
> +        private const string mgCommandMetadataUrl = "https://raw.githubusercontent.com/microsoftgraph/msgraph-sdk-powershell/features/2.0/src/Authentication/Authentication/custom/common/MgCommandMeta
@timayabi2020, the tests will fail until https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/2117 is merged. Please review and merge the dependent PR.

2023-07-03 07:07 UTC, andrueastman submitted a review, later dismissed

2023-07-03 15:39 UTC, peombwa commented on CodeSnippetsReflection.OpenAPI.Test/PowerShellGeneratorTests.cs
> +            Assert.Contains("Get-MgCommunicationCallRecord", result);
Assert should use the beta cmdlet of the provided URL - https://learn.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstnblockeduserslog?view=graph-rest-beta&tabs=powershell#request.
```suggestion
            Assert.Contains("Get-MgBetaCommunicationCallRecordPstnBlockedUserLog", result);
```

2023-07-03 15:55 UTC, peombwa commented on CodeSnippetsReflection.OpenAPI.Test/PowerShellGeneratorTests.cs
> +            var snippetModel = new SnippetModel(requestPayload, ServiceRootBetaUrl, await GetV1SnippetMetadata());
You should call `GetBetaSnippetMetadata` instead of `GetV1SnippetMetadata` for beta tests. The same applies to all beta test.
```suggestion
            var snippetModel = new SnippetModel(requestPayload, ServiceRootBetaUrl, await GetBetaSnippetMetadata());
```

2023-07-03 16:23 UTC, peombwa approved these changes

2023-07-03 16:59 UTC, andrueastman approved these changes

2023-07-03 17:14 UTC, merged