Fixes functions with parameters in Go
microsoftgraph/microsoft-graph-devx-api pull request #1681
Opened 2023-07-24 15:15 UTC by rkodev

## Overview

Fixes generation fluent path in go for functions with paramerts e.g https://learn.microsoft.com/en-us/graph/api/reportroot-getyammeractivitycounts?view=graph-rest-1.0&tabs=http

Current behaviour
```go
graphClient.Reports().GetYammerActivityCounts(period='{period}')().Get(context.Background(), nil)
```

expected behaviour

```go
period = '{period}'
graphClient.Reports().GetYammerActivityCountsWithPeriod(&period).Get(context.Background(), nil)
```

## Testing Instructions

* Unit tests

2023-07-24 16:36 UTC, baywet requested changes

2023-07-24 16:36 UTC, baywet commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/GoGenerator.cs
> +            return nodes.Select(x => x.Segment.GetFunctionWithParameters())
```suggestion
            return nodes.Select(static x => x.Segment.GetFunctionWithParameters())
```

2023-07-24 16:36 UTC, baywet commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/GoGenerator.cs
> +                  .ToDictionary(g => g.Key, g => g.Last()));
```suggestion
                .Aggregate(new Dictionary<String, String>(), static (first, second) => first.Concat(second.Item3)
                  .GroupBy(static kvp => kvp.Key, static kvp => kvp.Value)
                  .ToDictionary(static g => g.Key, static g => g.Last()));
```

2023-07-25 07:06 UTC, andrueastman commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/GoGenerator.cs
> +                    var funcWithParams = x.Segment.GetFunctionWithParameters();
I think all you need to do here is call `x.Segment.IsFunctionWithParameters()`(already defined) then look up the parameters and values in `snippetCodeGraph.PathParameters` as 
- Functions with multiple parameters could exists
- The `snippetCodeGraph.PathParameters` in contains type information that you can use to know for scenarios where the parameter is a number/Date type
- Casing is consistent with the metadata therefore generating names that are aligned with the generated SDK.

2023-07-25 08:07 UTC, rkodev commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/GoGenerator.cs
> +                    var funcWithParams = x.Segment.GetFunctionWithParameters();
Thanks for this. One concern with the Path Parameter is we can have an example using 1 or 2 params instead of all the path parameters. Thats the reason I opted for extracting the parameters from the snippet. I however do agree that the path param will give better type information

2023-07-25 08:08 UTC, rkodev commented on CodeSnippetsReflection.OpenAPI/StringExtensions.cs
> +    private static readonly Regex FunctionWithParams = new(@"^(\w+)\(([^)]+)\)$", RegexOptions.Compiled, TimeSpan.FromMilliseconds(200));
The need here was to extract the parameters used in the example

2023-07-25 08:50 UTC, andrueastman commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/GoGenerator.cs
> +                    var funcWithParams = x.Segment.GetFunctionWithParameters();
If a path had 3 parameters, and the example would use only 2 parameters, that would mean that one of the parameters is optional or has a pre-defined default. In such a case i believe the metadata would either 
- have two distinct paths (one with the optional param and the other without). 
- one path but the default would still need to be generated/passed as Kiota will still generate the parameter name in the function https://github.com/microsoft/kiota/issues/2584

At this point of the snippet generation, the example path would already have been matched to the path that is relevant to it (when the snippet model is built) and every path parameter (including the optional ones if matched with their defaults) would be needed to be generated as only one url template is present and a parameter must be passed/included in function name. 

Using the http URL would generate a function that does not exist in the SDK in such a scenario as the default parameter would be missing/not passed.

2023-07-25 09:23 UTC, rkodev commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/GoGenerator.cs
> +            return nodes.Select(x => x.Segment.GetFunctionWithParameters())
done

2023-07-25 09:26 UTC, rkodev commented on CodeSnippetsReflection.OpenAPI/StringExtensions.cs
> +    private static readonly Regex FunctionWithParams = new(@"^(\w+)\(([^)]+)\)$", RegexOptions.Compiled, TimeSpan.FromMilliseconds(200));
I've combined these 2 since the existing regex both identify a function syntax. The difference is the new regex splits the function into "name" + "params" and make it simpler to return function names.

2023-07-25 09:35 UTC, rkodev commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/GoGenerator.cs
> +                    var funcWithParams = x.Segment.GetFunctionWithParameters();
The only left concern would be is it a given than the function with params is always the last segment of a path? This approach ensures that the params retain the position in the segment

2023-07-26 08:17 UTC, andrueastman requested changes
Latest updates break some tests in PHP/C#/Poweshell.

Any chance we can 
- Fix the broken test.
- Add a test for Go for the test thats broken. Should point to the snippet at https://learn.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-1.0&tabs=http

2023-07-26 08:19 UTC, andrueastman commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/GoGenerator.cs
> +                    if (!x.Segment.IsFunctionWithParameters())
This can be done first before `var funcWithParams = x.Segment.GetFunctionWithParameters();` as it assures us that results exist.

2023-08-01 07:38 UTC, andrueastman approved these changes

2023-08-01 07:38 UTC, merged