Rsh/snippet generation java kiota
microsoftgraph/microsoft-graph-devx-api pull request #1748
Opened 2023-09-06 22:20 UTC by ramsessanchez

Fixes #1026 
Adds snippet generation for the Kiota based Java-SDK using OpenApi

2023-09-07 06:52 UTC, andrueastman commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/JavaGenerator.cs
> +        private static string GetPropertyObjectName(CodeProperty codeProperty, string apiVersion)
```suggestion
        private static string GetPropertyObjectName(CodeProperty codeProperty)
```
unused parameter

2023-09-07 06:52 UTC, andrueastman commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/JavaGenerator.cs
> +                              .Aggregate((a, b) => $"{a}{b}").ToFirstCharacterUpperCase()+"().";
```suggestion
                              .Select(static s => s.ToFirstCharacterLowerCase())
                              .Aggregate(static (a, b) => $"{a}{b}").ToFirstCharacterUpperCase()+"().";
```

2023-09-07 06:52 UTC, andrueastman commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/JavaGenerator.cs
> +                        .Aggregate(new List<string>(), (current, next) =>
```suggestion
                        .Aggregate(new List<string>(), static (current, next) =>
```

2023-09-07 06:53 UTC, andrueastman commented
Thanks for this @ramsessanchez. This looks great. Any chance you can checkout the sonarcloud warnings as well?

2023-09-07 18:41 UTC, ramsessanchez commented
There is one remaining code smell regarding the use of Last(), the smell suggests that using count-1 would be more efficient, however split returns an array so the smell actually is not helpful.

2023-09-07 21:02 UTC, ramsessanchez commented
@andrueastman I believe that we need to add the namespace change to dotNet snippet generation as well. While we can still use .me() the reference to the namespace .me was removed when we removed it during generation thus making some snippets uncompilable.

2023-09-11 06:28 UTC, andrueastman approved these changes
> @andrueastman I believe that we need to add the namespace change to dotNet snippet generation as well. While we can still use .me() the reference to the namespace .me was removed when we removed it during generation thus making some snippets uncompilable.

Thanks for pointing this out @ramsessanchez, I've updated the issue description at https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1874 to capture this when this is implemented in the next breaking change for dotnet

2023-09-20 06:26 UTC, andrueastman submitted a review, later dismissed

2023-09-21 18:06 UTC, ramsessanchez commented
Ready to merge, will continue fixes to snippet generation on later PR's

2023-09-22 09:55 UTC, andrueastman commented on GraphWebApi/Controllers/SnippetsController.cs
> +                generation = (lang != "java" && OpenApiSnippetsGenerator.SupportedLanguages.Contains(lang)) ? "openapi" : "odata";
```suggestion
                generation = (!"java" .Equals(lang,StringComparison.OrdinalIgnoreCase)&& OpenApiSnippetsGenerator.SupportedLanguages.Contains(lang)) ? "openapi" : "odata";
```
The dictionary is case insensitive as well so we need to guard against that https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/3c66e2491cc5c32dce561ab24c786b4d06223847/CodeSnippetsReflection.OpenAPI/OpenAPISnippetsGenerator.cs#L77
Same for the other entry point as well.

2023-09-22 09:55 UTC, andrueastman commented on CodeSnippetsReflection.App/Program.cs
> +                generation = (language != "java" && OpenApiSnippetsGenerator.SupportedLanguages.Contains(language)) ? "openapi" : originalGeneration;
check for casing

2023-09-22 19:18 UTC, zengin requested changes

2023-09-22 19:18 UTC, zengin commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/JavaGenerator.cs
> +            var codeGraph = new SnippetCodeGraph(snippetModel);
I am glad that @rkodev's investments are paying dividends here :)

2023-09-22 19:18 UTC, zengin commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/JavaGenerator.cs
> +                    requestPayloadParameterName = GetPropertyObjectName(codeGraph.Body).ToFirstCharacterLowerCase();
nit: easier to read with a switch expression.
```suggestion
                requestPayloadParameterName = codeGraph.Body.PropertyType switch
                {
                    PropertyType.Binary => "stream",
                    _ => GetPropertyObjectName(codeGraph.Body).ToFirstCharacterLowerCase()
                };
```

2023-09-22 19:36 UTC, zengin approved these changes

2023-09-22 19:44 UTC, merged