chore: enable CodeQL, update branch protection policy, add issue automation
microsoftgraph/microsoft-graph-devx-api pull request #1759
Opened 2023-09-19 18:17 UTC by MIchaelMainer

## Overview

Improve branch protection by requiring conversation resolution (signoff), require strict status checks including CodeQL, and add issue automation. 

## Testing Instructions

After merge into dev:
1. Open a new test PR and witness that there are now required status checks, all PR comments require resolution.
2. Create test issue and set the Resolution: Duplicate label on it. It should be automatically closed. This only tests the one action and the bot integration is working.

2023-09-19 18:24 UTC, baywet requested changes

2023-09-19 18:24 UTC, baywet commented on .github/policies/microsoft-graph-devx-api-branch-protection.yml
> +    requiresStrictStatusChecks: true
can we pause the strictChecks roll out until we figure out a model for dependabot please?

2023-09-19 18:32 UTC, MIchaelMainer commented on .github/policies/microsoft-graph-devx-api-branch-protection.yml
> +    requiresStrictStatusChecks: true
Thank you for reminding me about this! Yes, paused. Let me get back to my write-up......

2023-09-26 22:14 UTC, MIchaelMainer commented on .github/policies/microsoft-graph-devx-api-branch-protection.yml
> +    requiresStrictStatusChecks: true
We don't need to have this set to true. I think we should make this setting true by default, and if the maintainer finds that this setting is more trouble than it is worth, then we can disable. For dependabot scenarios, we may want to consider a less frequent update cycle for non-securoty updates.

2023-09-27 11:55 UTC, baywet approved these changes

2023-09-27 17:38 UTC, merged