Add base import generator and model imports
microsoftgraph/microsoft-graph-devx-api pull request #1905
Opened 2024-01-18 22:32 UTC by shemogumbe

## Overview

Brief description of what this PR does, and why it is needed.

### Demo

Optional. Screenshots, `curl` examples, etc.

### Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Testing Instructions

* How to test this PR
* Prefer bulleted description
* Start after checking out this branch
* Include any setup required, such as bundling scripts, restarting services, etc.
* Include test case, and expected output

2024-01-24 13:35 UTC, andrueastman commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/PythonGenerator.cs
> +            var imports = importsGenerator.GenerateImportTemplates(snippetModel);
The call to `GenerateImportTemplates` ends up creating another `SnippetCodeGraph` instance internally. Since this is already available, it may make sense to change the function signature to take in `SnippetCodeGraph` as parameter and pass the value avaialble here directly.
Alternatively, we can call `GenerateImportTemplates` internally in the `SnippetCodeGraph` and have the results available as property of the `SnippetCodeGraph`

2024-01-24 13:35 UTC, andrueastman commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/SnippetImports.cs
> +    public List<Dictionary<string, string>> GenerateImportTemplates(SnippetModel snippetModel)
I think we should create a class(model) with the known keys(Path,RequestBuilderName, Name,TypeDefinition ) as properties rather than using `Dictionary<string, string>` here to avoid the key checking in the caller.

2024-01-24 13:35 UTC, andrueastman commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/SnippetImports.cs
> +                        { "Path", Regex.Replace(path.Replace("\\", ".").Replace("()", ""), @"\{[^}]*-id\}", "item", RegexOptions.None, TimeSpan.FromSeconds(60))},
We should probably create a static class property(so we don't keep instantiating a new one) for the regex and pass the compile flag too. 
Similar to https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/723913bef8fed8a109697ec51e367ea5d3c2f1fb/TelemetryService/CustomPIIFilter.cs#L30
```suggestion
                        { "Path", Regex.Replace(path.Replace("\\", ".").Replace("()", ""), @"\{[^}]*-id\}", "item", RegexOptions.Compiled, TimeSpan.FromSeconds(60))},
```

2024-01-24 14:00 UTC, shemogumbe commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/SnippetImports.cs
> +    public List<Dictionary<string, string>> GenerateImportTemplates(SnippetModel snippetModel)
The keys differ for models/ request builder/ request_body etc.
With the class approach how do we achieve this, coz at the point of calling, its the keys that help us know if we  have a model, request builder etc

2024-01-24 14:03 UTC, shemogumbe commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/SnippetImports.cs
> +                        { "Path", Regex.Replace(path.Replace("\\", ".").Replace("()", ""), @"\{[^}]*-id\}", "item", RegexOptions.None, TimeSpan.FromSeconds(60))},
This is a one off instance, its not used elsewhere, would that still require a static class?

2024-01-24 14:06 UTC, shemogumbe commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/SnippetImports.cs
> +    public List<Dictionary<string, string>> GenerateImportTemplates(SnippetModel snippetModel)
For models - we return a different set of key value pairs from what we return for Request_builder, same for request_body

2024-01-25 08:38 UTC, SilasKenneth requested changes

2024-01-25 08:38 UTC, SilasKenneth commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/PythonGenerator.cs
> +                    snippetImports.Add($"{modelImportPrefix}.{import["TypeDefinition"].ToSnakeCase()} import {import["TypeDefinition"]}");
```suggestion
                    snippetImports.Add($"{modelImportPrefix}.{typeDefinition.ToSnakeCase()} import {typeDefinition}");
```

2024-01-25 08:38 UTC, SilasKenneth commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/PythonGenerator.cs
> +                    snippetImports.Add($"{requestBuilderImportPrefix}{import["Path"].Replace(".me.", ".users.item.")}.{import["RequestBuilderName"].ToSnakeCase()} import {import["RequestBuilderName"]
```suggestion
                    snippetImports.Add($"{requestBuilderImportPrefix}{path.Replace(".me.", ".users.item.")}.{requestBuilderName.ToSnakeCase()} import {requestBuilderName}");
```

2024-01-25 08:38 UTC, SilasKenneth commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/PythonGenerator.cs
> +            HashSet<string> snippetImports = new HashSet<string>();
```suggestion
           var snippetImports = new HashSet<string>();
```

2024-01-25 08:38 UTC, SilasKenneth commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/SnippetImports.cs
> +        if (node.Children != null && node.Children.Count > 0)
```suggestion
        if (node.Children is { Count: > 0 })
```

2024-01-25 08:40 UTC, SilasKenneth reviewed
Looks good just a few suggestions.

2024-01-25 16:00 UTC, samwelkanda approved these changes

2024-01-25 16:29 UTC, merged