Add use import statements for PHP Snippets
microsoftgraph/microsoft-graph-devx-api pull request #2000
Opened 2024-03-19 13:02 UTC by shemogumbe

## Overview

Brief description of what this PR does, and why it is needed.

### Demo

Optional. Screenshots, `curl` examples, etc.

### Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Testing Instructions

* How to test this PR
* Prefer bulleted description
* Start after checking out this branch
* Include any setup required, such as bundling scripts, restarting services, etc.
* Include test case, and expected output

2024-03-20 20:40 UTC, timayabi2020 commented
There are a couple of sona source warnings. Maybe you should have a look.

2024-03-21 08:59 UTC, SilasKenneth requested changes

2024-03-21 09:09 UTC, andrueastman commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/PhpGenerator.cs
> +                        if (import.Path != null && import.RequestBuilderName != null)
```suggestion
                        if (!string.IsNullOrEmpty(import.Path) && !string.IsNullOrEmpty(import.RequestBuilderName))
```
We are checking a string.

2024-03-21 09:09 UTC, andrueastman commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/PhpGenerator.cs
> +                                .Select(s => s.ToFirstCharacterUpperCase()).ToArray();
```suggestion
                                .Select(static s => s.ToFirstCharacterUpperCase()).ToArray();
```

2024-03-21 09:09 UTC, andrueastman commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/PhpGenerator.cs
> +            var importsGenerator = new ImportsGenerator();
The `ImportsGenerator` could probably be a class variable. There is no need to create an instance every time the function is called.  Alternatively, the `GenerateImportTemplates` and `ImportsGenerator` and can be a static function and class so we don't have to create an instance when we need it as `GenerateImportTemplates` is a pure function.

2024-03-21 09:43 UTC, shemogumbe commented on CodeSnippetsReflection.OpenAPI.Test/PhpImportGeneratorTests.cs
> +        Assert.Contains("use Microsoft\\Graph\\Generated\\Models;", result);
Makes sense as a way of making the code more explicit and improving performance, that's how it's done in Python.

2024-03-26 08:15 UTC, SilasKenneth approved these changes

2024-03-26 19:34 UTC, merged