Shem/add comments on client initialization
microsoftgraph/microsoft-graph-devx-api pull request #2173
Opened 2024-08-24 10:03 UTC by shemogumbe

Fixes https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1937

## Overview

graph_client is currently referenced in snippets with no information on how to initialize it.

### Demo

before the line referencing graphcliet, a python comment is added saying

```python
# To initialize your graph_client, see https://learn.microsoft.com/en-us/graph/sdks/create-client?from=snippets&tabs=python

```

2024-08-26 07:03 UTC, andrueastman submitted a review, later dismissed

2024-08-26 11:31 UTC, Ndiritu commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/PythonGenerator.cs
>                                                     $"{ClientVarName} = {ClientVarType}({CredentialVarName}, {ScopesVarName}){Environment.NewLine}{Environment.NewLine}");
Should we remove the graph client instantiation line here?

2024-08-26 16:39 UTC, andrueastman commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/PythonGenerator.cs
>                                                     $"{ClientVarName} = {ClientVarType}({CredentialVarName}, {ScopesVarName}){Environment.NewLine}{Environment.NewLine}");
You're right. This should be dropped to match the spec.

2024-08-27 15:23 UTC, andrueastman commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/PythonGenerator.cs
> -                                                   $"{ClientVarName} = {ClientVarType}({CredentialVarName}, {ScopesVarName}){Environment.NewLine}{Environment.NewLine}");
Couple of things
- Some of these variables are no longer used.
- Check the tests that are broken due to this change.

2024-08-28 06:20 UTC, andrueastman commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/PythonGenerator.cs
> -                                                   $"{ClientVarName} = {ClientVarType}({CredentialVarName}, {ScopesVarName}){Environment.NewLine}{Environment.NewLine}");
Could we also remove the unused variables like `ClientVarName` and `ClientVarType` as well?

2024-08-28 13:55 UTC, shemogumbe commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/PythonGenerator.cs
> -                                                   $"{ClientVarName} = {ClientVarType}({CredentialVarName}, {ScopesVarName}){Environment.NewLine}{Environment.NewLine}");
ClientVarName is referenced in the request execution path :
```
            string pathSegment = $"{ClientVarName}.{GetFluentApiPath(codeGraph.Nodes, codeGraph)}";
```


I have removed scopes, credentials and varType

2024-08-29 06:49 UTC, andrueastman approved these changes
This may also break raptor validation as it may expect the client initialization code to build/validate. 
We should probably confirm that before merging this. Otherwise, looks good from my end.

2024-08-29 08:16 UTC, shemogumbe commented
> This may also break raptor validation as it may expect the client initialization code to build/validate. We should probably confirm that before merging this. Otherwise, looks good from my end.

Thought the same too, I will need to check if Raptor has a client initiated, if not, instatiate one within the snippets in Raptor, will keep this unmerged till I fix that

2024-08-29 09:34 UTC, Ndiritu commented on apidoctor
nit; conflicts

2024-09-03 07:04 UTC, Ndiritu requested changes

2024-09-03 07:04 UTC, Ndiritu commented on apidoctor
Ideally we shouldn't have changes to this submodule in this PR.

2024-09-03 07:07 UTC, andrueastman commented on apidoctor
+1

2024-09-03 08:12 UTC, Ndiritu approved these changes

2024-09-03 08:17 UTC, merged