Enable testing of Permissions Descriptions
microsoftgraph/microsoft-graph-devx-api pull request #436
Opened 2021-01-29 15:25 UTC by MaggieKimani1

This PR proposes adding testing support for Permission descriptions files on Graph Explorer

2021-02-01 12:45 UTC, irvinesunday commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +        public PermissionsStore(IConfiguration configuration, IFileUtility fileUtility = null, IMemoryCache permissionsCache = null, IHttpClientUtility httpClientUtility = null)
nit: It would look much better if we had just two parameters per line.

2021-02-01 12:47 UTC, irvinesunday commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +            ?? throw new ArgumentNullException($"Config path is missing:{ _permissionsContainerName }");
nit: Tab (once) any overflowing lines of code

2021-02-01 12:56 UTC, irvinesunday commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +                        // Get file contents from source
nit: some spacing before this comment would make for an easy reading :)

2021-02-01 13:50 UTC, irvinesunday commented on GraphWebApi/Controllers/GraphExplorerPermissionsController.cs
> +        public GraphExplorerPermissionsController(IPermissionsStore permissionsStore, IConfiguration configuration, IHttpClientUtility httpClientUtility)
nit: spacing between fields and constructor

2021-02-01 13:51 UTC, irvinesunday commented on GraphWebApi/Controllers/GraphExplorerPermissionsController.cs
> +                     httpClientUtility: _httpClientUtility);
nit: Tab (once)

2021-02-01 13:54 UTC, irvinesunday commented on GraphWebApi/Controllers/GraphExplorerPermissionsController.cs
> +                    result = await _permissionsStore.GetScopesAsync(scopeType: scopeType, locale: localeCode, requestUrl: requestUrl, method: method, org: org, branchName: branchName);
Would be easier on the eye if we limited to about 2 or 3 method args per line since we have introduced named params.

2021-02-01 13:55 UTC, irvinesunday commented on GraphWebApi/Startup.cs
> +            services.AddControllers();
You def. need back that extension method :)

2021-02-01 21:48 UTC, zengin requested changes

2021-02-01 21:48 UTC, zengin commented on CodeSnippetsReflection.Test/CSharpGeneratorShould.cs
> -        [Fact]
Not sure why this PR is reverting #427

2021-02-01 21:48 UTC, zengin commented on GraphExplorerSamplesService/Services/SamplesStore.cs
> -            using var httpRequestMessage = new HttpRequestMessage(HttpMethod.Get, queriesFilePathSource);
Please keep `using` as `HttpRequestMessage` is an `IDisposable` object.

If this is blocked because of the `LangVersion` change, then you can use the old `using` block style:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement#example

2021-02-01 21:48 UTC, zengin commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +            string refreshTime = configuration[CacheRefreshTimeConfig] ?? throw new ArgumentNullException($"Config path missing: {CacheRefreshTimeConfig}");
This line uses `configuration` before its null check that happens on line 52. Please check the validity of function parameters as the first thing in the function.

2021-02-01 21:48 UTC, zengin commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +        /// /// <param name="org">Optional: The name of the org/owner of the repo.</param>
nit:
```suggestion
        /// <param name="org">Optional: The name of the org/owner of the repo.</param>
```

2021-02-02 09:12 UTC, MaggieKimani1 commented on CodeSnippetsReflection.Test/CSharpGeneratorShould.cs
> -        [Fact]
This was accidental when I was merging dev into my branch.
Reverting the changes

2021-02-02 10:21 UTC, MaggieKimani1 commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +            string refreshTime = configuration[CacheRefreshTimeConfig] ?? throw new ArgumentNullException($"Config path missing: {CacheRefreshTimeConfig}");
Yeah, sure. Thanks for pointing it out.

2021-02-02 16:53 UTC, irvinesunday commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +            bool cacheState = (_permissionsCache.GetOrCreate("PermissionsTablesState", entry =>
You may remove the open and close parentheses.

2021-02-02 16:56 UTC, irvinesunday commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +                IDictionary<string, IDictionary<string, ScopeInformation>> scopesInformationDictionary;
Move declaration near reference (line 275)

2021-02-02 17:13 UTC, irvinesunday commented on PermissionsService.Test/PermissionsStoreShould.cs
> +            PermissionsStore permissionsStore = new PermissionsStore(configuration: _configuration, permissionsCache: _permissionsCache, httpClientUtility: _httpClientUtility,  fileUtility: _fileUtil
Would be a good idea to wrap about 2 args. per line.

2021-02-02 18:47 UTC, zengin commented on PermissionsService.Test/PermissionsStoreShould.cs
> +            PermissionsStore permissionsStore = new PermissionsStore(configuration: _configuration, permissionsCache: _permissionsCache, httpClientUtility: _httpClientUtility,  fileUtility: _fileUtil
My two cents: Two per line can be hard to maintain if a new change pushes a parameter in the middle. Then all lines will require shifting. I would suggest either a single line for all the parameters or one parameter per line.

2021-02-03 06:36 UTC, MaggieKimani1 commented on PermissionsService.Test/PermissionsStoreShould.cs
> +            PermissionsStore permissionsStore = new PermissionsStore(configuration: _configuration, permissionsCache: _permissionsCache, httpClientUtility: _httpClientUtility,  fileUtility: _fileUtil
I could wrap a single arg per line for readability purposes and to make it easier to disable or reorder them.

2021-02-03 07:19 UTC, irvinesunday commented on PermissionsService.Test/PermissionsStoreShould.cs
> +        public void MockFetchingPermissionsDescriptionsFromGithub()
```suggestion
        public void FetchPermissionsDescriptionsFromGithub()
```

2021-02-03 07:20 UTC, irvinesunday commented on PermissionsService.Test/PermissionsStoreShould.cs
> +        public void MockFetchingPermissionsDescriptionsFromGithubGivenARequestUrl()
```suggestion
        public void FetchPermissionsDescriptionsFromGithubGivenARequestUrl()
```

2021-02-08 10:24 UTC, irvinesunday approved these changes
👍🏽

2021-02-08 18:28 UTC, zengin approved these changes

2021-02-08 18:28 UTC, zengin commented on FileService/Services/DiskFileUtility.cs
> +// ------------------------------------------------------------------------------------------------------------------------------------------------------
nit: have the copyright header before the `using` statements.

2021-02-08 19:45 UTC, MaggieKimani1 commented on FileService/Services/DiskFileUtility.cs
> +// ------------------------------------------------------------------------------------------------------------------------------------------------------
I think that's what I've done. Unless I don't understand what you mean.

2021-02-08 20:09 UTC, zengin commented on FileService/Services/DiskFileUtility.cs
> +// ------------------------------------------------------------------------------------------------------------------------------------------------------
I am sorry, I misinterpreted the diff.

2021-02-09 07:35 UTC, merged