Adds Changes endpoint
microsoftgraph/microsoft-graph-devx-api pull request #455
Opened 2021-02-10 11:44 UTC by irvinesunday

**Summary**
The Changes endpoint will be used primarily by Graph Explorer to surface changelog info. The changelog info describes Microsoft Graph API endpoint changes that have occurred in both V1.0 and Beta. Graph Explorer will call this Changelog endpoint to retrieve any changelog info. associated with a particular Microsoft Graph endpoint.

Changelog info can be retrieved by:
- Microsoft Graph url
- Workload name
- Dates
- Number of days

The response can also be paginated.

**This PR proposes**:
- Adding in a new `/Changes` endpoint.
- Updating the OpenAPI description with the new `/Changes` endpoint.
- Adding a `ChangesService` service library.
- Updating the `appsettings.json` with new configs for the `ChangesService` service library 
- Adding tests to validate the `ChangesService` service library.

Closes: [AB#6825](https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_workitems/edit/6825/)
Requirements doc: https://microsofteur-my.sharepoint.com/:w:/g/personal/bengugi_microsoft_com/ETcytiFdE_tMo7WNqgWTzbIBfZCwjLf_lGL2ckFhCXbGUQ?e=PxywbK

2021-02-11 04:55 UTC, ddyett commented on ChangesService/Common/ChangesServiceConstants.cs
> +        public const string ChangelogRefreshTimeDefault = "24";
is this one used somewhere?

2021-02-11 04:58 UTC, ddyett commented on ChangesService/Models/ChangeLogList.cs
> +            }
consider get =>  _changeLogs

2021-02-11 05:02 UTC, ddyett commented on ChangesService/Models/MicrosoftGraphProxyConfigs.cs
> +        public string GraphVersion { get; set; } = "v1.0";
consider making these init only {get; init; } =  "v1.0"

2021-02-11 05:06 UTC, ddyett commented on ChangesService/Models/ChangeLogList.cs
> +using Newtonsoft.Json;
how far off are we with work to move away from newtonsoft.

2021-02-11 05:18 UTC, ddyett commented on ChangesService/Models/ChangeLogList.cs
> +        private List<ChangeLog> _changeLogs;
i don't see anything to add,remove, etc on this list so it looks like there's a set up to create lists and replace them

2021-02-11 05:22 UTC, ddyett commented on ChangesService/Services/ChangesService.cs
> +        private static readonly IDictionary<string, string> _urlWorkloadDict = new Dictionary<string, string>();
since now on C# 9 consider

private static readonly Dictionary<string, string> _urlWorkloadDict = new();

2021-02-11 05:47 UTC, ddyett commented on ChangesService/Services/ChangesService.cs
> +            ChangeLogList changeLogListByWorkload = new ChangeLogList();
why do you need this variable when tempChangeLogList can just be assigned the filter return directly

2021-02-11 05:49 UTC, ddyett commented on ChangesService/Services/ChangesService.cs
> +                                                                      workload).ToList();
the code here looks inefficient.  you filter, then convert to the list, then potentially filter again for date and convert to list again.  Why not operate on the IEnumerable then convert later on?

2021-02-11 05:59 UTC, ddyett commented on ChangesService/Services/ChangesService.cs
> +                else if (searchOptions.Page < tempChangeLogList.TotalPages)
there seems to be some inefficiency in that  when I call for page 1 we do all that filtering work, then when I call for page 2 we do all that filtering work again.  Just a lot of list being created and destroyed.

2021-02-11 06:06 UTC, ddyett commented on ChangesService/Services/ChangesStore.cs
> +            if (string.IsNullOrEmpty(locale) || locale.Equals("en-gb", StringComparison.OrdinalIgnoreCase))
why call out en-gb in particular since there are several other english variants?

2021-02-11 06:09 UTC, ddyett commented on ChangesService/Services/ChangesStore.cs
> +                    string relativeUrl = string.Format(_changeLogRelativeUrl, locale);
try to be consistent if using var or using type

2021-02-11 06:11 UTC, ddyett commented on FileService/Common/FileServiceConstants.cs
> +            public static string ApplicationJsonMediaType = "application/json";
make readonly.

2021-02-11 14:03 UTC, baywet requested changes

2021-02-11 14:03 UTC, baywet commented on FileService/Services/HttpClientUtility.cs
> +            var fileContents = await httpResponseMessage?.Content.ReadAsStringAsync();
```suggestion
            var fileContents = await httpResponseMessage?.Content?.ReadAsStringAsync();
```

2021-02-11 14:03 UTC, baywet commented on FileService/Services/HttpClientUtility.cs
>              var httpResponseMessage = await _httpClient?.SendAsync(requestMessage);
```suggestion
            using var httpResponseMessage = await _httpClient?.SendAsync(requestMessage);
```

2021-02-15 13:41 UTC, irvinesunday commented on ChangesService/Services/ChangesService.cs
> +            ChangeLogList changeLogListByWorkload = new ChangeLogList();
Directly altering the `tempChangeLogList` object will inadvertently alter the param object `changeLogList` since it is assigned its reference. An improved approach could be to declare the `ChangeLogList` variables and `new()` them up when necessary within the code blocks.

```
            ChangeLogList changeLogListByWorkload; // declare here

            if (!string.IsNullOrEmpty(searchOptions.RequestUrl))
            {
                // Retrieve the workload name from the requestUrl
                var workload = RetrieveWorkloadNameFromRequestUrl(searchOptions, graphProxyConfigs, httpClientUtility)
                                .GetAwaiter().GetResult();

                changeLogListByWorkload = new(); // instantiate here

                // Search by retrieved workload name
                changeLogListByWorkload.ChangeLogs = FilterChangeLogListByWorkload(tempChangeLogList,
                                                                      workload).ToList();

                tempChangeLogList = changeLogListByWorkload;
            }
```
So we don't end up creating lists we don't use.

2021-02-15 16:35 UTC, irvinesunday commented on ChangesService.Test/ChangeLogSearchOptionsModelShould.cs
> +                new ChangeLogSearchOptions(startDate: startDate, daysRange: 90));
So technically speaking, when the `daysRange` is specified, the `endDate` will be the current day's date while the `startDate` will be calculated from `endDate` - `daysRange`. 
1. If you want data for the past x number of days up to current day, you just specify daysRange as x
2. If you want data for a given time duration, you specify the `startDate` and `endDate`. I'm guessing someone might have the `startDate` and just wants to get data for the following x number of days without needing to explicitly specifying the `endDate`. This is the scenario where your question falls into?

2021-02-15 18:10 UTC, baywet commented on ChangesService.Test/ChangeLogSearchOptionsModelShould.cs
> +                new ChangeLogSearchOptions(startDate: startDate, daysRange: 90));
I think that cover the case where only daysRange is specified. I feel like we could support specifying daysRange + startDate and daysRange + endDate without throwing an exception back to the consumer.

2021-02-15 21:17 UTC, irvinesunday commented on ChangesService/Interfaces/IChangesStore.cs
> +        Task<ChangeLogList> FetchChangeLogListAsync(string locale);
Thanks for the tip. I can implement the CultureInfo class within the existing method as below for the specific use case of checking whether locale values are formed correctly and for picking out English culture variations.

```
        public async Task<ChangeLogList> FetchChangeLogListAsync(string locale)
        {
            var englishId = "en-us"; // default locale
            if (string.IsNullOrEmpty(locale))
            {
                locale = englishId;
            }

            // Check for English CultureInfo variants
            if (new CultureInfo(locale).TwoLetterISOLanguageName.Equals("en", StringComparison.OrdinalIgnoreCase))
            {
                // All English CultureInfo variants
                // should default to 'en-us'
                locale = englishId;
            }
        }
```

In your suggestion though, how different would the method with a default implementation accepting a `CultureInfo` be?

2021-02-16 10:04 UTC, irvinesunday commented on FileService/Common/FileServiceConstants.cs
> +            public static string ApplicationJsonMediaType = "application/json";
Resolved with `const`

2021-02-16 10:05 UTC, irvinesunday commented on ChangesService/Services/ChangesStore.cs
> +            if (string.IsNullOrEmpty(locale) || locale.Equals("en-gb", StringComparison.OrdinalIgnoreCase))
Good call.

2021-02-16 10:11 UTC, irvinesunday commented on ChangesService/Common/ChangesServiceConstants.cs
> +        public const string ChangelogRefreshTimeDefault = "24";
No. Redundant.

2021-02-16 10:12 UTC, irvinesunday commented on ChangesService/Models/ChangeLogList.cs
> +        private List<ChangeLog> _changeLogs;
Are you inferring that the choice of the class name is misleading?

2021-02-16 10:14 UTC, irvinesunday commented on ChangesService/Services/ChangesService.cs
> +            ChangeLogList changeLogListByWorkload = new ChangeLogList();
Resolved: `tempChangeLogList` replaced with an `IEnumerable<ChangeLog>`.

2021-02-16 10:14 UTC, irvinesunday commented on ChangesService/Services/ChangesService.cs
> +                else if (searchOptions.Page < tempChangeLogList.TotalPages)
Resolved: List is created at the end of all filtering

2021-02-16 10:16 UTC, irvinesunday commented on ChangesService/Services/ChangesStore.cs
> +            if (string.IsNullOrEmpty(locale) || locale.Equals("en-gb", StringComparison.OrdinalIgnoreCase))
Resolved: All variants of supported locales are defaulted.

2021-02-16 10:19 UTC, irvinesunday commented on ChangesService/Services/ChangesService.cs
> +                                                                      workload).ToList();
Resolved with the `IEnumerable<ChangeLog> enumerableChangeLog` object

2021-02-16 10:22 UTC, irvinesunday commented on ChangesService/Models/ChangeLogList.cs
> +using Newtonsoft.Json;
What is the motivation for wanting to move the project away from `Newtonsoft.Json`?

2021-02-16 13:22 UTC, baywet commented on ChangesService/Interfaces/IChangesStore.cs
> +        Task<ChangeLogList> FetchChangeLogListAsync(string locale);
Back in the aspnet classic days (before core) the accept-language request header used to set the current ui thread culture so the MVC stack could switch between resources.
I believe this is still the case with core if you add this middleware https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.localization.requestlocalizationmiddleware?view=aspnetcore-5.0

In which case, the method in the RequestHelper is obsolete, and instead of passing the culture as a string, the process could rely on the current ui thread culture.

The other advantage of using cultures over plain string is because of their capability to parse the culture names for us, and link cultures to their parents. I don't believe we should be manipulating strings anymore, just looking at the two/three letters language name and/or the parent when we don't have that specific culture.

Additionally, because we don't have specialized locales files, I believe our files should be stored as the main culture for all the locales (i.e. fr instead of fr-fr). This way we'd match [the common fallback behavior](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-5.0#culture-fallback-behavior-2) prescribed by dotnet for the last decades.
This means that instead of building [a switch case](https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/455/files#diff-bd8fedd6df77a56a7aa4adcc8e7495e2ed9f7ac5506f7dfe0b0c48b4fba0fb57R60) we should:

1. Read the thread culture
2. Check for the presence in the cache or on disk of the xx-XX variant (return it if we find it)
3. Check for the presence in the cache or on disk of the xx variant (return it if we find it)
4. Check for the presence in the cache or on disk of the en variant (default fallback)

Now that being said. I can understand that we don't anticipate to provide a variant for fr-CA as opposed to fr-FR. So we could imagine skip step 2. (although our [public docs](https://docs.microsoft.com/en-us/locale/?target=https://docs.microsoft.com/en-us/graph/throttling) do make the distinction between fr-CA, fr-CH, fr-FR, and fr-BE)

The reason I'm being so specific is because I've worked a couple of years on [a localization product for SharePoint](https://oceanik.com/) and I've had to dive in the inner details of how localization works in dotnet, the specific in SharePoint, Windows, browsers... One of the key aspects to a functional localization process is to make sure it's implemented consistently with the platform the application runs on. Otherwise you'll run into weird edge cases where for some reason the localization is not working as expected for this or that locale.

Lastly, instead of building the cache and language switch mechanism ourselves, we could rely on resx, they do pre-load the content in memory and they do the switch of resource based on the UI thread. Maybe something to explore in addition to what I was mentioning above?

2021-03-02 08:36 UTC, irvinesunday commented on ChangesService/Models/ChangeLogList.cs
> +using Newtonsoft.Json;
Here's the issue to track this: https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/486

2021-03-02 14:09 UTC, irvinesunday commented on ChangesService/Services/ChangesService.cs
> +    public static class ChangesService
The behaviour and responsibilities exposed by this class are essentially utility functions; I did not see any reason to create an interface that defines functionalities to be inherited (and implemented) by this class (and consequently injected through DI) because there would be no need for creating a different class that would implement the interface definitions differently. 
This class currently has methods that test its functionality.

2021-03-02 14:11 UTC, irvinesunday commented on ChangesService/Models/ChangeLogList.cs
> +        private List<ChangeLog> _changeLogs;
Changed to `ChangeLogRecords`

2021-03-04 18:13 UTC, irvinesunday commented on ChangesService/Models/ChangeLogList.cs
> +        private void UpdateTotalPages()
@baywet I didn't quite get that, please explain further.

2021-03-16 11:41 UTC, thewahome commented on ChangesService.Test/ChangeLogPaginationModelShould.cs
> +            var pagination = new ChangeLogPagination();
This arrangement is repeated in the next test. It can go into a setup function

2021-03-16 11:59 UTC, thewahome commented on ChangesService/Services/ChangesService.cs
> +        public static ChangeLogRecords FilterChangeLogRecords(ChangeLogRecords changeLogRecords,
Consider breaking down this function into smaller private functions that get called by this public function.

2021-03-16 12:01 UTC, thewahome commented on ChangesService/Services/ChangesService.cs
> +            }
This can be extracted to its own function called paginateFilteredResults so that the `FilterChangeLogRecords` is smaller and easier to understand

2021-03-16 12:03 UTC, thewahome commented on ChangesService/Services/ChangesService.cs
> +            var workloadName = targetWorkloadId.Split('.').Last();
The comment may be rendered unnecessary if this block is turned into a self-documenting function

2021-03-16 16:23 UTC, irvinesunday commented on ChangesService/Services/ChangesService.cs
> +            var workloadName = targetWorkloadId.Split('.').Last();
I think the block is too small to warrant its own function. Furthermore, the function of the block is in line with the method name wherein it is contained.

2021-03-16 16:31 UTC, baywet commented on ChangesService/Models/ChangeLogList.cs
> +        private void UpdateTotalPages()
instead of calling this update method (remove it) have a total pages and a total items property that lazy loads the value by calling count. The only additional complexity it so make sure you compare the previous page size and the current one to determine whether or not you need to recalculate that value before returning it.

Note for myself, this has moved to ChangeLogRecords

2021-03-16 16:33 UTC, baywet commented on ChangesService/Services/ChangesService.cs
> +    public static class ChangesService
sure. Static instances usually lead to taking shortcuts and making thread safety as well as testability harder. But if you're happy with the current version, I'll leave it up to you.

2021-03-16 16:35 UTC, baywet commented on ChangesService/Interfaces/IChangesStore.cs
> +        Task<ChangeLogList> FetchChangeLogListAsync(string locale);
thanks for implementing the changes, resolving

2021-03-17 12:38 UTC, irvinesunday commented on ChangesService/Models/ChangeLogList.cs
> +        private void UpdateTotalPages()
Thanks for the clarification.
This is okay for the _TotalPages_ property. We can have the logic for getting the total pages in the getter. However for the _TotalItems_ property, its value needs to be set only once during the lifetime of an instance, and that's when the _ChangeLogs_ property is first initialized with a value. We use this property to get the total item count for _ChangeLogs_ before any pagination (which updates the _ChangeLogs_ count) is done. I think this can remain as is.

2021-03-17 13:16 UTC, baywet commented on ChangesService/Models/ChangeLogList.cs
> +        private void UpdateTotalPages()
then use a readonly property instead?

2021-03-17 16:02 UTC, irvinesunday commented on ChangesService/Models/ChangeLogList.cs
> +        private void UpdateTotalPages()
For _TotalPages_? This is updated to a readonly property. _TotalItems_ has a private setter. It needs the private setter to be able to capture the count of _ChangeLogs_ when this is first initialized.

2021-03-18 13:06 UTC, baywet requested changes
thanks for making the changes around localization. A few minor follow ups, mostly around code duplication

2021-03-18 13:06 UTC, baywet commented on FileService/Common/FileServiceHelper.cs
> +        public static string GetSupportedLocaleVariant(CultureInfo cultureInfo)
remove in favor of the extension method

2021-03-18 13:06 UTC, baywet commented on FileService/Extensions/LocalizationExtensions.cs
> +            var langName = new CultureInfo(cultureInfoName).TwoLetterISOLanguageName ?? "en"; // english is the default
```suggestion
            return new CultureInfo(cultureInfoName).GetSupportedLocaleVariant();
```
and remove everything below

2021-03-18 16:42 UTC, irvinesunday commented on FileService/Common/FileServiceHelper.cs
> +        public static string GetSupportedLocaleVariant(CultureInfo cultureInfo)
I missed this. Thank you

2021-03-19 11:54 UTC, baywet approved these changes

2021-03-19 18:21 UTC, merged