ReEnable app insights
microsoftgraph/microsoft-graph-devx-api pull request #525
Opened 2021-04-07 07:03 UTC by MaggieKimani1

This PR involves reenabling App Insights for code-based monitoring using the ASP.Net Core SDK.
It also captures PII data handling by cleaning out any from of GUIDS or usernames and email addresses from the request body.

2021-04-07 13:07 UTC, baywet requested changes

2021-04-07 13:07 UTC, baywet commented on GraphWebApi/Telemetry/TelemetryProcessor.cs
> +            _next = next;
defensive programming?

2021-04-07 13:07 UTC, baywet commented on GraphWebApi/Telemetry/TelemetryProcessor.cs
> +                if (request != null)
```suggestion
                if (item is RequestTelemetry request)
```
(and remove the previous line)

2021-04-07 13:07 UTC, baywet commented on GraphWebApi/Telemetry/TelemetryProcessor.cs
> +                    request.Name = _guidRegex.Replace(request.Name, "{customerID}");
could Name be null?

2021-04-07 13:07 UTC, baywet commented on GraphWebApi/Telemetry/TelemetryProcessor.cs
> +                        if (_guidRegex.IsMatch(request.Url?.AbsoluteUri))
no need for null propagation operator as you're testing for not null in parent block

2021-04-07 13:27 UTC, MaggieKimani1 commented on GraphWebApi/appsettings.json
> +    "AppInsightsApiKey": "ENTER_KEY_HERE",
They're not similar but I can do away with the API key

2021-04-07 19:35 UTC, nikithauc commented on GraphWebApi/Telemetry/TelemetryMiddleware.cs
> +        public static string GetOperationId(string id)
Please add summary for this function and describe what id stands for.

2021-04-07 19:36 UTC, nikithauc commented on GraphWebApi/Telemetry/TelemetryProcessor.cs
> +        public Uri SanitizeUrl(Uri requestUrl)
Can you add unit tests for the changes in this PR?

2021-04-07 19:39 UTC, nikithauc commented on GraphWebApi/Telemetry/TelemetryProcessor.cs
> +                        request.Name = _guidRegex.Replace(request.Name, "{customerID}");
Do we need a _emailRegex.Replace here as the comment mentions - Regex-replace anything that looks like a GUID or email?

2021-04-07 19:40 UTC, nikithauc commented on GraphWebApi/Controllers/GraphExplorerPermissionsController.cs
> +using GraphWebApi.Telemetry;
Is this import being used anywhere? As the file has no other changes?

2021-04-07 19:47 UTC, nikithauc commented on GraphWebApi/Telemetry/TelemetryProcessor.cs
> +        private static Regex _username = new Regex("(fn|ln|lastname|firstname|name|fullname)");
How does this work?

2021-04-08 02:25 UTC, MIchaelMainer reviewed
Will we be able to test the telemetry capture against a pre-release instance of this application? I want to see what we capture before we take this to production.

Also, what is the context of this PR? Where is the data coming from?

2021-04-08 02:25 UTC, MIchaelMainer commented on GraphWebApi/Startup.cs
> +                options.RequestCollectionOptions.InjectResponseHeaders = true;
I don't think this is applicable here but response headers can contain PII. Just an FYI, please resolve.

2021-04-08 02:25 UTC, MIchaelMainer commented on GraphWebApi/Telemetry/TelemetryMiddleware.cs
> +                    Name = $"{context.Request.Method + " " + context.Request.Path.Value}"
Comment doesn't match the format.

`context.Request.Path.Value` looks like a URL. Where is this URL coming from and could it contain PII? If so, it must be sanitized.

2021-04-08 02:25 UTC, MIchaelMainer commented on GraphWebApi/Telemetry/TelemetryMiddleware.cs
> +                if (requestHeaders.ContainsKey("Request-Id"))
I don't think the header case is always `Request-Id`. In fact, Request-Id is returned in responses, not requests.  Please make this check `StringComparison.OrdinalIgnoreCase`. I'm not quite sure I understand the context of these changes in this PR so it may make sense to check for `client-request-id`.

2021-04-08 02:25 UTC, MIchaelMainer commented on GraphWebApi/Telemetry/TelemetryProcessor.cs
> +        private static Regex _username = new Regex("(fn|ln|lastname|firstname|name|fullname)");
Also, does this filter properties like `$filter(displayname -eq 'Michael Mainer')` in a URL?

2021-04-08 02:25 UTC, MIchaelMainer commented on GraphWebApi/Telemetry/TelemetryProcessor.cs
> +        private static Regex _guidRegex = new Regex(@"\b[A-F0-9]{8}(?:-[A-F0-9]{4}){3}-[A-F0-9]{12}\b",
Are these the same filters used in GE? @millicentachieng

2021-04-08 09:14 UTC, irvinesunday commented on GraphWebApi/Telemetry/TelemetryProcessor.cs
> +        private static Regex _emailRegex = new Regex(@"([a-zA-Z0-9_\.-]+)@([\da-zA-Z\.-]+)\.([a-zA-Z\.]{2,6})",
With [C#9](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9#fit-and-finish-features) you can omit the type in your constructor invocations: e.g.:

```suggestion
        private static readonly Regex _emailRegex = new(@"([a-zA-Z0-9_\.-]+)@([\da-zA-Z\.-]+)\.([a-zA-Z\.]{2,6})",
```
 Also, update the private fields to be `readonly`

2021-04-08 09:14 UTC, irvinesunday commented on GraphWebApi/Telemetry/TelemetryMiddleware.cs
> +                using (var operation = client.StartOperation(requestTelemetry))
You may simplify the using statement:

```suggestion
                using var operation = client.StartOperation(requestTelemetry);
```
Then remove the redundant open and close braces that follow.

2021-04-08 09:14 UTC, irvinesunday commented on GraphWebApi/Telemetry/TelemetryMiddleware.cs
> +        public async Task Invoke(HttpContext context, TelemetryClient client)
Please add a summary for this public method.

2021-04-08 09:15 UTC, irvinesunday commented on GraphWebApi/Telemetry/TelemetryMiddleware.cs
> +using System.Collections.Generic;
Unused import; you may remove.

2021-04-08 09:15 UTC, irvinesunday commented on GraphWebApi/Properties/ServiceDependencies/local/appInsights1.arm.json
> +  "metadata": {
Should this property be here? 
See: https://docs.microsoft.com/en-us/azure/azure-monitor/app/resource-manager-app-resource

2021-04-08 09:15 UTC, irvinesunday commented on GraphWebApi/Properties/ServiceDependencies/local/appInsights1.arm.json
> +              "properties": {},
Do we need to include the required missing property `Application_Type` under `properties`?
![image](https://user-images.githubusercontent.com/40403681/113995138-a525d580-985e-11eb-87c5-1c75a2765b08.png)

2021-04-08 09:15 UTC, irvinesunday commented on GraphWebApi/Controllers/GraphExplorerSamplesController.cs
> +using Microsoft.ApplicationInsights;
Unused import; you may remove.

2021-04-08 12:48 UTC, baywet requested changes

2021-04-08 12:48 UTC, baywet commented on GraphWebApi/Telemetry/TelemetryMiddleware.cs
> +                using (var operation = client.StartOperation(requestTelemetry))
you're also missing defensive programming for the client

2021-04-08 12:50 UTC, baywet commented on GraphWebApi/Telemetry/TelemetryMiddleware.cs
> +            int rootEnd = (int)(id?.IndexOf('.'));
```suggestion
            int rootEnd = id?.IndexOf('.') ?? -1;
```

2021-04-08 12:52 UTC, baywet commented on GraphWebApi/Telemetry/TelemetryMiddleware.cs
> +            // Returns the root ID from the '|' to the first '.' if any.
```suggestion
            if(string.IsNullOrEmpty(id)) return string.Empty;
            // Returns the root ID from the '|' to the first '.' if any.
```

2021-04-08 12:53 UTC, baywet commented on GraphWebApi/Telemetry/TelemetryProcessor.cs
> +                    if(request.Name != null)
```suggestion
                    if(!string.IsNullOrEmpty(request.Name))
```

2021-04-09 06:59 UTC, MaggieKimani1 commented on GraphWebApi/Telemetry/TelemetryProcessor.cs
> +                        request.Name = _guidRegex.Replace(request.Name, "{customerID}");
That's a typo on my end. The regex only caters for GUIDs

2021-04-09 07:01 UTC, MaggieKimani1 commented on GraphWebApi/Controllers/GraphExplorerPermissionsController.cs
> +using GraphWebApi.Telemetry;
No it's not. Cleaning it up..

2021-04-13 03:53 UTC, ddyett commented
We should put this in a feature branch first so we can do validation we have no privacy or security issues.  I wouldn't want this to block deploying other work.

2021-04-13 04:04 UTC, ddyett commented on GraphWebApi/Startup.cs
> +                options.EnableAdaptiveSampling = true;    // Enable adaptive sampling
the name is self explanatory.  it would be great if the comment better described what enabling adaptive sampling means.

2021-04-13 04:14 UTC, ddyett commented on GraphWebApi/Telemetry/TelemetryMiddleware.cs
> +                            requestTelemetry.Success = context.Response.StatusCode >= 200 && context.Response.StatusCode <= 299;
```suggestion
                            requestTelemetry.Success = context.Response.StatusCode is >= 200 and <= 299;
```

2021-04-13 04:20 UTC, ddyett commented on GraphWebApi/Telemetry/TelemetryMiddleware.cs
> +            int rootEnd = (int)(id?.IndexOf('.'));
stay consistent with var usage.

2021-04-13 04:21 UTC, ddyett commented on GraphWebApi/Telemetry/TelemetryProcessor.cs
> +        private static Regex _guidRegex = new Regex(@"\b[A-F0-9]{8}(?:-[A-F0-9]{4}){3}-[A-F0-9]{12}\b",
public static readonly

2021-04-13 04:25 UTC, ddyett commented on GraphWebApi/Telemetry/TelemetryProcessor.cs
> +        public Uri SanitizeUrl(Uri requestUrl)
looks like this can be private and static since it doesn't use any instance properties.

2021-04-13 04:27 UTC, ddyett commented on GraphWebApi/Telemetry/TelemetryProcessor.cs
> +                    requestUrl = new Uri(_guidRegex.Replace(requestUrl.ToString(), "{customerID}"));
not true that any guid is a customerid.  Perhaps just Id

2021-04-13 04:32 UTC, ddyett commented on GraphWebApi/Telemetry/TelemetryMiddleware.cs
> +    public class TelemetryMiddleware
unit test this middleware.

2021-04-13 08:44 UTC, thewahome requested changes

2021-04-13 08:44 UTC, thewahome commented on GraphWebApi/Telemetry/TelemetryProcessor.cs
> +        // Matches usernames with firstname or lastname labels
I have noticed a huge amount of comments on the code even in places where the code is self-explanatory. When there are many comments and a refactor happens, the comments can quickly get outdated and not match the methods they intend to explain.

When a statement/a set of statements require comments for them to make sense, it/they are ripe for refactoring into a method (or a better named variable in the case of a statement )that communicates intent. So that someone can easily read the function name and understand it. 

Summaries on public functions are helpful for the public clients that depend on them.

2021-04-13 10:32 UTC, MaggieKimani1 commented on GraphWebApi/Telemetry/TelemetryProcessor.cs
> +        private static Regex _username = new Regex("(fn|ln|lastname|firstname|name|fullname)");
I've implemented logic to filter that out

2021-04-14 17:31 UTC, fey101 commented on GraphWebApi/Telemetry/TelemetryMiddleware.cs
> +                            requestTelemetry.Success = context.Response.StatusCode >= 200 && context.Response.StatusCode <= 299;
Is StatusCode **is** >= 200 **and** <= 299 valid C# code? Interesting coz it looks like a mix of syntax from different languages?

2021-04-14 17:58 UTC, fey101 commented on GraphWebApi/Telemetry/TelemetryProcessor.cs
> +        private static readonly Regex _guidRegex = new(@"\b[A-F0-9]{8}(?:-[A-F0-9]{4}){3}-[A-F0-9]{12}\b",
This appears quite strange to me. Is there no package in C# that can handle this better than having one hard code the actual regex? Or why was this necessary?

2021-04-15 06:04 UTC, MaggieKimani1 commented on GraphWebApi/Telemetry/TelemetryProcessor.cs
> +        private static readonly Regex _guidRegex = new(@"\b[A-F0-9]{8}(?:-[A-F0-9]{4}){3}-[A-F0-9]{12}\b",
I haven't found a package that caters to my particular use case, hence the hard coding.

2021-04-20 12:39 UTC, baywet requested changes

2021-04-20 12:39 UTC, baywet commented on GraphWebApi/Telemetry/CustomPIIFilter.cs
> +                if (value.IsMatch(requestPath) && value.IsMatch(renderedMessage))
shouldn't it be || instead?

2021-04-20 12:39 UTC, baywet commented on GraphWebApi/Telemetry/CustomPIIFilter.cs
> +            foreach (var value in piiRegex.Values)
```suggestion
            foreach (var piiRegex in piiRegexes.Values)
```

2021-04-20 12:39 UTC, baywet commented on GraphWebApi/Telemetry/CustomPIIFilter.cs
> +            var piiRegex = new Dictionary<string, Regex>
```suggestion
            var piiRegexes = new Dictionary<string, Regex>
```

2021-04-20 12:39 UTC, baywet commented on GraphWebApi/Telemetry/CustomPIIFilter.cs
> +                if (requestPath.Contains("filter") && requestPath.Contains("displayname"))
what about firstName, lastName, email?... maybe this should rely on a list instead and iterate over it

2021-04-20 15:13 UTC, MaggieKimani1 commented on GraphWebApi/Telemetry/CustomPIIFilter.cs
> +                if (requestPath.Contains("filter") && requestPath.Contains("displayname"))
Oh yes, let me make that addition

2021-04-20 15:16 UTC, baywet commented on GraphWebApi/Telemetry/CustomPIIFilter.cs
> +                if (value.IsMatch(requestPath) && value.IsMatch(renderedMessage))
but won't this condition sanitize ONLY if BOTH contain PII information?

2021-04-20 15:23 UTC, MaggieKimani1 commented on GraphWebApi/Telemetry/CustomPIIFilter.cs
> +                if (value.IsMatch(requestPath) && value.IsMatch(renderedMessage))
I can change it to || , but my understanding is that if the request path has PII, then definitely the rendered message will also contain PII since it contains the request path string.

2021-04-20 15:41 UTC, baywet commented on GraphWebApi/Telemetry/CustomPIIFilter.cs
> +                if (value.IsMatch(requestPath) && value.IsMatch(renderedMessage))
let me rephrase: is there a possibility for either requestPath or renderedMessage to contain PII but not both?

2021-04-21 08:28 UTC, thewahome approved these changes

2021-04-21 12:24 UTC, baywet requested changes

2021-04-21 12:24 UTC, baywet commented on GraphWebApi/Telemetry/CustomPIIFilter.cs
> +                    "displayname",
id, givenName, surname, employeeId, phone numbers, all kind of upns and email addresses, and more probably need to be in there as well. Please cross check the [user properties](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0#properties) and see which ones apply.

We might actually take an allow list approach where properties we allow and want to track are kept, and the rest is discarded. This will protect us from having a workload adding a new PII property, app developers filtering on it and us logging it when it wasn't intended to.

2021-04-21 12:24 UTC, baywet commented on GraphWebApi/Telemetry/CustomPIIFilter.cs
> +                {"guidRegex", _guidRegex},
you're never reading the key, switch to a list instead?

2021-04-26 13:16 UTC, MaggieKimani1 commented on GraphWebApi/Telemetry/CustomPIIFilter.cs
> +                    "displayname",
I'm already masking the Id, email addresses and UPNs.
I've added a check for more user properties that you've suggested after counter-checking with the link you shared.

2021-04-27 12:04 UTC, baywet requested changes

2021-04-27 12:04 UTC, baywet commented on GraphWebApi/Properties/ServiceDependencies/local/appInsights1.arm.json
> +              "properties": {}
```suggestion
              "properties": {},
```

2021-04-27 12:04 UTC, baywet commented on GraphWebApi/Telemetry/CustomPIIFilter.cs
> +            var newQueryString = $"{queryString[0] + propertyName + queryString[2]}";
comments for the magic numbers

2021-04-27 12:04 UTC, baywet commented on GraphWebApi/Telemetry/CustomPIIFilter.cs
> +                        newQueryString = $"{text[0]}GET{newQueryString}responded{text[2]}";
comments for the magic numbers

2021-04-27 12:04 UTC, baywet commented on GraphWebApi/Telemetry/CustomPIIFilter.cs
> +            var propertyNames = new List<string>
move this to a static constant outside of the method to avoid initializing the list on every method call

2021-04-27 12:04 UTC, baywet commented on GraphWebApi/Telemetry/CustomPIIFilter.cs
> +                        customEvent.Properties["RequestPath"] = piiRegex.Replace(customEvent.Properties["RequestPath"], "****");
move the keys to constants to avoid duplication and facilitate maintenance

2021-04-27 17:59 UTC, baywet commented on GraphWebApi/Telemetry/CustomPIIFilter.cs
> +                        customEvent.Properties["RenderedMessage"] = piiRegex.Replace(renderedMessage, "****");
Maybe I wasn't clear enough: I didn't mean move things as a parameter. The code still has "requestPath" and "renderedMessage" defined 6 times only in that file.
1. Move those keys into `private const string`
2. Use those constants instead of redefining by passing them to the indexers

2021-04-28 11:28 UTC, baywet approved these changes

2021-04-28 11:31 UTC, merged