Replace cast CollectionPage with supported CollectionWithReferencesPa…
microsoftgraph/microsoft-graph-devx-api pull request #528
Opened 2021-04-08 12:40 UTC by fey101

…ge cast

Fixes #327

2021-04-08 12:45 UTC, baywet commented on CodeSnippetsReflection/LanguageGenerators/CSharpGenerator.cs
> +            return $"{type}{property}CollectionWithReferencesPage";
would that change affect all collections? even the ones that don't support references?

2021-04-08 12:59 UTC, fey101 commented on CodeSnippetsReflection/LanguageGenerators/CSharpGenerator.cs
> +            return $"{type}{property}CollectionWithReferencesPage";
Probably, yes. I'll look into this. Do you know of any collection that doesn't support references, that I could use to test this?

2021-04-08 13:04 UTC, baywet commented on CodeSnippetsReflection/LanguageGenerators/CSharpGenerator.cs
> +            return $"{type}{property}CollectionWithReferencesPage";
the lists collection on a SharePoint site is a good example.

2021-04-09 20:27 UTC, MIchaelMainer commented
At first glance, we may need to add a GetCollectionWithReferencesPageClassName(). This would be called here:
https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/851eea0381cf448d0671421fcd200079af23e4a2/CodeSnippetsReflection/LanguageGenerators/CSharpGenerator.cs#L558

When `typeProperties.IsNavigationProperty` and when the target is not contained.

2021-04-12 14:15 UTC, fey101 commented on CodeSnippetsReflection/LanguageGenerators/CSharpGenerator.cs
> +            return $"{type}{property}CollectionWithReferencesPage";
It appears b2xUserflows, b2cUserflows as well as sharepoint columns list all contain the attribute ContainsTarget=True. https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/clean_beta_metadata/cleanMetadataWithDescriptionsbeta.xml. Not sure what the differentiating factor will therefore be.

2021-04-12 14:20 UTC, baywet requested changes

2021-04-12 14:20 UTC, baywet commented on CodeSnippetsReflection/LanguageGenerators/CSharpGenerator.cs
> +                                stringBuilder.Append($"new {GetCollectionPageClassName((NavigationPropertySegment)pathSegment, path)}()\r\n{tabSpace}{{\r\n");
use as instead

2021-04-12 14:20 UTC, baywet commented on CodeSnippetsReflection/LanguageGenerators/CSharpGenerator.cs
> +        private string GetCollectionPageClassName(NavigationPropertySegment pathSegment, ICollection<string> path)
defensive programming

2021-04-12 14:23 UTC, fey101 commented
> At first glance, we may need to add a GetCollectionWithReferencesPageClassName(). This would be called here:
> https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/851eea0381cf448d0671421fcd200079af23e4a2/CodeSnippetsReflection/LanguageGenerators/CSharpGenerator.cs#L558
> 
> When `typeProperties.IsNavigationProperty` and when the target is not contained.

The `GetCollectionPageClassName` is only referenced once. Creating another class `GetCollectionWithReferencesPageClassName` would therefore render the former class stale. So instead, I chose to check within the class if `ContainsTarget` is true to differentiate between the 2. However, current problem is that both `b2cUserFlows`/`b2xUserFlows` and Sharepoint `columns` list appear to have the attribute `ContainsTarget=True`

2021-04-14 05:40 UTC, zengin approved these changes

2021-04-14 11:51 UTC, baywet requested changes

2021-04-14 11:51 UTC, baywet commented on CodeSnippetsReflection/LanguageGenerators/CSharpGenerator.cs
> +            if (navPathSegment.EdmType is IEdmCollectionType)
```suggestion
            if (navPathSegment.EdmType is IEdmCollectionType edmCollectionType)
```

2021-04-14 11:51 UTC, baywet commented on CodeSnippetsReflection/LanguageGenerators/CSharpGenerator.cs
> +                var definition =  (navPathSegment.EdmType as IEdmCollectionType).ElementType.Definition;
```suggestion
                var definition =  edmCollectionType.ElementType.Definition;
```

2021-04-14 11:51 UTC, baywet commented on CodeSnippetsReflection/LanguageGenerators/CSharpGenerator.cs
> +                throw new Exception($"Failed to get ElementType.Definition properties for {navPathSegment}");
```suggestion
                throw new InvalidOperationException($"Failed to get ElementType.Definition properties for {navPathSegment}");
```

2021-04-14 11:51 UTC, baywet commented on CodeSnippetsReflection/LanguageGenerators/CSharpGenerator.cs
> +                throw new Exception($"{navPathSegment.NavigationProperty.Name} does not contain property {property}");
```suggestion
                throw new InvalidOperationException($"{navPathSegment.NavigationProperty.Name} does not contain property {property}");
```

2021-04-14 11:51 UTC, baywet commented on CodeSnippetsReflection/LanguageGenerators/CSharpGenerator.cs
> +            var type = GetCsharpClassName(navPathSegment, path.ToList().GetRange(0, path.Count - 1));
```suggestion
            var type = GetCsharpClassName(navPathSegment, path.Take(path.Count - 1));
```

2021-04-14 11:51 UTC, baywet commented on CodeSnippetsReflection/LanguageGenerators/CSharpGenerator.cs
> +        private string GetCollectionPageClassName(NavigationPropertySegment navPathSegment, ICollection<string> path)
defensive programming on path, if you don't have anything in the collection (or if it's null) the method will derail

2021-04-14 11:51 UTC, baywet commented on CodeSnippetsReflection/LanguageGenerators/CSharpGenerator.cs
> +                throw new Exception(
```suggestion
                throw new InvalidOperationException(
```

2021-04-14 14:29 UTC, fey101 commented on CodeSnippetsReflection/LanguageGenerators/CSharpGenerator.cs
> +                var definition =  (navPathSegment.EdmType as IEdmCollectionType).ElementType.Definition;
@baywet , are you reviewing the most recent changes? We worked with Mustafa to simplify some of the contained code in a C# friendly manner. The most recent updates, include the commit "Csharp Syntax simplification".

2021-04-14 14:29 UTC, fey101 commented on CodeSnippetsReflection/LanguageGenerators/CSharpGenerator.cs
> +                throw new Exception($"Failed to get ElementType.Definition properties for {navPathSegment}");
same as above. this code block is outdated.

2021-04-14 14:30 UTC, fey101 commented on CodeSnippetsReflection/LanguageGenerators/CSharpGenerator.cs
> +                throw new Exception($"{navPathSegment.NavigationProperty.Name} does not contain property {property}");
Outdated code block

2021-04-14 14:36 UTC, fey101 commented on CodeSnippetsReflection/LanguageGenerators/CSharpGenerator.cs
> +            var type = GetCsharpClassName(navPathSegment, path.ToList().GetRange(0, path.Count - 1));
Thanks for the suggestions. Learnt on how to use a IEnumerable.Take. However, codeblock outdated as well.

2021-04-14 15:28 UTC, fey101 commented on CodeSnippetsReflection/LanguageGenerators/CSharpGenerator.cs
> +            var type = GetCsharpClassName(navPathSegment, path.ToList().GetRange(0, path.Count - 1));
Also `Path.Take` might not work especially in a situation where there's only 1 item in the path.

2021-04-14 18:43 UTC, baywet requested changes
Ignore my last batch of comments, it seams that I have reviewed the merge 🤦‍♂️

2021-04-14 18:43 UTC, baywet commented on CodeSnippetsReflection/LanguageGenerators/CSharpGenerator.cs
>              var type = GetCsharpClassName(pathSegment, path.ToList().GetRange(0, path.Count - 1));
I'm not sure what's the value of this get range since it's taking all the elements. Maybe a clone would be enough if the goal is to clone the collection?

2021-04-14 18:43 UTC, baywet commented on CodeSnippetsReflection/LanguageGenerators/CSharpGenerator.cs
> +                ?? throw new Exception("Path doesn't match with the metadata property description!" +
```suggestion
                ?? throw new InvalidOperationException("Path doesn't match with the metadata property description!" +
```

2021-04-14 19:39 UTC, fey101 commented on CodeSnippetsReflection/LanguageGenerators/CSharpGenerator.cs
>              var type = GetCsharpClassName(pathSegment, path.ToList().GetRange(0, path.Count - 1));
No, the goal is not to clone. The goal is to get the parent type( i.e. 1 level lower than the last element in the path). Using Take raises an error error CS1503: Argument 2: cannot convert from 'System.Collections.Generic.IEnumerable<string>' to 'System.Collections.Generic.ICollection<string>. On that line. Both with `var type = GetCsharpClassName(pathSegment, path.ToList().Take(path.Count - 1));` as well as `var type = GetCsharpClassName(pathSegment, path.Take(path.Count - 1));`

2021-04-14 20:34 UTC, zengin commented on CodeSnippetsReflection/LanguageGenerators/CSharpGenerator.cs
>              var type = GetCsharpClassName(pathSegment, path.ToList().GetRange(0, path.Count - 1));
This doesn't take all the elements, it gets all the elements except the last one. Second parameter is not `endIndex` but `count`.

Maybe the following is less confusing:
```suggestion
            var type = GetCsharpClassName(pathSegment, path.ToList().Take(path.Count - 1));
```

2021-04-15 12:02 UTC, baywet commented on CodeSnippetsReflection/LanguageGenerators/CSharpGenerator.cs
>              var type = GetCsharpClassName(pathSegment, path.ToList().GetRange(0, path.Count - 1));
alternatively you could also have used [skip last ](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.skiplast?view=net-5.0)

2021-04-15 12:03 UTC, baywet approved these changes

2021-04-15 13:34 UTC, merged