Add filter for search query options
microsoftgraph/microsoft-graph-devx-api pull request #566
Opened 2021-05-12 06:43 UTC by MaggieKimani1

2021-05-12 07:17 UTC, baywet requested changes

2021-05-12 07:17 UTC, baywet commented on TelemetryService/CustomPIIFilter.cs
> +                    if(requestPathValue.Contains("users") && renderedMessageValue.Contains("users"))
constant to avoid duplicating the key

2021-05-12 07:17 UTC, baywet commented on TelemetryService/CustomPIIFilter.cs
> +                if (requestUrl.Contains("users"))
use constant

2021-05-12 07:17 UTC, baywet commented on TelemetryService/CustomPIIFilter.cs
> +            if (querySegment.Contains(":"))
constant for this search operator

2021-05-12 07:17 UTC, baywet commented on TelemetryService/CustomPIIFilter.cs
> +                var searchSegments = querySegment.Split(":");
use constant

2021-05-12 07:17 UTC, baywet commented on TelemetryService/CustomPIIFilter.cs
> +                querySegment = $"'{ property}:{ propertyName}'";
use constant

2021-05-12 07:17 UTC, baywet commented on TelemetryService/CustomPIIFilter.cs
> +            if (querySegment.Contains(":"))
KQL supports [many different operators](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/keyword-query-language-kql-syntax-reference#:~:text=%20KQL%20operators%20for%20complex%20queries%20%201,the%20terms%20in%20the%20query%20are...%20More%20) but the graph implementation [seems to be restricted to only this one](https://docs.microsoft.com/en-us/microsoft-365/compliance/keyword-queries-and-search-conditions?view=o365-worldwide#searchable-email-properties). It might be worth adding the other operators and iterating over those to be future proof.

2021-05-12 11:12 UTC, MaggieKimani1 commented on TelemetryService/CustomPIIFilter.cs
> +                    if(requestPathValue.Contains("users") && renderedMessageValue.Contains("users"))
Oh yes.
Resolving..

2021-05-12 21:39 UTC, nikithauc commented on TelemetryService/CustomPIIFilter.cs
> +        private string SanitizeSearchQueryOption(string requestUrl)
@MaggieKimani1

2021-05-12 23:10 UTC, MIchaelMainer commented on TelemetryService/CustomPIIFilter.cs
> +        private string SanitizeSearchQueryOption(string requestUrl)
Because of this the entire content of search should be redacted.

2021-05-12 23:29 UTC, MIchaelMainer requested changes

2021-05-12 23:29 UTC, MIchaelMainer commented on TelemetryService.Test/CustomPIIFilterShould.cs
> +        [InlineData("https://localhost:44399/openapi?url=/users?$search='displayName=Meghan'",
Add scenarios:

```csharp
        [InlineData("https://localhost:44399/openapi?url=/users?$search='Meghan'",
                    "https://localhost:44399/openapi?url=/users?$search='****'")]
        [InlineData("https://localhost:44399/openapi?url=/users?$search='5555551212'",
                    "https://localhost:44399/openapi?url=/users?$search='****'")]
```

2021-05-13 06:11 UTC, MaggieKimani1 commented on TelemetryService/CustomPIIFilter.cs
> +        private string SanitizeSearchQueryOption(string requestUrl)
Yes, that's possible.

> Searches on people occur on both the displayName and emailAddress properties of the person resource.

But functionality on sanitizing default search properties on message, person and directory object collections has already been implemented on Graph Explorer so when the requests come in through autocomplete, we get the sensitive data already sanitized.

2021-05-13 06:27 UTC, MaggieKimani1 commented on TelemetryService/CustomPIIFilter.cs
> +        private string SanitizeSearchQueryOption(string requestUrl)
@MIchaelMainer does that mean I shouldn't leave out even the property searched and just mask everything within `?$search`?

2021-05-13 06:44 UTC, baywet submitted a review, later dismissed

2021-05-13 07:58 UTC, irvinesunday commented on TelemetryService/CustomPIIFilter.cs
> +        private const string users = "users";
Use PascalCasing for constants

2021-05-13 08:10 UTC, irvinesunday commented on TelemetryService/CustomPIIFilter.cs
> +
nit: remove whitespace between `if` and `else` block

2021-05-13 08:11 UTC, MaggieKimani1 commented on TelemetryService/CustomPIIFilter.cs
> +        private const string users = "users";
We're checking for the _**users**_ keyword in the incoming request url

2021-05-13 08:21 UTC, irvinesunday commented on TelemetryService/CustomPIIFilter.cs
> +        private string SanitizeSearchQueryOption(string requestUrl)
I think we should mask everything after `?search`. We really don't care much about the search criterion values used by a user.

2021-05-13 08:56 UTC, irvinesunday requested changes

2021-05-13 08:56 UTC, irvinesunday commented on TelemetryService/CustomPIIFilter.cs
> +        private const string users = "users";
I'm referring to the constant variable name, not the value. :)

2021-05-13 08:56 UTC, irvinesunday commented on TelemetryService/CustomPIIFilter.cs
> +                    if(requestPathValue.Contains(users) && renderedMessageValue.Contains(users))
Why are we only checking against `users`? This is a valid path request that would miss to be sanitized: `/openapi?url=/me/people/e3d0513b-449e-4198-ba6f-bd97ae7cae85`

2021-05-13 13:27 UTC, irvinesunday commented on TelemetryService/CustomPIIFilter.cs
> +            var searchOperator = "search=";
`$search` ?
So that we do not mask this query param value: `https://localhost:44399/samples?search='Hello World'`

2021-05-13 16:14 UTC, MIchaelMainer submitted a review, later dismissed

2021-05-13 17:08 UTC, irvinesunday approved these changes

2021-05-13 17:10 UTC, merged