Refactors, fixes and updates the TelemetryService
microsoftgraph/microsoft-graph-devx-api pull request #572
Opened 2021-05-18 16:30 UTC by irvinesunday

This PR proposes:
- Adding option for sanitizing trace events. Trace events will soon start being captured in an upcoming feature. Includes tests to validate this.
-  Refactors code by modularizing similar functionalities and renaming a few variables/methods for ease of maintenance and to promote consistency.
- Addresses a couple of extra OData `$filter` cases that need to be sanitized. Tests have been updated to validate this.
- Fixes a few bugs and updates the relevant tests where the below example request urls were not being sanitized properly:
 1. `/permissions?requesturl=/users/9f376303-1936-44a9-b4fd-7271483525bb/drives&method=GET`, 
2. `/permissions?requesturl=/users/20463493-79c2-4116-b87b-a20d06242e6a/drives&method=GET`. 

This was because the `_employeeIdRegex` `[0-9]{7}` was sanitizing the above GUIDs on the original value even after the `_guidRegex` already made a pass. Hence, 

1. would be: `/permissions?requesturl=/users/9f376303-1936-44a9-b4fd-****525bb/drives&method=GET`, and
2.  would be: `/permissions?requesturl=/users/****3-79c2-4116-b87b-a20d06242e6a/drives&method=GET`

Also, the event telemetry `RequestPath` and `RenderedMessage` values were skipped being sanitized for presence of OData `$search` options.

2021-05-18 18:59 UTC, MIchaelMainer requested changes
In your estimate, how much of the different filter forms in Microsoft Graph do we cover? How much of the OData filter forms do we cover?

I think I've covered all (or most) of the different OData `$filter` query options that have the potential of exposing PII. I used this OData [doc.](http://docs.oasis-open.org/odata/odata/v4.01/cs01/part2-url-conventions/odata-v4.01-cs01-part2-url-conventions.html#sec_SystemQueryOptionfilter) as reference to populate this check-list: https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/6ddb1944d2c1d49788635be669cc564afe838bf5/TelemetryService/CustomPIIFilter.cs#L45-L58

2021-05-18 18:59 UTC, MIchaelMainer commented on TelemetryService.Test/CustomPIIFilterShould.cs
> +                    "https://graphexplorerapi.azurewebsites.net/openapi?url=/users?$filter=emailAddress eq '****'")]
Can you add test data like this:

```csharp
[InlineData("https://graphexplorerapi.azurewebsites.net/openapi?url=/users?$filter=testProperty eq 'arbitraryPropertyData'",
                    "https://graphexplorerapi.azurewebsites.net/openapi?url=/users?$filter=testProperty eq '****'")]
```

We can't know the future where properties that will contain private data will be filterable. We should filter out all property values.

2021-05-18 18:59 UTC, MIchaelMainer commented on TelemetryService.Test/CustomPIIFilterShould.cs
> +                    "https://graphexplorerapi.azurewebsites.net/openapi?url=/users?$search=****")]
Add a test case with arbitrary data to demonstrate that we redact arbitrary search data

2021-05-18 18:59 UTC, MIchaelMainer commented on TelemetryService/CustomPIIFilter.cs
> +            if ((bool)!contents?.Any())
nit: maintain the negation in the same order as line 208 for readability

2021-05-18 20:08 UTC, irvinesunday commented on TelemetryService.Test/CustomPIIFilterShould.cs
> +                    "https://graphexplorerapi.azurewebsites.net/openapi?url=/users?$filter=emailAddress eq '****'")]
I see the sense in that. We're safer sanitizing everything that is filterable, instead of just focusing on the current PII potential fields:
```
"displayName",
"firstName",
"lastName",
"givenName",
"preferredName",
"surname"
```

2021-05-18 20:15 UTC, irvinesunday commented on TelemetryService.Test/CustomPIIFilterShould.cs
> +                    "https://graphexplorerapi.azurewebsites.net/openapi?url=/users?$search=****")]
Should we keep the sanitization/redaction of `$search` and `$filter` options to just `/users` and `/people` paths?

2021-05-18 20:37 UTC, irvinesunday commented on TelemetryService.Test/CustomPIIFilterShould.cs
> +                    "https://graphexplorerapi.azurewebsites.net/openapi?url=/users?$filter=emailAddress eq '****'")]
Should we keep the sanitization/redaction of `$search` and `$filter` values to just `/users` and `/people` paths?

2021-05-18 21:48 UTC, MIchaelMainer submitted a review, later dismissed
Do we get a deployment to staging when merging to dev?

2021-05-18 21:51 UTC, MIchaelMainer commented on TelemetryService.Test/CustomPIIFilterShould.cs
> +                    "https://graphexplorerapi.azurewebsites.net/openapi?url=/users?$filter=emailAddress eq '****'")]
No, we should sanitize on all $search and $filter. That is unless we know with certainty the privacy nature of the data. What might be an interesting approach is if we had an allow list of data that we are certain will not contain private data. That could provide us richer logging IF we need it. Do we have any actionable information for us based on the contents of query parameters? If not, let's sanitize it all.

2021-05-18 21:52 UTC, MIchaelMainer commented on TelemetryService.Test/CustomPIIFilterShould.cs
> +                    "https://graphexplorerapi.azurewebsites.net/openapi?url=/users?$search=****")]
Yes, as long as we aren't redacting based on that US phone number form.

2021-05-19 10:11 UTC, irvinesunday commented on TelemetryService.Test/CustomPIIFilterShould.cs
> +                    "https://graphexplorerapi.azurewebsites.net/openapi?url=/users?$filter=emailAddress eq '****'")]
Then I would posit that we also sanitize all _emails_, _GUIDS_, _mobile numbers_ and _employee ids_ from all paths. Initially we were just restricting to `/users` and `/people` paths. 
It is also worth noting that these sanitizations will occur on the query path of a given url, e.g. given a url: `https://graphexplorerapi.azurewebsites.net/openapi?url=/users?$expand=directreports($filter=firstName eq 'mary')` the sanitizable portion will be `?url=/users?$expand=directreports($filter=firstName eq 'mary')`

2021-05-19 10:15 UTC, irvinesunday commented on TelemetryService.Test/CustomPIIFilterShould.cs
> +                    "https://graphexplorerapi.azurewebsites.net/openapi?url=/users?$filter=emailAddress eq '****'")]
> Do we get a deployment to staging when merging to dev?

When we merge from `dev` into `master`

2021-05-19 11:22 UTC, baywet requested changes

2021-05-19 11:58 UTC, irvinesunday commented on TelemetryService/CustomPIIFilter.cs
> +            if (item is EventTelemetry and EventTelemetry customEvent)
Yeah. 
I think I'll even go ahead and merge those two `if` statements

2021-05-19 11:59 UTC, irvinesunday commented on TelemetryService/CustomPIIFilter.cs
> +                if (customEvent.Properties.ContainsKey(RequestPath) && customEvent.Properties.ContainsKey(RenderedMessage))
Ah. Read my mind!

2021-05-19 12:03 UTC, irvinesunday commented on TelemetryService/CustomPIIFilter.cs
> +            if (sanitizedContent.Contains(ODataFilterOperator))
True

2021-05-19 12:58 UTC, baywet approved these changes

2021-05-19 13:33 UTC, MIchaelMainer approved these changes

2021-05-19 13:39 UTC, merged