Sanitize telemetry request urls using uri template
microsoftgraph/microsoft-graph-devx-api pull request #585
Opened 2021-05-26 19:20 UTC by irvinesunday

This PR proposes:
- Updating the `CustomPIIFilter.cs` class to redact numbers from requests.
- Using the `UriTemplateMatcher` table populated by the `PermissionsService` to sanitize request urls by replacing them with matching uri templates from the table.
- All requests with the pattern `/permissions?requestUrl=xyz` or `/openapi?url=xyz` will be sanitized using the uri template matching.
  - Any query params will be stripped off the param values for `requestUrl` or `url`. This is required before performing the uri template matching.
  - The resulting base url will then be matched against the `PermissionsService` `UriTemplateMatcher` table. This table exposes a list of url templates for Graph endpoints. It is the same one used when matching permissions requests.
  - Any params that don't match `/permissions?requestUrl=xyz` or `/openapi?url=xyz`, for example `/samples?search='hello world'`(this is a valid query param for searching sample queries) or `/permissions?request=/abc?$filter(displayName eq 'Megan Bowen'` (this is an invalid query param - but still expected) will not be sanitized using the uri template matching method. (**NB**: For telemetry, we don't really care much about any succeeding query params coming in through the params (`requestUrl` or `url`), hence why we strip them off. We cannot account for all cases of incoming param values that are invalid, and thus they will be sanitized through the other available options.)
  - The above checks apply to Request telemetry and Event telemetry request urls. Trace telemetry will be sanitized using the other sanitization checks available.
  - Urls will still go through all other sanitization checks even after the above steps. 
- Telemetry tests have been updated in the `TelemetryService.Test` project.
- To enable to mock out the `UriTemplateMatcher` table from the `PermissionsService`, a `PermissionStoreFactoryMock` class has been created and used to create mocked instances of `IPermissionsStore` objects. This helps us get mocked instances of the `PermissionsService` class in both the `TelemetryService.Test` and `PermissionsService.Test` projects whilst maintaining code integrity and sanity. 
- The  `TelemetryService.Test` project now exposes sample JSON test files for the permissions endpoints mapping to be used for testing. 
- `PermissionsService.Test` has been updated to take advantage of the factory class as well.
- A new method for retrieving the `UriTemplateMatcher` table from the `PermissionsService` has been added to the interface `IPermissionsStore`. This will be used by the `TelemetryService` to get access to the aforementioned table. `PermissionsService` implements `IPermissionsStore`.
- Permissions seeding now happens on singleton object creation of `PermissionsStore`. This is important so as to ensure the `UriTemplateMatcher` table being used in the `TelemetryService` is always in a valid state.
- The `Extensions.cs` class in the `UtilityService` library has been updated with a new method. This method `RemoveParantheses` is used to sanitize a url before attempting to find a matching template in the `UriTemplateMatcher` table

2021-05-26 19:49 UTC, MaggieKimani1 approved these changes

2021-05-26 23:55 UTC, MIchaelMainer submitted a review, later dismissed
This is more like an Approved with Suggestions

2021-05-26 23:55 UTC, MIchaelMainer commented on UtilityService/Extensions.cs
> +        public static string RemoveParantheses(this string value)
The name should be changed to RemoveParenthesisKey() since the regex results in the removal of the entire key.

While we promote the [key-as-segment convention](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_KeyasSegmentConvention) in our docs and samples, we also need to support parenthesis-style convention.

As a consideration, instead of removing the parenthesis and all inside of it, it may make sense to just normalize it with key-as-segment.

2021-05-26 23:55 UTC, MIchaelMainer commented on UtilityService/Extensions.cs
> +            return Regex.Replace(value, @"\(.*?\)", string.Empty);
Since few humans remember regex expression syntax, please provide an example like:

// example input: `/v1.0/users('MeganB@M365.onmicrosoft.com')`
// example input: `/v1.0/users('3bf94edc-10ba-45ab-9664-0dc645461f99')`
// returns: `/v1.0/users`

2021-05-27 11:26 UTC, baywet requested changes

2021-05-27 11:26 UTC, baywet commented on TelemetryService.Test/TelemetryService.Test.csproj
> +  <ItemGroup>
I believe you don't need that block since you have a content block below for the same files.

2021-05-27 11:26 UTC, baywet commented on MockTestUtility/PermissionStoreFactoryMock.cs
> +            if (string.IsNullOrEmpty(configFilePath) && configuration == null)
break apart, saying "one of these values might be null" is less useful thank saying "this value is null"

2021-05-27 11:26 UTC, baywet commented on PermissionsService.Test/PermissionsStoreShould.cs
> +            _permissionsStore = PermissionStoreFactoryMock.GetPermissionStore(".\\TestFiles\\appsettingstest-valid.json");
use a constant for the folder name

2021-05-27 11:26 UTC, baywet commented on TelemetryService.Test/CustomPIIFilterShould.cs
> +            if (eventTelemetry.Properties.ContainsKey("RequestPath") && eventTelemetry.Properties.ContainsKey("RenderedMessage"))
I'm not sure whether you're testing this since you added it right above?

2021-05-27 11:26 UTC, baywet commented on TelemetryService/CustomPIIFilter.cs
> +                    var valueIndex = queryValue.IndexOf('=');
maybe add 1 here instead so you don't have to repeat it below?

2021-05-27 13:08 UTC, irvinesunday commented on UtilityService/Extensions.cs
> +        public static string RemoveParantheses(this string value)
Thanks for the heads up. I might have just discovered a better way around it.

2021-05-27 13:56 UTC, irvinesunday commented on UtilityService/Extensions.cs
> +            return Regex.Replace(value, @"\(.*?\)", string.Empty);
Since we don't want to remove paranthesis-styled keys from paths, I've added the below as examples instead in the XML documentation:
https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/6377bdf7a4d3a25735a9e977ed31405a70bf5fef/UtilityService/Extensions.cs#L53-L61

2021-05-27 14:12 UTC, irvinesunday commented on TelemetryService.Test/CustomPIIFilterShould.cs
> +            if (eventTelemetry.Properties.ContainsKey("RequestPath") && eventTelemetry.Properties.ContainsKey("RenderedMessage"))
That's really unnecessary. Thanks.

2021-05-27 14:26 UTC, irvinesunday commented on MockTestUtility/PermissionStoreFactoryMock.cs
> +            if (string.IsNullOrEmpty(configFilePath) && configuration == null)
I've added helpful comment to try and convey the intention:
https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/7ac4efe7d7d103e6dfda26fd39c4a7fe8f7cca58/MockTestUtility/PermissionStoreFactoryMock.cs#L35-L41

2021-05-27 14:27 UTC, baywet submitted a review, later dismissed

2021-05-27 19:47 UTC, MIchaelMainer requested changes

2021-05-27 19:47 UTC, MIchaelMainer commented on TelemetryService.Test/CustomPIIFilterShould.cs
> +                    "/permissions?requesturl=/students/'****'")]
I'd expect the output to be `/permissions?requesturl=/students/****`, not `/permissions?requesturl=/students/'****'`

2021-05-27 19:47 UTC, MIchaelMainer commented on TelemetryService.Test/CustomPIIFilterShould.cs
> +                    "/permissions?requesturl=/students/'****'")]
Could we make this so that it tests that we properly form intermediate segments as well.

`/permissions?requesturl=/students('MeganB@M365x214355.onmicrosoft.com')/classes`
`/permissions?requesturl=/students/****/classes`

2021-05-27 19:47 UTC, MIchaelMainer commented on UtilityService.Test/UtilityServiceExtensionsShould.cs
> +        public void RemoveParantheses(string targetString, string expectedString)
Global/Spelling. 

RemoveParantheses => RemoveParentheses

2021-05-27 19:47 UTC, MIchaelMainer commented on UtilityService.Test/UtilityServiceExtensionsShould.cs
> +        public void RemoveParantheses(string targetString, string expectedString)
Also, add a test case for composable function. It works as is.

        [InlineData("worksheets/microsoft.graph.range(address={address})/microsoft.graph.range(address={address})",
                    "worksheets/microsoft.graph.range/microsoft.graph.range")]

2021-05-27 19:47 UTC, MIchaelMainer commented on UtilityService.Test/UtilityServiceExtensionsShould.cs
> +        public void GetUriTemplatePathFormat(string targetString, string expectedString)
Add test case for composable function.

2021-05-27 19:47 UTC, MIchaelMainer commented on UtilityService/Extensions.cs
> +            return Regex.Replace(value, @"\(.*?\)", string.Empty);
That is different than parenthesis-styled keys. These are OData functions. We don't want to treat them the same.

2021-05-27 21:38 UTC, irvinesunday commented on TelemetryService.Test/CustomPIIFilterShould.cs
> +                    "/permissions?requesturl=/students/'****'")]
With regard to masking the email address value including the quotation marks as:
`/permissions?requesturl=/students('MeganB@M365x214355.onmicrosoft.com')` to be resolved to `/permissions?requesturl=/students/****` as opposed to `/permissions?requesturl=/students/'****'`
I am of the opinion that this shouldn't be a hard requirement as long as the crucial piece of information, the email address, is been masked successfully. 
Updating the email regex: https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/1d03de986e7f5496c3f2f09f3d927fc675a8f970/TelemetryService/CustomPIIFilter.cs#L31 to also match non-alphanumeric characters preceding or succeeding the email address value (except for the expected _  - and a .) would inadvertently also end up masking the parentheses or slashes - in such cases: `/students(MeganB@M365x214355.onmicrosoft.com)` or `/students/MeganB@M365x214355.onmicrosoft.com` inaccurately resolving to `/students****`

2021-05-27 21:43 UTC, irvinesunday commented on UtilityService.Test/UtilityServiceExtensionsShould.cs
> +        public void GetUriTemplatePathFormat(string targetString, string expectedString)
Added.

2021-05-27 21:43 UTC, irvinesunday commented on UtilityService.Test/UtilityServiceExtensionsShould.cs
> +        public void RemoveParantheses(string targetString, string expectedString)
Added

2021-05-27 22:02 UTC, MIchaelMainer commented on TelemetryService.Test/CustomPIIFilterShould.cs
> +                    "/permissions?requesturl=/students/'****'")]
Agreed about it not being a hard requirement. It does what it needs to do.

2021-05-27 22:39 UTC, MIchaelMainer approved these changes

2021-05-27 22:43 UTC, merged