Add Extra Instrumentation using Application Insights API
microsoftgraph/microsoft-graph-devx-api pull request #593
Opened 2021-06-07 18:49 UTC by MaggieKimani1

This PR proposes using the Application Insights API to send custom metrics by inserting a few lines of code in order to help better diagnose issues related to our API and obtain the stack trace whenever an exception is thrown.
We've implemented methods such as:
1. `TrackTrace` by adding trace messages for better logging and to capture diagnostic data and inspect them in Diagnostic Search tab in the App Insights portal
2. `TrackException` to send exception messages to Application Insights.

These methods have been plugged into the following controllers and service libraries:

- SamplesStore and Samples Controller
- PermissionsStore and Permissions Controller
- ChangesStore, ChangesService and the ChangesController
- OpenAPIService and OpenApi Controller

This helps to enrich our data collection, enhance tracking and examination of individual occurrences of exceptions and improving QoS in DevX API.

Resource: https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-custom-events-metrics
Fixes #560

2021-06-07 20:52 UTC, adhiambovivian commented
@MaggieKimani1  @baywet any reason why the telemetry & app monitoring on devxAPI is tightly coupled? Wouldn't it be beneficial to decouple all the telemetry work on DevXAPI to allow the two to evolve separately without heavy dependency?

2021-06-07 21:07 UTC, baywet commented
@adhiambovivian i believe Maggie and @irvinesunday will have more context here.
My involvement with devx Api have only been have Java snippets generation, dotnet 5 migration and high level pull requests reviews.

2021-06-08 07:50 UTC, fey101 requested changes

2021-06-08 07:50 UTC, fey101 commented on ChangesService/Services/ChangesStore.cs
> +            _telemetry?.TrackTrace($"Retrieving changelog records for locale '{locale}' from in-memory cache '{locale}'",
I think it would be prudent to remove args from the TrackTrace.message and put them in TrackTrace.properties so as to have all related logs bundled up together and filterable. Otherwise the logs may be too much to process.

2021-06-08 07:50 UTC, fey101 commented on ChangesService/Services/ChangesStore.cs
> +                _telemetry?.TrackTrace($"In-memory cache '{locale}' empty. " +
remove args from the TrackTrace.message and put them in TrackTrace.properties

2021-06-08 07:50 UTC, fey101 commented on ChangesService/Services/ChangesStore.cs
> +                        _telemetry?.TrackTrace($"In-memory cache '{lockedLocale}' of changelog records " +
remove args from the TrackTrace.message and put them in TrackTrace.properties

2021-06-08 07:50 UTC, fey101 commented on ChangesService/Services/ChangesStore.cs
> +                    sourceMsg = $"Successfully seeded changelog records for locale '{lockedLocale}' from source";
remove args from the TrackTrace.message and put them in TrackTrace.properties

2021-06-08 07:50 UTC, fey101 commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +                _telemetry?.TrackTrace($"Seeding permissions table from file source '{permissionFilePath}'",
remove args from the TrackTrace.message and put them in TrackTrace.properties

2021-06-08 07:50 UTC, fey101 commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +            _telemetry?.TrackTrace($"Retrieving permissions for locale '{locale}' from in-memory cache 'ScopesInfoList_{locale}'",
remove args from the TrackTrace.message and put them in TrackTrace.properties

2021-06-08 07:50 UTC, fey101 commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +                        _telemetry?.TrackTrace($"Successfully seeded permissions for locale '{locale}' from Azure blob resource",
remove args from the TrackTrace.message and put them in TrackTrace.properties

2021-06-08 07:50 UTC, fey101 commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +                        _telemetry?.TrackTrace($"In-memory cache 'ScopesInfoList_{locale}' of permissions " +
remove args from the TrackTrace.message and put them in TrackTrace.properties

2021-06-08 07:50 UTC, fey101 commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +            _telemetry?.TrackTrace($"Retrieving permissions for locale '{locale}' from GitHub repository",
remove args eg. '{locale}' above, from the TrackTrace.message and put them in TrackTrace.properties

2021-06-08 07:50 UTC, fey101 commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +                _telemetry?.TrackTrace($"{nameof(scopesInfoJson)} empty or null when creating the scopes information tables",
remove args i.e. the {nameof(scopesInfoJson)} from the TrackTrace.message and put them in TrackTrace.properties

2021-06-08 07:50 UTC, fey101 commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +                    _telemetry?.TrackTrace($"Url '{requestUrl}' not found",
remove args i.e. {requestUrl} from the TrackTrace.message and put them in TrackTrace.properties

2021-06-08 07:50 UTC, fey101 commented on GraphWebApi/Controllers/ChangesController.cs
> +                _telemetry?.TrackTrace($"Request to fetch changelog records for the requested culture info '{cultureInfo}'",
remove args from the TrackTrace.message and put them in TrackTrace.properties

2021-06-08 07:50 UTC, fey101 commented on GraphWebApi/Controllers/GraphExplorerSamplesController.cs
> +                    _telemetry?.TrackTrace($"Search value: '{search}' not found in: category, humanName or tip properties of sample queries",
remove args from the TrackTrace.message and put them in TrackTrace.properties

2021-06-08 07:50 UTC, fey101 commented on GraphWebApi/Controllers/GraphExplorerSamplesController.cs
> +                    _telemetry?.TrackTrace($"Sample query with id: {id} doesn't exist in the list of sample queries",
remove args i.e. id from the TrackTrace.message and put them in TrackTrace.properties

2021-06-08 09:52 UTC, MaggieKimani1 commented on ChangesService/Services/ChangesStore.cs
> +                _telemetry?.TrackTrace($"In-memory cache '{locale}' empty. " +
@fey101 as @irvinesunday has mentioned, according to [documentation](https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-custom-events-metrics#properties), the TrackTrace properties will group the trace events that are related by default on App Insights

2021-06-08 12:32 UTC, irvinesunday commented
Need to add Trace telemetry for _CodeSnippets_ as well?

2021-06-08 16:15 UTC, fey101 commented on ChangesService/Services/ChangesStore.cs
> +            _telemetry?.TrackTrace($"Retrieving changelog records for locale '{locale}' from in-memory cache '{locale}'",
@irvinesunday , Are you suggesting that TrackTrace.Properties is not the right place to place args or are you suggesting that even with the args in the message, tracktrace.Properties will group related logs by default? Not seeing where the latter is specified in the attached documentation.

2021-06-08 16:24 UTC, fey101 commented on ChangesService/Services/ChangesStore.cs
> +                _telemetry?.TrackTrace($"In-memory cache '{locale}' empty. " +
@MaggieKimani1 , this is what I see from the documentation


<!--StartFragment-->
properties | Map of string to string: Additional data used to filter exceptions in the portal. Defaults to empty.
-- | --


<!--EndFragment-->
Am wondering how it will know of related events if args in the message make the messages appear different for each unique instance.

2021-06-08 16:29 UTC, fey101 commented on ChangesService/Services/ChangesStore.cs
> +                _telemetry?.TrackTrace($"In-memory cache '{locale}' empty. " +
If the case is as you stated @MaggieKimani1 , then why did they not have the db.id in the following example as part of the message?
```C#
var telemetry = new Microsoft.ApplicationInsights.TelemetryClient();
telemetry.TrackTrace("Slow database response",
                SeverityLevel.Warning,
                new Dictionary<string,string> { {"database", db.ID} });
```

2021-06-08 17:30 UTC, MaggieKimani1 commented on ChangesService/Services/ChangesStore.cs
> +                _telemetry?.TrackTrace($"In-memory cache '{locale}' empty. " +
@fey101 in the above example, the db.id is used to enable filtering of all messages relating to a particular db whereas in our case, we're using the name of the controller or service library for us to keep track of all trace events fired by calling an endpoint.

2021-06-08 19:02 UTC, MIchaelMainer commented on ChangesService/Services/ChangesStore.cs
> +            _telemetry?.TrackTrace($"Retrieving changelog records for locale '{locale}' from in-memory cache '{locale}'",
Args in TrackTrace.message and TrackTrace.properties serve two related but different purposes. 

Regarding adding args to TrackTrace.properties, I think the question to ask ourselves is whether the argument is intended to be filtered or maybe queried. If I can answer in the affirmative to "is there a scenario where I want to filter on locale?", then we we should put that in TrackTrace.properties.

2021-06-08 19:21 UTC, MIchaelMainer approved these changes
approved pending others' signoff.

2021-06-08 19:21 UTC, MIchaelMainer commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +                        throw new InvalidOperationException("The permissions data sources cannot be empty." +
nit: the other controllers explicitly handle InvalidOperationException. PermissionsController implicitly handles this with the final catch(Exception). 

This would be a good place to trigger an alert that our permission data source is empty.

2021-06-08 19:38 UTC, irvinesunday commented
Unfortunately we are sanitizing all numerical data.

![image](https://user-images.githubusercontent.com/40403681/121246703-1d823480-c8aa-11eb-8d9c-87b93933ba78.png)

2021-06-09 18:19 UTC, fey101 commented on ChangesService/Services/ChangesStore.cs
> +            _telemetry?.TrackTrace($"Retrieving changelog records for locale '{locale}' from in-memory cache '{locale}'",
Resolving this since it makes sense that there will be no value in filtering based on locale, for now and in the foreseen future. And is useful in the message as seen [devX-API-AppInsights-Testing](https://ms.portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22SubscriptionId%22%3A%2268397ef5-9754-46e7-9572-9b15d12367f1%22%2C%22ResourceGroup%22%3A%22Graph-Explorer-API%22%2C%22Name%22%3A%22DevX-API-AppInsights-Testing%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252F68397ef5-9754-46e7-9572-9b15d12367f1%252FresourceGroups%252FGraph-Explorer-API%252Fproviders%252Fmicrosoft.insights%252Fcomponents%252FDevX-API-AppInsights-Testing%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel/%7B%22cacheId%22%3A%2237340994-198a-4857-9d14-6c94f21b17bf%22%2C%22eventTable%22%3A%22traces%22%2C%22timeContext%22%3A%7B%22durationMs%22%3A86400000%2C%22endTime%22%3A%222021-06-09T18%3A08%3A42.565Z%22%7D%7D)

2021-06-09 18:22 UTC, fey101 commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +                    _telemetry?.TrackTrace($"Url '{requestUrl}' not found",
is there a scenario where I want to filter on requestUrl? I feel like this is a valid case but if it's not, @MaggieKimani1 , feel free to resolve it.

2021-06-09 18:24 UTC, MaggieKimani1 commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +                        throw new InvalidOperationException("The permissions data sources cannot be empty." +
I'll definitely add that trace message where that exception is thrown. Thank you for noticing that!

2021-06-09 18:26 UTC, fey101 approved these changes

2021-06-09 18:50 UTC, baywet requested changes

2021-06-09 18:50 UTC, baywet commented on ChangesService/Services/ChangesService.cs
> +        public static TelemetryClient TelemetryClient
just out of curiosity, have you considered using a Lazy if you want a singleton?

2021-06-09 18:50 UTC, baywet commented on OpenAPIService/OpenApiService.cs
> +        public static TelemetryClient TelemetryClient
why is this repeated? couldn't we encapsulate it away in a telemetry service or something similar to make it reusable?

2021-06-10 16:14 UTC, MaggieKimani1 commented on ChangesService/Services/ChangesService.cs
> +        public static TelemetryClient TelemetryClient
I hadn't considered implementing it that way.
Thank you for the suggestion

2021-06-14 13:25 UTC, baywet requested changes

2021-06-14 13:25 UTC, baywet commented on TelemetryClient/ITelemetryClientSingleton.cs
> +      //  TelemetryClient GetTelemetryClient();
?

2021-06-14 13:25 UTC, baywet commented on TelemetryClient/TelemetryClientSingleton.cs
> +        public static TelemetryClient TelemetryClient { get; private set; }
duplicated with the same class in TelemetryClientFactory folder, remove

2021-06-14 13:25 UTC, baywet commented on GraphWebApi/Startup.cs
> +            services.AddSingleton<TelemetryClientSingleton>();
shouldn't the interface be present here as well so it can be injected into dependant services?

2021-06-14 13:25 UTC, baywet commented on ChangesService/Services/ChangesService.cs
> +            TelemetryClientSingleton.TelemetryClient?
why make a static reference? inject it in the constructor instead and have it as an instance property to get better decoupling.

2021-06-14 13:25 UTC, baywet commented on TelemetryClientFactory/TelemetryClientSingleton.cs
> +        public TelemetryClientSingleton(TelemetryClient telemetryClient)
Why would you implement the singleton pattern yourself? the framework does this for you in the startup configuration. Remove

2021-06-14 13:52 UTC, MaggieKimani1 commented on TelemetryClientFactory/TelemetryClientSingleton.cs
> +        public TelemetryClientSingleton(TelemetryClient telemetryClient)
There's a cyclic DI issue caused by injecting the IPermissionsStore into the constructor of the CustomPIIFilter class(it relies on the **UrlTemplateMatcher** from our PermissionsStore class for sanitization), and the TelemetryClient into the constructor of the PermissionsStore.
Implementing it this way helps to decouple the two classes as I couldn't reference the telemetry client via DI in the PermissionStore class without causing the DI issue. 

Is there a better approach that you can recommend?

2021-06-14 14:17 UTC, baywet commented on TelemetryClientFactory/TelemetryClientSingleton.cs
> +        public TelemetryClientSingleton(TelemetryClient telemetryClient)
I think we're coming back to @adhiambovivian 's comment about telemetry and APM being decoupled, maybe an opportunity for us to clean this as well?

2021-06-16 12:17 UTC, baywet requested changes

2021-06-16 12:17 UTC, baywet commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +            _telemetryClient = telemetryClient;
defensive programming, otherwise the methods will fail as it's readonly

2021-06-16 12:17 UTC, baywet commented on MockTestUtility/PermissionStoreFactoryMock.cs
> +            return new PermissionsStore(configuration, httpClientUtility, fileUtility, permissionsCache, null);
mock the telemetry client

2021-06-16 12:17 UTC, baywet commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +        public PermissionsStore(IConfiguration configuration,
The changes service needs a similar modification, the singleton needs to be removed

2021-06-18 10:12 UTC, MaggieKimani1 commented on MockTestUtility/PermissionStoreFactoryMock.cs
> +            return new PermissionsStore(configuration, httpClientUtility, fileUtility, permissionsCache, null);
This won't be necessary as the telemetry client param is optional

2021-06-18 12:28 UTC, baywet requested changes

2021-06-18 12:28 UTC, baywet commented on TelemetryService/CustomPIIFilter.cs
> +            _serviceProvider = serviceProvider;
```suggestion
            _serviceProvider = serviceProvider ?? throw new ArgumentNullException(nameof(serviceProvider), $"{ serviceProvider }: { nameof(serviceProvider) }");;
```

And delete the block above

2021-06-18 12:28 UTC, baywet commented on TelemetryService/CustomPIIFilter.cs
> +            var permissionsStore = _serviceProvider.GetRequiredService<IPermissionsStore>();
why don't you pass the IPermissionStore into the constructor directly and let the dependency injection framework do the work for you?

2021-06-18 12:47 UTC, MaggieKimani1 commented on TelemetryService/CustomPIIFilter.cs
> +            var permissionsStore = _serviceProvider.GetRequiredService<IPermissionsStore>();
This will cause a circular dependency which is what we are trying to avoid by using this approach

2021-06-18 13:03 UTC, baywet commented on GraphWebApi/Startup.cs
> +            services.AddSingleton<TelemetryClientSingleton>();
in the latest update this has been removed, but I believe we're not adding the telemetry client to the list of services anymore.

2021-06-18 13:04 UTC, baywet commented on TelemetryClientFactory/TelemetryClientSingleton.cs
> +        public TelemetryClientSingleton(TelemetryClient telemetryClient)
resolving as this as been worked around by calling the service provider within the service itself. Not ideal but works for now without requiring a major revamp.

2021-06-18 13:13 UTC, baywet commented on GraphWebApi/Startup.cs
> +            services.AddSingleton<TelemetryClientSingleton>();
nevermind, the Telemetry client class in use is the one provided by application insights and injected by the AI section. resolving

2021-06-18 13:14 UTC, baywet approved these changes
Thanks for making all the changes! 🚢

2021-06-18 13:15 UTC, merged