Initialize telemetry client
microsoftgraph/microsoft-graph-devx-api pull request #614
Opened 2021-06-21 07:51 UTC by MaggieKimani1

Previously, the ` _telemetryClient` field in the `OpenApiService` and `ChangesService` classes weren't being initialized correctly.
To resolve this, I've created interfaces for both services and registered them in Startup as singletons.

2021-06-21 11:58 UTC, baywet requested changes

2021-06-21 11:58 UTC, baywet commented on ChangesService/Interfaces/IChangesService.cs
> +    public interface IChangesService
the interface should contain the methods prototypes so consumers can refer to the interface and don't need to know about the implementation/downcast. A PIE starts with abstraction :)

2021-06-21 11:58 UTC, baywet commented on OpenAPIService/Interfaces/IOpenApiService.cs
> +    public interface IOpenApiService
same as IChangeService

2021-06-21 21:13 UTC, nikithauc commented on ChangesService/Interfaces/IChangesService.cs
> +    public interface IChangesService
If `IChangeService` and `IOpenApiService` contain the same abstract methods then please maintain a single interface with  the prototype with the common method.

2021-06-22 12:02 UTC, baywet requested changes

2021-06-22 12:02 UTC, baywet commented on OpenAPIService/OpenApiService.cs
> +                    _openApiTraceProperties.Add(UtilityConstants.TelemetryPropertyKey_SanitizeIgnore, "OpenApiService");
leverage a constant instead? of nameof(OpenApiService)

2021-06-22 12:03 UTC, baywet commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +                _permissionsTraceProperties.Add(UtilityConstants.TelemetryPropertyKey_SanitizeIgnore, "PermissionsStore");
constant or nameof

2021-06-22 12:04 UTC, baywet commented on GraphWebApi/Controllers/GraphExplorerSamplesController.cs
> +                _samplesTraceProperties.Add(UtilityConstants.TelemetryPropertyKey_SanitizeIgnore, "SamplesCount");
constant or nameof

2021-06-22 12:05 UTC, baywet commented on OpenAPIService.Test/OpenAPIDocumentCreatorMock.cs
> +            _openApiService = openApiService;
defensive programing otherwise the CreateOpenApiDocument method might fail

2021-06-22 13:04 UTC, MaggieKimani1 commented on OpenAPIService.Test/OpenAPIDocumentCreatorMock.cs
> +            _openApiService = openApiService;
Let me add that..

2021-06-22 14:09 UTC, baywet approved these changes

2021-06-22 14:13 UTC, merged