Fix: Revert explode value to false in operation parameters
microsoftgraph/microsoft-graph-devx-api pull request #621
Opened 2021-06-25 10:14 UTC by irvinesunday

Fixes https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/618

This PR:
- Adds an `OpenApiParameters` visitor method to walk through the list of operation parameters in an OpenApi document and set their properties `explode: false` if `style: form`
- Adds a test to validate this.

2021-06-25 12:36 UTC, baywet requested changes

2021-06-25 12:36 UTC, baywet commented on OpenAPIService/OperationSearch.cs
> +            foreach (var parameter in parameters)
```suggestion
            foreach (var parameter in parameters.Where(x => x.Style == ParameterStyle.Form))
```

2021-06-25 12:36 UTC, baywet commented on OpenAPIService/OperationSearch.cs
> +                if (parameter.Style == ParameterStyle.Form)
```suggestion
```

2021-06-25 12:36 UTC, baywet commented on OpenAPIService/OperationSearch.cs
> +                {
```suggestion
```

2021-06-25 12:36 UTC, baywet commented on OpenAPIService/OperationSearch.cs
> +                }
```suggestion
```

2021-06-25 12:36 UTC, baywet commented on OpenAPIService/OperationSearch.cs
> +                    parameter.Explode = false;
```suggestion
                 parameter.Explode = false;
```

2021-06-25 12:36 UTC, baywet commented on OpenAPIService.Test/OpenAPIDocumentCreatorMock.cs
> +                                        {
```suggestion
```

2021-06-25 12:36 UTC, baywet commented on OpenAPIService.Test/OpenAPIDocumentCreatorMock.cs
> +                                        }
```suggestion
```

2021-06-28 15:10 UTC, peombwa submitted a review, later dismissed

2021-07-05 14:37 UTC, baywet requested changes

2021-07-05 14:37 UTC, baywet commented on OpenAPIService/OperationSearch.cs
> +            _predicate = predicate;
```suggestion
            _predicate = predicate ?? throw new ArgumentNullException(nameof(predicate));
```

2021-07-05 16:24 UTC, baywet submitted a review, later dismissed

2021-07-05 16:44 UTC, baywet approved these changes

2021-07-05 16:47 UTC, merged