Fix: Get all distinct permissions
microsoftgraph/microsoft-graph-devx-api pull request #636
Opened 2021-07-12 11:02 UTC by irvinesunday

Fixes https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/635
Fixes https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/633

## Overview

Gets all distinct scopes from the permissions mapping files and from the Service Principal descriptions when servicing fetch-all permissions requests from both the [permissions-mapping](https://raw.githubusercontent.com/microsoftgraph/microsoft-graph-devx-content/dev/permissions/permissions-v1.0.json) and the [Service Principal](https://raw.githubusercontent.com/microsoftgraph/microsoft-graph-devx-content/dev/permissions/permissions-descriptions.json) descriptions.

### Notes

Resolves issues raised in this PR as well: https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/628
@baywet I felt this syntax provides better readability and contextualization:
https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/9835dbb0e5b9410e3db8b9178124d443bd4fbe7b/GraphExplorerPermissionsService/Services/PermissionsStore.cs#L407-L411

## Testing Instructions

- Run: https://localhost:44399/permissions?scopeType=Application
- Search for: `Channel.Create.Group`
- You should be able to see this sample query from the list.
- Run: https://localhost:44399/permissions?requesturl=/me&method=GET
- Search for: `Directory.AccessAsUser.All`
- There should only be one instance of this.

2021-07-12 12:46 UTC, baywet requested changes
Thanks for following up on this one.
IMHO the method syntax is vastly superior to the query syntax as some operations (distinct, firstordefault and many others) are simply not available with the query syntax last time I checked.
Plus the method syntax gives you a fluent style that "reads like english" except for the lambdas and gets close to functional style programming.

2021-07-12 12:46 UTC, baywet commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +                var scopes = new List<string>();
you could even append the distinct at the end of the statement here

2021-07-12 12:46 UTC, baywet commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +                    scopes = scopeCategory.Value?
First or default instead of foreach

2021-07-12 12:46 UTC, baywet commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +                if (scopeType.Contains(Delegated))
doing the comparison at each loop is not very optimal, get it out into a boolean var

2021-07-12 12:46 UTC, baywet commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +            var applicationScopesInfoTable = new Dictionary<string, ScopeInformation>();
same comment as previous for the initialization

2021-07-13 07:54 UTC, irvinesunday commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +                if (scopeType.Contains(Delegated))
True. 
I've gone for the option of using a single variable for the key: https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/181dcd4479d06b94bddbaf6994f8de40396e2218/GraphExplorerPermissionsService/Services/PermissionsStore.cs#L504

2021-07-13 07:58 UTC, irvinesunday commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +                    if (scopesInformationDictionary[Delegated].ContainsKey(scope))
This works too in breaking up the duplication
https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/181dcd4479d06b94bddbaf6994f8de40396e2218/GraphExplorerPermissionsService/Services/PermissionsStore.cs#L509-L512

2021-07-13 10:26 UTC, irvinesunday commented
> Thanks for following up on this one.
> IMHO the method syntax is vastly superior to the query syntax as some operations (distinct, firstordefault and many others) are simply not available with the query syntax last time I checked.
> Plus the method syntax gives you a fluent style that "reads like english" except for the lambdas and gets close to functional style programming.

Thank you for your feedback; much is learnt from these. 💪

2021-07-13 12:33 UTC, baywet requested changes
thanks for taking in all the changes!
Now that we've simplified a lot of the code, there's another opportunity to simplify a last section greatly.

2021-07-13 12:33 UTC, baywet commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +                    scopesInfo.Add(scopeInfo);
```suggestion
                    scopesInfo.Add(scopeInfo ?? new() {
                        ScopeName = scope
                    });
```

2021-07-13 12:33 UTC, baywet commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +                if (scopeInfo is not null)
remove if/else statement

2021-07-13 12:33 UTC, baywet commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +                if (scopesInformationDictionary[key].ContainsKey(scope))
```suggestion
scopesInformationDictionary[key].TryGetValue(scope, out var scopeInfo);
```

2021-07-13 12:33 UTC, baywet commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +                ScopeInformation scopeInfo = null;
remove variable declaration

2021-07-13 12:33 UTC, baywet commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +                {
remove block

2021-07-13 12:33 UTC, baywet commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +            foreach (var scope in scopes)
after applying all the changes I've suggested below, you'll find the foreach body is much simpler and easier to fit in a Select statement.
So I'd suggest
```CSharp
return scopes.Select(x => ....).ToList();
```
... being the updated body of the foreach.

2021-07-13 19:23 UTC, irvinesunday commented
> thanks for taking in all the changes!
> Now that we've simplified a lot of the code, there's another opportunity to simplify a last section greatly.

You are quite the minimalist 😄

2021-07-13 19:29 UTC, irvinesunday commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +            foreach (var scope in scopes)
All is fine and dandy now. But I have a question about switching up the `foreach` for the `Select`. What gains are we getting from this? IMO the `foreach` gives an easy-to-debug option if someone wants to _step into_ the code.

2021-07-13 19:42 UTC, baywet commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +            foreach (var scope in scopes)
strictly from a performance standpoint the approach has multiple benefits:
- it avoids assigning and growing multiple times a list, the tolist will create a list with the right number of memory spaces
- select can take advantage of vectorialization (SI MD) and other hardware instructions benefits on some platforms, improving performance with large datasets (although I doubt this will make a measurable change here)
- loops instructions are not necessarily aligned by default, leading to CPU "overhead" https://devblogs.microsoft.com/dotnet/loop-alignment-in-net-6/


from a semantic code approach: foreach to me translate into an "action" (for each of those items, I'm going to change/apply something), but select translate into data mapping (I want to get this subset/facet of that existing dataset). This makes it easier to parse mentally as your brain is already in the mode "we're mapping data" and not in the mode "we're performing an action, but wait, we're actually mapping data".

2021-07-13 19:50 UTC, baywet commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +            foreach (var scope in scopes)
another advantage I forgot to mention from a performance standpoint which partially applies here: let's assume we return IEnumerable instead of list, and we don't call toList after the select: this would enable deferred execution of the select/streaming of data. i.e.: the selection will only execute whenever a caller tries to enumerate the data. This is particularly useful on large datasets/whenever multiple transformations need to be applied (based on conditions on the data set (order, select, distinct,...)

2021-07-13 20:24 UTC, irvinesunday commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +            foreach (var scope in scopes)
I hear you

2021-07-13 20:32 UTC, baywet approved these changes

2021-07-13 20:48 UTC, merged