Adds a Known Issues endpoint
microsoftgraph/microsoft-graph-devx-api pull request #648
Opened 2021-07-23 10:45 UTC by MaggieKimani1

Fixes #619 
## Overview
Currently, there is a Known Issues board on Azure DevOps that consolidates a list of Microsoft Graph known issues in a central place to provide internal teams and customers a comprehensive process that enables the generation, tracking and keeping the known issues up to date. 

We shall use **DevX API** to surface the list of known issues on the `known issues tracking tool` by querying all the workItems in the [Known Issues Organization]
(https://dev.azure.com/microsoftgraph/Known%20Issues%20(staging)/_workitems/recentlyupdated/).
The Known Issues tracking tool will consume this endpoint, fetch the list of all known issues and surface them and their current state on the UI

This PR proposes:
- Adding a `/KnownIssues` endpoint 
- Adding a `KnownIssues` service library
- Updates `appsettings.json` with new known issues configuration
- Adds tests to validate the `KnownIssues` service library

### Demo

![image](https://user-images.githubusercontent.com/36787645/126769501-14ff3ed5-7677-4fa2-8ee2-ace1b5f5bd2b.png)

## Testing Instructions

- Run https://localhost:44399/knownissues

2021-07-23 13:15 UTC, baywet requested changes

2021-07-23 13:15 UTC, baywet commented on GraphWebApi/Controllers/KnownIssuesController.cs
> +            _knownIssueService = knownIssueService;
defensive programming

2021-07-23 13:15 UTC, baywet commented on GraphWebApi/Controllers/KnownIssuesController.cs
> +            var results = await _knownIssueService.QueryBugs();
don't await a single task, return the task

2021-07-23 13:15 UTC, baywet commented on KnownIssuesService/Interfaces/IKnownIssuesService.cs
> +        Task<List<KnownIssuesContract>> QueryBugs();
Async suffix for consistency

2021-07-23 13:15 UTC, baywet commented on KnownIssuesService/Models/KnownIssuesContract.cs
> +    public class KnownIssuesContract
why not `KnownIssue` ?

2021-07-23 13:15 UTC, baywet commented on KnownIssuesService/Models/KnownIssuesContract.cs
> +    {
have you thought about using a record?

2021-07-23 13:15 UTC, baywet commented on KnownIssuesService/Services/KnownIssuesService.cs
> +						contract.State = item.Fields["System.State"].ToString();
```suggestion
						contract.State = item.Fields.TryGetValue("System.State", out var state) ? state.ToString() : default;
```
And remove the surrounding if block
for all the instances below as well

2021-07-23 13:15 UTC, baywet commented on KnownIssuesService/Services/KnownIssuesService.cs
> +					return new List<KnownIssuesContract>();
```suggestion
					return knownIssuesList;
```

2021-07-23 13:15 UTC, baywet commented on KnownIssuesService/Services/KnownIssuesService.cs
> +					KnownIssuesContract contract = new KnownIssuesContract();
once the if statement simplifications below have been done, you'll be in a much better position to use property initialization here.

2021-07-23 13:15 UTC, baywet commented on KnownIssuesService/Services/KnownIssuesService.cs
> +				foreach (var item in items)
once you've simplified the if statements, and used property initialization, replace this foreach by a select statement on items, and then use tolist to assign the Konwnissueslist right away instead of growing it on a loop.

2021-07-23 13:15 UTC, baywet commented on KnownIssuesService/Services/KnownIssuesService.cs
> +				var test = result.AsOf;
this doesn't appear to be used, remove

2021-07-23 13:15 UTC, baywet commented on KnownIssuesService/Services/KnownIssuesService.cs
> +			Wiql wiql = new Wiql()
```suggestion
			return new Wiql()
```

2021-07-23 13:15 UTC, baywet commented on KnownIssuesService/Services/KnownIssuesService.cs
> +			return wiql;
```suggestion
```

2021-07-27 20:06 UTC, MaggieKimani1 commented on GraphWebApi/Controllers/KnownIssuesController.cs
> +            var results = await _knownIssueService.QueryBugs();
Resolving..

2021-07-27 20:21 UTC, MaggieKimani1 commented on KnownIssuesService/Services/KnownIssuesService.cs
> +			WorkItemQueryResult result = await _httpQueryClient.QueryByWiqlAsync(_workItemQuery, null, 100, null, CancellationToken.None).ConfigureAwait(false);
Thank you for pointing this out. Resolving..

2021-07-27 21:12 UTC, MaggieKimani1 commented on KnownIssuesService/Services/KnownIssuesService.cs
> +		private readonly IConfiguration _configuration;
I was using the _configuration object to initialize the _accessToken and _knownIssuesUrl within the constructor which I've seen is not necessary. Resolving..

2021-07-27 21:12 UTC, MaggieKimani1 commented on KnownIssuesService/Models/KnownIssuesContract.cs
> +    {
Would you mind expounding on this?

2021-07-28 11:57 UTC, baywet commented on KnownIssuesService/Models/KnownIssuesContract.cs
> +    {
records are immutable classes and they have syntax sugar that make boiler plate definitions faster. https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/records

2021-08-02 07:55 UTC, irvinesunday requested changes
Let's add the `knownissues` path and its operations in the OpenApi.yaml doc. https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/dev/GraphWebApi/wwwroot/OpenApi.yaml

2021-08-02 08:07 UTC, irvinesunday commented on KnownIssuesService/Services/KnownIssuesService.cs
> +    public class KnownIssuesService : IKnownIssuesService
Let's also add an XML summary documentation for this class.

2021-08-02 08:19 UTC, irvinesunday commented on KnownIssuesService/Services/KnownIssuesService.cs
> +		/// <returns>an instance of the authenticated VS Service</returns>
[nitpick] Capitalize first letter. Same applies for the subsequent instances of lower-cased first letter of sentences in the XML summaries.

2021-08-02 08:24 UTC, irvinesunday commented on KnownIssuesService/Services/KnownIssuesService.cs
> +		public Wiql QueryBuilder()
You can consider marking this method as `static`, since it does not access any instance data.

2021-08-02 08:36 UTC, irvinesunday commented on KnownIssuesService/Services/KnownIssuesService.cs
> +					KnownIssuesContract contract = new KnownIssuesContract();
Also, a better variable name could be `knownIssue` ?

2021-08-02 08:39 UTC, irvinesunday commented on KnownIssuesService/Services/KnownIssuesService.cs
> +				throw ex;
```suggestion
				throw;
```

2021-08-02 08:40 UTC, irvinesunday commented on KnownIssuesService/Services/KnownIssuesService.cs
> +				throw ex;
Rethrow to preserve stack details.

2021-08-02 08:41 UTC, irvinesunday commented on KnownIssuesService/Services/KnownIssuesService.cs
> +			catch (Exception ex)
```suggestion
			catch
```

2021-08-02 08:44 UTC, irvinesunday commented
@MaggieKimani1 are we considering capturing telemetry for the `KnownIssues` service and controller?

2021-08-02 08:47 UTC, irvinesunday commented on KnownIssuesService/Services/KnownIssuesService.cs
> +			List<WorkItem> items = await _httpQueryClient.GetWorkItemsAsync(ids, null, result.AsOf, null, null, null, CancellationToken.None).ConfigureAwait(false);
Defensive programming.

2021-08-02 08:49 UTC, irvinesunday commented on KnownIssuesService/Services/KnownIssuesService.cs
> +			_httpQueryClient = httpQueryClient;
Defensive programming: Use the `UtilityFunctions`: https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/dev/UtilityService/UtilityFunctions.cs

2021-08-02 09:05 UTC, irvinesunday commented on KnownIssuesService.Test/WorkItemTrackingHttpClientMock.cs
> +            var workItems = _workItemsStubData.GetWorkItems();
For uniformity, stick to either implicit or explicitly typed variables throughout.

2021-08-02 09:08 UTC, irvinesunday commented on KnownIssuesService.Test/WorkItemsStubData.cs
> +    public class WorkItemsStubData
Members of this class can be marked as `static` as they don't access any instance data.

2021-08-02 09:10 UTC, irvinesunday commented on KnownIssuesService.Test/KnownIssuesServiceShould.cs
> +            var ids = workItemQueryResult.WorkItems.Select(item => item.Id).ToArray();
[nit] Use explicitly typed variable for uniformity.

2021-08-02 09:12 UTC, irvinesunday commented on KnownIssuesService.Test/KnownIssuesServiceShould.cs
> +        public async Task GetQueryByWiqlAsync_Test()
Let's try and be consistent with the naming style of tests as used across the other tests in the solution.

2021-08-02 13:32 UTC, irvinesunday commented on KnownIssuesService.Test/KnownIssuesServiceShould.cs
> +            _configuration ??= new ConfigurationBuilder()
I don't think we're using this `_configuration` variable, we can remove.

2021-08-03 17:36 UTC, MaggieKimani1 commented
> @MaggieKimani1 are we considering capturing telemetry for the `KnownIssues` service and controller?



> @MaggieKimani1 are we considering capturing telemetry for the `KnownIssues` service and controller?

Yes we are

2021-08-04 10:03 UTC, irvinesunday commented on KnownIssuesService/Services/KnownIssuesService.cs
> +			_workItemQuery = QueryBuilder()
`QueryBuilder()` will never return `null` since it returns static data.

2021-08-04 10:04 UTC, irvinesunday commented on KnownIssuesService/Services/KnownIssuesService.cs
> +				?? throw new ArgumentNullException("Value cannot be null");
`QueryBuilder()` will never return `null` since it returns static data.

2021-08-04 10:06 UTC, irvinesunday commented on KnownIssuesService/Services/KnownIssuesService.cs
> +				?? UtilityFunctions.CheckArgumentNull(configuration, nameof(configuration));
The second expression evaluates when the first one is `null`, so there's no need to check `CheckArgumentNull()` here. You can add it as the 1st statement in the 'ctor. 
`UtilityFunctions.CheckArgumentNull(configuration, nameof(configuration));`

2021-08-04 10:18 UTC, irvinesunday commented on KnownIssuesService/Services/KnownIssuesService.cs
> +				?? UtilityFunctions.CheckArgumentNull(httpQueryClient, nameof(httpQueryClient));
Same as above, put the null-checks at the start of the 'ctor.

2021-08-04 10:39 UTC, irvinesunday commented on KnownIssuesService/Services/KnownIssuesService.cs
> +        public VssBasicCredential Authenticate()
This method is called internally by this class, it can be `private`. It would be good to evaluate most of the accessibility scopes of the other methods in this class. Most of them can be `private`.

2021-08-04 10:40 UTC, irvinesunday commented on KnownIssuesService/Services/KnownIssuesService.cs
> +        public VssBasicCredential Authenticate()
Also, we could use telemetry here to tell us that we are authenticating into VSS.

2021-08-04 10:41 UTC, irvinesunday commented on GraphWebApi/Controllers/KnownIssuesController.cs
> +                ?? UtilityFunctions.CheckArgumentNull(knownIssuesService, nameof(knownIssuesService));
This can go at the top of the function:
`UtilityFunctions.CheckArgumentNull(knownIssuesService, nameof(knownIssuesService));`

2021-08-04 11:40 UTC, baywet requested changes
thanks for taking in my initial comments. A few minor things left.

2021-08-04 11:40 UTC, baywet commented on KnownIssuesService.Test/KnownIssuesService.Test.csproj
> +    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.9.4" />
```suggestion
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.10.0" />
```

2021-08-04 11:40 UTC, baywet commented on KnownIssuesService/Services/KnownIssuesService.cs
> +			var accessToken = _configuration[AccessTokenValue];
if the second constructor is used, the _configuration field will be null. Either add defensive programing here or initialize the configuration in the second constructor as well.

2021-08-04 11:40 UTC, baywet commented on KnownIssuesService/Services/KnownIssuesService.cs
> +			var knownIssuesUri = _configuration[KnownIssuesPath];
same comment about configuration

2021-08-04 11:40 UTC, baywet commented on KnownIssuesService/Services/KnownIssuesService.cs
> +            if (ids.Length == 0)
indent

2021-08-04 11:40 UTC, baywet commented on KnownIssuesService/Services/KnownIssuesService.cs
> +			WorkItemQueryResult result = await GetQueryByWiqlAsync();
```suggestion
			var result = await GetQueryByWiqlAsync();
```
(consistency)

2021-08-04 14:16 UTC, MaggieKimani1 commented on KnownIssuesService/Services/KnownIssuesService.cs
> +		private List<KnownIssue> KnownIssuesList { get; set; }
Good point.

2021-08-04 18:03 UTC, MaggieKimani1 commented on KnownIssuesService/Services/KnownIssuesService.cs
> +            if (ids.Length == 0)
This unfortunately seems like a github issue since the code is well indented on my machine.

2021-08-04 18:42 UTC, baywet submitted a review, later dismissed

2021-08-04 20:10 UTC, irvinesunday approved these changes
👍🏽

2021-08-04 20:18 UTC, merged