Cleanup codebase
microsoftgraph/microsoft-graph-devx-api pull request #668
Opened 2021-08-23 10:01 UTC by MaggieKimani1

## Overview
This PR proposes:

1.  Removal of deprecated authentication code by:
    - Removing the protected endpoints i.e. post, update and delete
    - Removing the sample query policies used for authorization and their implementation
    - Removing the `SamplesPolicyServiceShould.cs` test class
2. Renames the projects for consistency
3. Cleans up `SampleServiceShould.cs` test class

2021-08-23 12:50 UTC, baywet requested changes

2021-08-23 12:50 UTC, baywet commented on GraphWebApi/Controllers/SamplesController.cs
> +            _telemetryClient = telemetryClient;
defensive programing

2021-08-23 12:50 UTC, baywet commented on GraphWebApi/Controllers/SamplesController.cs
> +                if (filteredSampleQueries.Count == 0)
```suggestion
                if (!filteredSampleQueries.Any())
```

2021-08-23 12:50 UTC, baywet commented on GraphWebApi/Controllers/SamplesController.cs
> +                _telemetryClient?.TrackException(exception,
this should be handled by a middleware instead of being on each method. https://www.thecodebuzz.com/global-exception-handling-in-net-core-using-middleware-component

2021-08-23 12:50 UTC, baywet commented on GraphWebApi/Controllers/SamplesController.cs
> +                if (sampleQueriesList == null || sampleQueriesList.SampleQueries.Count == 0)
refactor to a method instead of defining this multiple times

2021-08-23 12:50 UTC, baywet commented on GraphWebApi/Controllers/SamplesController.cs
> +                SampleQueryModel sampleQueryById = sampleQueriesList.SampleQueries.Find(x => x.Id == Guid.Parse(id));
move the guid parse outside of the condition to avoid parsing multiple times

2021-08-23 12:50 UTC, baywet commented on GraphWebApi/Controllers/SamplesController.cs
> +        {
defensive programing on the parameters

2021-08-23 12:50 UTC, baywet commented on GraphWebApi/Controllers/SamplesController.cs
> +        {
defenseive programing

2021-08-24 18:00 UTC, MaggieKimani1 commented on GraphWebApi/Controllers/SamplesController.cs
> +                if (sampleQueriesList == null || sampleQueriesList.SampleQueries.Count == 0)
Thanks for pointing this out!

2021-08-24 18:40 UTC, MaggieKimani1 commented on GraphWebApi/Controllers/SamplesController.cs
> +        {
The org and branchName params are optional https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/96b978bfd1da00ff4c263df2d03068f2fb272105/GraphWebApi/Controllers/SamplesController.cs#L136-L144

2021-08-24 18:46 UTC, MaggieKimani1 commented on GraphWebApi/Controllers/SamplesController.cs
> +        {
Same case to this.
The search param is also optional
https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/96b978bfd1da00ff4c263df2d03068f2fb272105/GraphWebApi/Controllers/SamplesController.cs#L50-L60

2021-08-24 19:19 UTC, baywet commented on GraphWebApi/Controllers/SamplesController.cs
> +        {
sure, validating the id param is a good start :)

2021-08-24 19:21 UTC, baywet commented on GraphWebApi/Controllers/SamplesController.cs
> +        {
right resolving

2021-08-30 07:13 UTC, merged