Update sonarcloud.yml file
microsoftgraph/microsoft-graph-devx-api pull request #679
Opened 2021-08-31 16:54 UTC by MaggieKimani1

- Renames file
- Adds the default branch
- Add dispatch events to allow for manual queue of workflows
- Adds a job for checking the secret and include condition in the build step
- Add path to test coverage files

2021-08-31 18:07 UTC, baywet reviewed
would you mind adding coverlet as well please?

2021-08-31 19:01 UTC, baywet requested changes

2021-08-31 19:01 UTC, baywet commented on .github/workflows/sonarcloud.yml
> +          ./.sonar/scanner/dotnet-sonarscanner begin /k:"microsoftgraph_microsoft-graph-devx-api" /o:"microsoftgraph2" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarclou
```suggestion
          ./.sonar/scanner/dotnet-sonarscanner begin /k:"microsoftgraph_microsoft-graph-devx-api" /o:"microsoftgraph2" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"
```

2021-08-31 19:08 UTC, baywet approved these changes

2021-08-31 19:22 UTC, merged

2021-09-02 07:02 UTC, Ndiritu commented on .github/workflows/sonarcloud.yml
>      steps:
@MaggieKimani1 Noticed this from the snippet shared on teams. Does DevX-API need to Set up JDK 11?

2021-09-02 07:17 UTC, Ndiritu commented on .github/workflows/sonarcloud.yml
>      steps:
My mistake. Realise it's needed by the SonarQube server