Fix analysis bugs
microsoftgraph/microsoft-graph-devx-api pull request #699
Opened 2021-09-13 12:19 UTC by MaggieKimani1

Fixes analysis bugs exposed by Sonarcloud

![image](https://user-images.githubusercontent.com/36787645/133082128-58e31c65-d3ed-4d3b-9ca1-d48447ff764d.png)

2021-09-13 12:51 UTC, baywet requested changes

2021-09-13 12:51 UTC, baywet commented on FileService/Services/HttpClientUtility.cs
> +                throw new InvalidOperationException();
maybe add a message so we can pinpoint the issue easily?

2021-09-13 12:51 UTC, baywet commented on OpenAPIService/OpenApiService.cs
> +                    tempTargetChild = targetChild?.Children
is it possible that children is null when targetChild is not?

2021-09-13 12:51 UTC, baywet commented on OpenAPIService/PowershellFormatter.cs
> +            if (schema != null)
collapse this if statement with the next one

2021-09-13 13:31 UTC, irvinesunday commented on OpenAPIService/OpenApiService.cs
> +                    tempTargetChild = targetChild?.Children
It is possible. We should also add a null-conditional after `Children`

2021-09-13 13:37 UTC, MaggieKimani1 commented on OpenAPIService/OpenApiService.cs
> +                    tempTargetChild = targetChild?.Children
@irvinesunday

2021-09-13 15:45 UTC, MaggieKimani1 commented on OpenAPIService/PowershellFormatter.cs
> +            if (schema != null)
Is this to help with test coverage?

2021-09-13 16:51 UTC, baywet requested changes

2021-09-13 16:51 UTC, baywet commented on FileService/Services/HttpClientUtility.cs
> +                throw new InvalidOperationException("The request message was already sent by the HttpClient instance.");
I don't believe this message accurately reflects the situation here.

2021-09-13 16:52 UTC, baywet commented on OpenAPIService/PowershellFormatter.cs
> +            if (schema != null)
no, it just makes less code to maintain, and reading it easier. Thanks for making the change.

2021-09-13 22:05 UTC, zengin requested changes

2021-09-14 16:27 UTC, MaggieKimani1 commented on FileService/Services/HttpClientUtility.cs
> +            return httpResponseMessage.IsSuccessStatusCode ? throw new Exception(fileContents) : fileContents;
That's correct, thank you for pointing it out.
Resolving...

2021-09-14 17:19 UTC, baywet submitted a review, later dismissed

2021-09-17 07:12 UTC, zengin submitted a review, later dismissed

2021-09-17 07:12 UTC, zengin commented on FileService.Test/HttpClientUtilityShould.cs
> +            HttpContent httpContent = new StringContent("Content as string");
nit: consider defining "Content as string" as constant.

2021-09-17 11:35 UTC, baywet approved these changes

2021-09-17 12:01 UTC, merged