[Feature] Add new path to support Resource Explorer
microsoftgraph/microsoft-graph-devx-api pull request #709
Opened 2021-09-21 15:16 UTC by irvinesunday

This PR: 
- Creates an additional path on the `OpenApiController` --> `/openapi/tree` for surfacing the `OpenApiUrlTreeNode`. This will be used by Graph Explorer for the new Resource Explorer feature.
- Updates the OpenAPI description to describe the above new path.
- Adds support for serializing the  `OpenApiUrlTreeNode` into JSON. The output result will look like this: https://microsoft.sharepoint-df.com/:u:/t/GraphTooling/EaaJlJIk21xIpI8_pbZQim8Bjy16CJgadxTc8G7JD0QcJg
The prettier version: https://microsoft.sharepoint-df.com/:u:/t/GraphTooling/ERL1J2BviFRBnLqbgIzjq90Bf3eryzE8sM-fFU-C3zY0Ww?e=A8qURb
- Refactors the code that is responsible for creating new or attaching on to an `OpenApiUrlTreeNode` into a common reusable method.
- Adds tests to validate the above capabilities.

2021-09-21 16:37 UTC, baywet requested changes

2021-09-21 16:37 UTC, baywet commented on GraphWebApi/Controllers/OpenApiController.cs
> +            return Ok(Encoding.ASCII.GetString(stream.ToArray()));
maybe set the response content type? So browser know what to do

2021-09-21 18:19 UTC, baywet commented on GraphWebApi/Controllers/OpenApiController.cs
> +            return Ok(Encoding.ASCII.GetString(stream.ToArray()));
what are you doing to get that? Are you using StringContent?

2021-09-22 08:42 UTC, irvinesunday commented on GraphWebApi/Controllers/OpenApiController.cs
> +            return Ok(Encoding.ASCII.GetString(stream.ToArray()));
Got it

2021-09-22 08:45 UTC, irvinesunday commented
@MaggieKimani1 @baywet is there a way to suppress SonarCloud from checking test coverage in the Controllers? These are not captured in our unit tests but they affect the overall % coverage.

2021-09-22 09:23 UTC, MaggieKimani1 commented
@irvinesunday the test coverage report is generated by Coverlet and sent to SonarCloud. You can try using the `[ExcludeFromCodeCoverage]` attribute in the Controller class.
 https://gunnarpeipman.com/aspnet-core-exclude-code-coverage/

2021-09-22 11:43 UTC, baywet approved these changes

2021-09-22 13:21 UTC, thewahome approved these changes

2021-09-22 13:42 UTC, MaggieKimani1 approved these changes

2021-09-22 13:45 UTC, merged