[New feature bug fix] Avoids caching OpenAPIUrlTreeNode document
microsoftgraph/microsoft-graph-devx-api pull request #713
Opened 2021-09-23 23:41 UTC by irvinesunday

This PR:

- Attempts to fix a bug that was surfaced during staging tests of the new Resource Explorer endpoint feature. The `OpenApiService` was not correctly returning the expected `OpenApiUrlTreeNode` data for a requested version/label, e.g. 
  - These calls: 
  https://graphexplorerapi-staging.azurewebsites.net/openapi/tree?graphVersions=v1.0 or 
  https://graphexplorerapi-staging.azurewebsites.net/openapi/tree?graphVersions=beta 
fetches the `OpenApiUrlTreeNode` document for both `v1.0` and `beta` versions instead of the specific requested version, `v1.0` or `beta`. This is because, according to the implementation logic, we were improperly caching the `OpenApiUrlTreeNode` document that gets created. 
  - The proposed implementation in this PR is that the  `OpenApiUrlTreeNode` gets created every time it is requested, without storing it in a cache. The `CreateOpenApiUrlTreeNode` method accepts a `Collection` of `OpenApiDocument` and simply creates an `OpenApiUrlTreeNode` without caching the result. This will help in ensuring that the tree nodes do not go stale over time. Instead, the tree nodes will always be a representation of the cached versions of the `OpenApiDocument`.
- Actions user feedback that proposes calling the path `/openapi/tree` without providing any query params should default to fetching the `OpenApiUrlTreeNode` containing both `v1.0` and `beta` paths, and not the initial default `v1.0` paths.

2021-09-24 08:36 UTC, thewahome commented on GraphWebApi/Controllers/OpenApiController.cs
> +            graphVersions = string.IsNullOrEmpty(graphVersions) ? "*" : graphVersions.ToLower();
Nice that the parameter is not required if someone wants both versions

2021-09-24 11:14 UTC, irvinesunday commented on GraphWebApi/Controllers/OpenApiController.cs
> +            graphVersions = string.IsNullOrEmpty(graphVersions) ? "*" : graphVersions.ToLower();
Thank you for your earlier suggestion 😉

2021-09-24 11:55 UTC, baywet requested changes

2021-09-24 11:55 UTC, baywet commented on GraphWebApi/Controllers/OpenApiController.cs
> +        public async Task<IActionResult> Get([FromQuery] string graphVersions,
```suggestion
        public async Task<IActionResult> Get([FromQuery] string graphVersions = "*",
```

2021-09-24 11:55 UTC, baywet commented on GraphWebApi/Controllers/OpenApiController.cs
> +            graphVersions = string.IsNullOrEmpty(graphVersions) ? "*" : graphVersions.ToLower();
```suggestion
```

2021-09-24 11:55 UTC, baywet commented on GraphWebApi/Controllers/OpenApiController.cs
> +                graphVersionsList.Add(graphVersions);
```suggestion
                graphVersionsList.Add(graphVersions.ToLower());
```

2021-09-24 11:55 UTC, baywet commented on GraphWebApi/Controllers/OpenApiController.cs
>              List<string> graphVersionsList = new();
```suggestion
            HashSet<string> graphVersionsList = new();
```

2021-09-27 11:46 UTC, baywet requested changes

2021-09-27 11:46 UTC, baywet commented on GraphWebApi/Controllers/OpenApiController.cs
>              else
```suggestion
            else if(!string.IsNullOrEmpty(graphVersions))
```

2021-09-27 11:46 UTC, baywet commented on GraphWebApi/Controllers/OpenApiController.cs
>              }
else throw? or return a bad request?

2021-09-27 12:23 UTC, irvinesunday commented on GraphWebApi/Controllers/OpenApiController.cs
>              }
I already made a similar change before reading your suggestion here 😄

2021-09-27 12:23 UTC, baywet approved these changes

2021-09-27 12:35 UTC, merged