Task/tour content
microsoftgraph/microsoft-graph-devx-api pull request #787
Opened 2021-11-16 12:47 UTC by Onokaev

## Overview
Adds an endpoint for Graph Explorer product tour content (/toursteps)

### Demo

Optional. Screenshots, `curl` examples, etc.

### Notes
The actual content will change as well as tests that verify the total number of steps. 

## Testing Instructions
Run the solution then type this url on your browser: https://localhost:44399/toursteps. This should fetch content from the blob storage
For github tests, type the url on your browser: https://localhost:44399/toursteps?org=microsoftgraph&branchName=dev

2021-11-16 13:48 UTC, baywet requested changes

2021-11-16 13:48 UTC, baywet commented on TourStepsService.Test/TestFiles/tour-steps_ja-JP.json
> +
this one is not valid json, is it expected?

2021-11-16 13:48 UTC, baywet commented on TourStepsService/Models/TourStepsList.cs
> +        public List<TourStepsModel> TourSteps { get; set; }
```suggestion
        public List<TourStepsModel> TourSteps { get; set; } = new();
```

and remove the constructor

2021-11-16 13:48 UTC, baywet commented on TourStepsService/Models/TourStepsModel.cs
> +                if (value != "" && !Uri.IsWellFormedUriString(value, UriKind.Absolute))
you should probably trim the value before you perform the checks

2021-11-16 13:48 UTC, baywet commented on TourStepsService/Models/TourStepsModel.cs
> +                return new QueryObject();
are we expecting to return a new value with each call? shouldn't you just init the property instead?

2021-11-16 13:48 UTC, baywet commented on TourStepsService/Services/TourStepsStore.cs
> +            _httpClientUtility = httpClientUtility;
defensive programing otherwise FetchTourStepsListAsync will fail

2021-11-16 13:48 UTC, baywet commented on TourStepsService/Services/TourStepsStore.cs
> +        public async Task<TourStepsList> FetchTourStepsListAsync(string locale)
FYI using a proxy/decorator design pattern would have been more elegant rather than mixing the cache and logic layers.

2021-11-16 13:48 UTC, baywet commented on TourStepsService/Services/TourStepsStore.cs
> +                    string queriesFilePathSource =
mixed use of type or var all over this PR, chose one, stick to it.

2021-11-16 13:48 UTC, baywet commented on GraphWebApi/Controllers/TourStepsController.cs
> +        public async Task<IActionResult> GetTourStepsListAsync(string org, string branchName)
```suggestion
        public async Task<IActionResult> GetTourStepsListAsync(string org = default, string branchName = default)
```

so people can call the endpoint without providing values for those two parameters

2021-11-16 14:23 UTC, Onokaev commented on TourStepsService.Test/TestFiles/tour-steps_ja-JP.json
> +
No, it's not valid json, but it's expected. The endpoint is supposed to return null if the file being fetched is empty

2021-11-16 14:24 UTC, Onokaev commented on TourStepsService/Models/TourStepsModel.cs
> +                return new QueryObject();
Sure. Let me fix this

2021-11-16 14:26 UTC, Onokaev commented on TourStepsService/Services/TourStepsStore.cs
> +        public async Task<TourStepsList> FetchTourStepsListAsync(string locale)
Let me look into this

2021-11-19 07:23 UTC, Onokaev commented on TourStepsService/Services/TourStepsStore.cs
> +        public async Task<TourStepsList> FetchTourStepsListAsync(string locale)
I have looked at the proxy/decorator design patterns and it's good design. I was however trying to maintain the same principle applied in Sample Queries and Permissions endpoints.
 
Is it okay if this design change is planned for and tracked as a separate task?

2021-11-22 13:47 UTC, baywet requested changes

2021-11-22 13:47 UTC, baywet commented on GraphWebApi/Controllers/TourStepsController.cs
> +    [ExcludeFromCodeCoverage]
any specific reason why the controller should be excluded?

2021-11-22 13:47 UTC, baywet commented on SamplesService.Test/GithubTestFiles/Org/Repo/Branch/sample-queries/sample-queries-test_es-ES.json
> +        "
looks like unvoluntary change

2021-11-23 05:49 UTC, Onokaev commented on GraphWebApi/Controllers/TourStepsController.cs
> +    [ExcludeFromCodeCoverage]
The rest of the controllers are excluded from CodeCoverage and have no unit tests. It seems like a convention with this repo.
However, the methods that are called in the controllers have been covered in separate unit tests

2021-11-23 05:49 UTC, Onokaev commented on SamplesService.Test/GithubTestFiles/Org/Repo/Branch/sample-queries/sample-queries-test_es-ES.json
> +        "
Yes. Fixed

2021-11-25 10:45 UTC, irvinesunday commented on TourStepsService.Test/TourStepsServiceShould.cs
> +            // Get serialized JSON string of the list of sample queries
Misleading comment 😄

2021-11-25 10:46 UTC, irvinesunday commented on TourStepsService.Test/TourStepsServiceShould.cs
> +        public void ThrowArgumentNullExceptionIfDeserializeSampleQueriesListJsonStringParameterIsNull()
Misleading test method name 👀

2021-11-25 10:47 UTC, irvinesunday commented on TourStepsService.Test/TourStepsStoreShould.cs
> +            // Act - Fetch ja-JP sample queries which is empty
Misleading comment

2021-11-25 10:48 UTC, irvinesunday commented on TourStepsService.Test/TourStepsStoreShould.cs
> +            // Act - Fetch ja-JP samples which is empty
Misleading comment

2021-11-25 10:53 UTC, irvinesunday commented on TourStepsService/Services/TourStepsStore.cs
> +            // Fetch the requisite sample path source based on the locale
Misleading comment

2021-11-25 10:59 UTC, irvinesunday commented on SamplesService.Test/SamplesStoreShould.cs
> +
Unnecessary whitespace

2021-11-25 10:59 UTC, irvinesunday commented on SamplesService.Test/SamplesStoreShould.cs
> +
Unnecessary whitespace

2021-11-25 11:00 UTC, irvinesunday commented on SamplesService/Models/SampleQueriesList.cs
> +﻿// ------------------------------------------------------------------------------------------------------------------------------------------------------
👍🏽

2021-11-26 06:46 UTC, Onokaev commented on TourStepsService.Test/TourStepsServiceShould.cs
> +            // Get serialized JSON string of the list of sample queries
Fixed

2021-11-26 06:46 UTC, Onokaev commented on TourStepsService.Test/TourStepsServiceShould.cs
> +        public void ThrowArgumentNullExceptionIfDeserializeSampleQueriesListJsonStringParameterIsNull()
Fixed

2021-11-26 06:46 UTC, Onokaev commented on TourStepsService.Test/TourStepsStoreShould.cs
> +            // Act - Fetch ja-JP sample queries which is empty
Fixed

2021-11-26 06:46 UTC, Onokaev commented on TourStepsService.Test/TourStepsStoreShould.cs
> +            // Act - Fetch ja-JP samples which is empty
Fixed

2021-11-26 06:47 UTC, Onokaev commented on TourStepsService/Services/TourStepsStore.cs
> +            // Fetch the requisite sample path source based on the locale
Fixed

2021-11-26 06:47 UTC, Onokaev commented on SamplesService.Test/SamplesStoreShould.cs
> +
Fixed

2021-11-26 06:47 UTC, Onokaev commented on SamplesService.Test/SamplesStoreShould.cs
> +
Fixed

2021-11-26 06:48 UTC, irvinesunday commented
Remember to also add the new path to the OpenAPI definition doc.: https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/dev/GraphWebApi/wwwroot/OpenApi.yaml

2021-11-26 10:12 UTC, irvinesunday submitted a review, later dismissed

2021-11-26 13:26 UTC, baywet submitted a review, later dismissed

2021-11-26 14:04 UTC, baywet requested changes

2021-11-26 14:04 UTC, baywet commented on TourStepsService.Test/TourStepsService.Test.csproj
> +    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.9.4" />
```suggestion
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.0.0" />
```

2021-11-26 14:04 UTC, baywet approved these changes

2021-11-26 17:14 UTC, irvinesunday approved these changes

2021-11-29 07:11 UTC, merged