[Feature]: Support regex-based filtering on operationIds query parameter
microsoftgraph/microsoft-graph-devx-api pull request #802
Opened 2021-11-25 13:00 UTC by danielmbaluka

## Overview

This PR adds the support for filtering Open API by operationIds query parameter.
 For example: GET `https://graphexplorerapi.azurewebsites.net/openapi?operationIds=deviceManagement.reports*`

### Demo
<img width="349" alt="filter-by-operation-ids" src="https://user-images.githubusercontent.com/6814355/143445969-28fbc336-f306-4ab7-a2bd-1d57ca788b82.PNG">

2021-11-25 13:29 UTC, baywet requested changes

2021-11-25 13:29 UTC, baywet commented on OpenAPIService/OpenApiService.cs
> +                    var regex = new Regex(operationIdsArray[0]);
we should probably surround this with a try catch in case the regex is invalid to return a sanitized exception.

2021-11-26 09:13 UTC, irvinesunday commented on OpenAPIService/OpenApiService.cs
> +                    var regex = new Regex(operationIdsArray[0]);
What's an example of an invalid regex in this case?

Ideally we should just return a `404` with a relevant message. Example,
![image](https://user-images.githubusercontent.com/40403681/143556214-e7e2fe2f-b123-46fa-8474-e594c56eb9b3.png)

2021-11-26 09:35 UTC, irvinesunday commented on OpenAPIService.Test/OpenAPIServiceShould.cs
> +        public void SupportFilteringOpenApiDocumentByRegexOnOperationIdsAndTags(string operationIds, string tags)
Improvement suggestion:
```
 [Theory]
        [InlineData("^users.", null, 3)]
        [InlineData("^users.|^applications.", null, 5)]
        [InlineData(null, "^users.", 3)]
        [InlineData(null, "^users.user$", 2)]
        [InlineData(null, "^users.|^communications.|^applications.", 6)]
        public void SupportFilteringOpenApiDocumentByRegexOnOperationIdsAndTags(string operationIds, string tags,int pathCount)
        {
            // Act
            var predicate = _openApiService.CreatePredicate(operationIds: operationIds,
                                                          tags: tags,
                                                          url: null,
                                                          source: _graphMockSource,
                                                          graphVersion: GraphVersion);

            var subsetOpenApiDocument = _openApiService.CreateFilteredDocument(_graphMockSource, Title, GraphVersion, predicate);

            // Assert
            Assert.Equal(pathCount, subsetOpenApiDocument.Paths.Count);
        }
```

2021-11-26 13:20 UTC, danielmbaluka commented on OpenAPIService.Test/OpenAPIServiceShould.cs
> +        public void SupportFilteringOpenApiDocumentByRegexOnOperationIdsAndTags(string operationIds, string tags)
Thank you @irvinesunday, I have implemented the suggestion.

2021-11-26 13:25 UTC, baywet commented on OpenAPIService/OpenApiService.cs
> +                    var regex = new Regex(operationIdsArray[0]);
[[ would be an invalid regex for example

2021-11-26 13:39 UTC, danielmbaluka commented on OpenAPIService/OpenApiService.cs
> +                    var regex = new Regex(operationIdsArray[0]);
@irvinesunday here is an example of an invalid regex.
<img width="644" alt="invalid-regex-example" src="https://user-images.githubusercontent.com/6814355/143589318-fc7d7386-72c5-45b7-b7ba-dbc8a2306577.PNG">

2021-11-26 13:45 UTC, darrelmiller commented
We just finished moving slicing capabilities to Hidi.  The goal is to stop using devX for slicing.  This should have been implemented in the OpenAPI.NET slicing service, not in DevX API.

2021-11-26 13:56 UTC, baywet commented on OpenAPIService/OpenApiService.cs
> +                    var regex = new Regex(operationIdsArray[0]);
works for me, we're not leaking the stack trace and responding with a comprehensive error message.

2021-11-26 13:56 UTC, baywet approved these changes

2021-11-26 16:38 UTC, irvinesunday commented
> We just finished moving slicing capabilities to Hidi. The goal is to stop using devX for slicing. This should have been implemented in the OpenAPI.NET slicing service, not in DevX API. /cc @irvinesunday @adhiambovivian @MaggieKimani1

Hidi can now easily just port this to its codebase 😁. In the meantime, I think DevX API can continue exposing this new feature until a full switch to Hidi is realised.

2021-11-26 16:57 UTC, irvinesunday approved these changes

2021-11-29 14:34 UTC, MaggieKimani1 commented
> > We just finished moving slicing capabilities to Hidi. The goal is to stop using devX for slicing. This should have been implemented in the OpenAPI.NET slicing service, not in DevX API. /cc @irvinesunday @adhiambovivian @MaggieKimani1
> 
> Hidi can now easily just port this to its codebase 😁. In the meantime, I think DevX API can continue exposing this new feature until a full switch to Hidi is realised.

In the meantime, I can import this functionality into Hidi. 😊

2021-12-01 14:56 UTC, danielmbaluka commented
This feature is not needed in DevX API for now. It will be ported to Hidi.

2021-12-01 14:56 UTC, closed without merging