PowerShell Snippets Generation
microsoftgraph/microsoft-graph-devx-api pull request #812
Opened 2021-12-02 23:19 UTC by millicentachieng

## Overview

Add PowerShell snippets generator 

Snippet includes importing the relevant module and the actual Microsoft Graph command and parameters. 

### Example
The PowerShell equivalent of  `GET https://graph.microsoft.com/v1.0/users/48d31887-5fad-4d73-a9f5-3c356e68a038` is:
```
Import-Module Microsoft.Graph-Users

Get-MgUser -UserId $userId
```

## Testing Instructions
- Run DevX API locally
- Use an API client of choice to make the call below
```
POST https://localhost:44399/api/graphexplorersnippets?lang=powershell&generation=openapi

GET /v1.0/me HTTP/1.1
Host: graph.microsoft.com
Content-Type: application/json
````
- Use different Microsoft Graph queries in the request body to test for other results

2021-12-03 14:07 UTC, baywet requested changes
excellent first draft! a few comments.

2021-12-03 14:07 UTC, baywet commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/PowerShellGenerator.cs
> +                path = meSegmentRegex.Replace(path, "/users/{user-id}");
```suggestion
                path = meSegmentRegex.Replace(path, "/users/{");
```

In case the id parameter name is different for some reason.

2021-12-03 14:07 UTC, baywet commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/PowerShellGenerator.cs
> +            path = $"^{Regex.Replace(path, "(?<={)(.*?)(?=})", "(\\w*-\\w*|\\w*)")}$";
move the regex to a static precompiled property to avoid paying the code of compiling the regex every time

2021-12-03 14:07 UTC, baywet commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/PowerShellGenerator.cs
> +        private static string TrimNamespace(string path)
isn't this method already in the string extensions? drop one of them

2021-12-03 14:07 UTC, baywet commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/PowerShellGenerator.cs
> +                    using (var parsedBody = JsonDocument.Parse(snippetModel.RequestBody, new JsonDocumentOptions { AllowTrailingCommas = true }))
oooh I didn't know about that option!! can you replicate it for go and typescript please? it's going to fix a few snippets

2021-12-06 19:48 UTC, millicentachieng commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/PowerShellGenerator.cs
> +                    using (var parsedBody = JsonDocument.Parse(snippetModel.RequestBody, new JsonDocumentOptions { AllowTrailingCommas = true }))
Done for C#, Typescript, and Go.

2021-12-06 19:48 UTC, millicentachieng commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/CSharpGenerator.cs
> +			switch (snippetModel.ContentType?.Split(';').First().ToLowerInvariant()) {
Done

2021-12-06 19:49 UTC, millicentachieng commented on CodeSnippetsReflection.OpenAPI/OpenApiSchemaExtensions.cs
> +            if (schema.AllOf.Count == 0 && schema.AnyOf.Count == 0 && schema.OneOf.Count == 0)
Done.

2021-12-07 01:31 UTC, peombwa commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/PowerShellGenerator.cs
> +                    throw new ArgumentNullException("Microsoft.Graph PowerShell SDK could not be found on this machine. Please install the SDK using 'Install-Module Microsoft.Graph'.");
Good catch! The implementation was based around AzDo pipelines (we can install the module as task), but this won't be the case for Azure websites. I'll add the repo as a submodule instead.

2021-12-07 16:33 UTC, peombwa commented on CodeSnippetsReflection.OpenAPI/LanguageGenerators/PowerShellGenerator.cs
> +                path = meSegmentRegex.Replace(path, "/users/{user-id}");
This is just us replacing `/me` segment with a `/users/[user-id}`. The matching logic will in `GetCommandForRequest` method will handle all this.

2021-12-08 13:07 UTC, baywet commented
@peombwa I saw the changes but both the sonarcloud and the devx api workflows are failing, hence I didn't leave another review because I was expecting more changes to come. Would you mind having a look at why these are failing please?

2021-12-09 12:51 UTC, baywet approved these changes

2022-01-04 14:04 UTC, baywet commented
@millicentachieng I looks like a bad merged happened last time you merged dev to your branch:
- [your version of the snippets pipeline doesn't have a setup dotnet 6 task](https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/d511508e6b34fc4b1ba8501e1ca3e2f3839d6f70/pipelines/snippets.yml#L47)
- [dev version has](https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/e41d1bb25e5e27d4649e012cc70f63d8f2f320c8/pipelines/snippets.yml#L52)

I suggest that you rebase on dev, dropping the merging commit, and re-handling the conflicts, let me know if you need any help with that.

(from a clean state)

```Shell
git switch dev
git pull
git switch feature/powershelSnippetsGeneration
git rebase -i dev
```

edit the document ([i]), replace `pick` by `drop` in front of the merge commit (a097f3c), save ([esc], [w], [q], [enter]).
let me know if you need any help with that.

2022-01-04 14:44 UTC, millicentachieng commented
@baywet, we had this [PR](https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/839), updating the snippets pipeline, merged to dev yesterday. Merging dev into feature/powershellSnippetsGeneration should fix the failing pipeline.

2022-01-04 14:50 UTC, baywet commented
ah! thanks! I missed a few things while out. disregard my rebase instruction and proceed with the merge then, thanks!

2022-01-04 15:19 UTC, baywet approved these changes

2022-01-04 18:58 UTC, peombwa approved these changes

2022-01-05 07:15 UTC, merged