Use OData query options for the Changes endpoint
microsoftgraph/microsoft-graph-devx-api pull request #828
Opened 2021-12-15 12:15 UTC by irvinesunday

Fixes https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/720

This PR:
- Uses OData query options (`top` and `skip`) in place of `page` and `pageLimit` to filter `ChangeLogRecords`. This is to align the API to Graph API standards.
- Update relevant tests to validate the above.

2021-12-15 13:10 UTC, baywet requested changes

2021-12-15 14:42 UTC, irvinesunday commented on ChangesService/Services/ChangesService.cs
> +                if (searchOptions.Top != null && searchOptions.Skip > 0)
Please clarify your suggestion. There's is validation logic for those two properties done in the class: https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/5fb9e1f844771cb5f65702b83b88231344e50ae2/ChangesService/Models/ChangeLogQueryOptions.cs?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L23-L51

Did you mean I remove the default initializations from the query params of the controller action?

![image](https://user-images.githubusercontent.com/40403681/146206715-985e33c8-0f37-4ed3-a67c-5d382498eee7.png)

2021-12-15 14:51 UTC, baywet commented on ChangesService/Services/ChangesService.cs
> +                if (searchOptions.Top != null && searchOptions.Skip > 0)
I mean that:
- top should not be nullable, and have a default value
- the setter for top in `ChangeLogQueryOptions` should have validation for a maximum value
- conditional blocks down from this comments could then be greatly simplified as you should be able to systematically pass top/skip

2021-12-16 09:43 UTC, irvinesunday commented on ChangesService/Services/ChangesService.cs
> +                if (searchOptions.Top != null && searchOptions.Skip > 0)
Since we can't know the maximum value allowable for `top` in our case, we can't validate for this nor set a default value for it, unless we go with `int.MaxValue`. However, with `skip`, since it can safely default to `0` we can now simplify the conditional statements as below:

![image](https://user-images.githubusercontent.com/40403681/146347162-902923cf-925b-4acc-b198-a70b8f8233f3.png)

2021-12-16 17:53 UTC, baywet commented on ChangesService/Services/ChangesService.cs
> +                if (searchOptions.Top != null && searchOptions.Skip > 0)
couldn't you decide of an arbitrary value for top like graph does to 30?

2021-12-16 17:59 UTC, irvinesunday commented on ChangesService/Services/ChangesService.cs
> +                if (searchOptions.Top != null && searchOptions.Skip > 0)
This would limit a client that wants to retrieve all the changelog data in the returned response.

2021-12-16 18:01 UTC, baywet commented on ChangesService/Services/ChangesService.cs
> +                if (searchOptions.Top != null && searchOptions.Skip > 0)
do we want to allow them to do that though? what's going to be the impact on the API's reliability/performance when retrieving a large changelog?

2021-12-16 20:23 UTC, irvinesunday commented on ChangesService/Services/ChangesService.cs
> +                if (searchOptions.Top != null && searchOptions.Skip > 0)
The entire response data is currently appr. less than 4MB and with less than 1000 changelog entries (which grows steadily). This is served back from a cache by the server. On the other hand, the OpenAPI endpoint serves back a much larger cached doc. at appr. 29MB.

2021-12-16 21:08 UTC, baywet commented on ChangesService/Services/ChangesService.cs
> +                if (searchOptions.Top != null && searchOptions.Skip > 0)
how much do you expect it to grow over the next 5 years?

2021-12-16 22:10 UTC, irvinesunday commented on ChangesService/Services/ChangesService.cs
> +                if (searchOptions.Top != null && searchOptions.Skip > 0)
I can't give an approximation on that until I investigate and find out how long the changelog data has been live. This is external data.

2022-01-11 16:03 UTC, irvinesunday commented on ChangesService/Services/ChangesService.cs
> +                if (searchOptions.Top != null && searchOptions.Skip > 0)
@baywet I have opted to use a max value (top) of 500 items.

2022-01-11 16:09 UTC, baywet approved these changes

2022-01-11 17:17 UTC, merged