Removes function parameters from incoming urls when querying for permissions
microsoftgraph/microsoft-graph-devx-api pull request #948
Opened 2022-04-18 14:19 UTC by irvinesunday

Fixes https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/924

This PR addresses the below when querying for permissions:
- Fixes a bug that was translating namespace-simplified function parameters as path segments.
- Removes function parameters from incoming request urls.
- Updates the permission test appropriately.

2022-04-18 14:22 UTC, baywet submitted a review, later dismissed

2022-04-18 16:31 UTC, zengin approved these changes

2022-04-19 06:35 UTC, millicentachieng requested changes

2022-04-19 06:35 UTC, millicentachieng commented on PermissionsService.Test/PermissionsStoreShould.cs
>          [Fact]
This test can be written as follows (Line 186 - 219):

```
[Theory]
[InlineData("/workbook/worksheets/{id}/charts/{id}/image")]
[InlineData("/workbook/worksheets/{id}/charts/{id}/image(width={value})")]
public void RemoveFunctionParametersFromRequestUrlsDuringLoadingAndQueryingOfPermissionsFiles(string url)
{
	// Act
	List<ScopeInformation> result =
		_permissionsStore.GetScopesAsync(scopeType: DelegatedWork,
										 requestUrl: url,
										 method: "GET").GetAwaiter().GetResult();

	/* Assert */
	Assert.Collection(result,
		item =>
		{
			Assert.Equal("Files.ReadWrite", item.ScopeName);
			Assert.Equal("Have full access to your files", item.DisplayName);
			Assert.Equal("Allows the app to read, create, update, and delete your files.", item.Description);
			Assert.False(item.IsAdmin);
		});
}
```
Sorry, a GitHub suggestion doesn't work here.

2022-04-19 08:49 UTC, irvinesunday commented on PermissionsService.Test/PermissionsStoreShould.cs
>          [Fact]
I was wondering how I'd do that. Thanks 😄

2022-04-19 09:59 UTC, millicentachieng approved these changes

2022-04-19 11:04 UTC, merged