Fixes enum generation for TS
microsoftgraph/microsoft-graph-devx-api pull request #955
Opened 2022-04-25 21:19 UTC by rkodev

## Overview

Resolved Enum Generation for typescript code

Fixes https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/815

## Testing Instructions

Generated code for https://docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-post?view=graph-rest-1.0&tabs=typescript

2022-04-25 21:46 UTC, zengin requested changes
Can you please add a test case for this?

2022-04-25 21:51 UTC, rkodev commented
> Can you please add a test case for this?

Will do :-)

2022-04-25 23:46 UTC, zengin commented on CodeSnippetsReflection.OpenAPI.Test/TypeScriptGeneratorTest.cs
> +            const string userJsonObject = "{  \"displayName\": \"Test create\",  \"settings\": {    \"recurrence\": {      \"pattern\": {        \"type\": \"weekly\",        \"interval\": 1      },
nit on readability:
```suggestion
            const string userJsonObject = @"{
    ""displayName"": ""Test create"",
    ""settings"": {
        ""recurrence"": {
            ""pattern"": {
                ""type"": ""weekly"",
                ""interval"": 1
            },
            ""range"": {
                ""type"": ""noEnd"",
                ""startDate"": ""2020-09-08T12:02:30.667Z""
            }
        }
    }
}";
```

2022-04-25 23:47 UTC, zengin submitted a review, later dismissed

2022-04-26 07:52 UTC, zengin approved these changes
Thank you @rkodev for the tests!

2022-04-26 07:58 UTC, merged